### ISSUE TITLE
如何添加音乐播放器

### ISSUE THREAD

**Issue by beamaster** [viosey/hexo-theme-material#109]
请问如何添加一个音乐播放器盒子🎵，没有弄过，有经验的朋友欢迎来指点一下，谢谢

**Comment by viosey** [comment]
请参考这篇文章 http://www.jianshu.com/p/53e0d2a617da
但我未实测过，未知是否可行

**Comment by cubesky** [comment]
如果你有音乐的直链，可以直接在 .md 文件中写 <audio src="地址"></audio> 来支持音乐播放
这里是[我的博客中的音乐播放](https://liyin.date/slogan/)
