### ISSUE TITLE
New feature：多说使用 title 作为 thread key

### ISSUE THREAD

**Issue by 40huo** [viosey/hexo-theme-material#11]
以前的评论不能显示，添加新评论后每个post下都出现了该条评论。
但在多说后台看是正常的。

**Comment by viosey** [comment]
请参考这个 issue 的解决方案
https://github.com/viosey/typecho-theme-material/issues/46

**Comment by 40huo** [comment]
哦，这样，我看的时候不仔细。。。
之前用的 next，会自动把 URL 当作 Thread Key，我觉得这个功能也挺方便的，能否加一个？

**Comment by viosey** [comment]
OK👌
