### ISSUE TITLE
Shell code does not color well

### ISSUE THREAD

**Issue by pidupuis** [viosey/hexo-theme-material#114]
The color system does not work well for bash.

In particular, as soon as the code contains a comment, everything else is treating as a comment.

Try this:

```bash
# a comment
echo "foo"
```

Compared to:

```bash
echo "foo"
```

**Comment by cubesky** [comment]
@pidupuis We are now trying to fix the highlight issues. We prepare to use prism.js to highlight codes.

**Comment by pidupuis** [comment]
Great news! :)

**Comment by pidupuis** [comment]
Duplicate from https://github.com/viosey/hexo-theme-material/issues/58

**Comment by cubesky** [comment]
Fixed in `1.3.0`
已在 `1.3.0` 修复
