### ISSUE TITLE
Code highlight function

### ISSUE THREAD

**Issue by walsvid** [viosey/hexo-theme-material#12]
在markdown中添加了代码块，也标注了语言类型，但是并没有高亮语法，这个功能怎么启用，在文档中没找到？

**Comment by viosey** [comment]
代码高亮这个功能因为一些原因还未能实现，
正在开发中

**Comment by ratelgogo** [comment]
markdown的表格样式也有问题

**Comment by viosey** [comment]
@ratelgogo Markdown 表格样式已经修复
