### ISSUE TITLE
Footer SNS use SVG instead of PNG

### ISSUE THREAD

**Issue by AkarinServer** [viosey/hexo-theme-material#120]
- Footer icon 将会改用 svg
- 新增绘制圆形的 footer icon 可供选择。

**Comment by AkarinServer** [comment]
你好，这个问题我们会在下一个版本修复，请耐心等待。

**Comment by viosey** [comment]
嗯，我们打算让 @AkarinServer 做两套 svg footer 图标，分别是 square 和 circle。

**Comment by AkarinServer** [comment]
好的，那有什么帮忙的吗？

**Comment by AkarinServer** [comment]
暂时不用，谢谢你的热心啦~

**Comment by Halyul** [comment]
mdzz...在github上这么玩真的好吗(:３っ　)へ

**Comment by cubesky** [comment]
@AkarinServer Please fix this issue ASAP. Thanks.

**Comment by AkarinServer** [comment]
@cubesky You can you up
