### ISSUE TITLE
关于page的教程有问题

### ISSUE THREAD

**Issue by EYHN** [viosey/hexo-theme-material#130]
[https://material.viosey.com/intro/](https://material.viosey.com/intro/#pages)

![image](https://cloud.githubusercontent.com/assets/13579374/21953859/eb2a894e-da7c-11e6-9217-d4e586b36ea9.png)

正确的格式应该是：

```
pages:
	友情链接: 
              link:  "/links/"
	时间轴归档: 
              link:  "/timeline/"
```

**Comment by AkarinServer** [comment]
很抱歉，这是我们昨天的更新，还没有来得及更改文档，谢谢您的反馈。

**Comment by Halyul** [comment]
这一波坑了无数的人啊

**Comment by AkarinServer** [comment]
你说呢！？连我都被坑了……QwQ

**Comment by neoFelhz** [comment]
文档已经更新，参见 [https://material.viosey.com/intro/#pages](https://material.viosey.com/intro/#pages)
造成的不便深感抱歉。
