### ISSUE TITLE
主页的页面按钮弹出列表链接错误

### ISSUE THREAD

**Issue by to2false** [viosey/hexo-theme-material#132]
https://github.com/viosey/hexo-theme-material/blob/master/layout/_partial/blog_info.ejs#L29
```
theme.pages[i]
```
改为
```
theme.pages[i].link
```
感谢作者的主题，第一次使用

**Comment by Halyul** [comment]
既然你都写出解决方案了，为何不自己PR呢。。

**Comment by neoFelhz** [comment]
Thx,we will fix it soon.

**Comment by viosey** [comment]
#133 
thanks for your contribution, if you find bugs, you can PR by yourself

**Comment by to2false** [comment]
@viosey 😅
