### ISSUE TITLE
home page search input style problem on Safari

### ISSUE THREAD

**Issue by to2false** [viosey/hexo-theme-material#134]
Use in MacOS safari encounter style issue
![wechatimg2](https://cloud.githubusercontent.com/assets/21302817/21959738/f482b86a-db0b-11e6-988a-c4823979238b.jpeg)

**Comment by viosey** [comment]
what kind of the search method you use?
if `swiftype` may lead to the this problem, and `google` & `local` I think they are find.

**Comment by to2false** [comment]
@viosey the current value is `google`, and `local` can't load page

**Comment by cubesky** [comment]
@to2false if you want to use local , you need to install hexo-generator-search.
For more details, [see here](https://material.viosey.com/en/services/)

**Comment by to2false** [comment]
@cubesky thanks for tips, it works and then find the pop window position downward a little.
![wechatimg3](https://cloud.githubusercontent.com/assets/21302817/21959925/b0a64dd6-db11-11e6-9d02-f2e808e74e18.jpeg)

**Comment by to2false** [comment]
@viosey @cubesky the style issues only encountered in safari

**Comment by neoFelhz** [comment]
Well. which version of Safari are you using?

**Comment by to2false** [comment]
Safari version: 10.0.2

**Comment by viosey** [comment]
It's a troublesome bug.
At now design, it's no possible to be fixed, unless we change display of search result.
