### ISSUE TITLE
建议代码块的宽度和整个页面相等

### ISSUE THREAD

**Issue by weaponxxx** [viosey/hexo-theme-material#136]
建议代码块的宽度和整个页面相等，否则一小块看着比较难看，如图
![](http://i.imgur.com/uKY6KGK.png)

**Comment by neoFelhz** [comment]
这个实在取决于你的代码块宽度。
这是我的博客：
[Demo1](https://blog.neofelhz.space/archives/android-captive-portal.html)、[Demo2](https://blog.neofelhz.space/archives/coding-snapdragon-810-down.html)

**Comment by cubesky** [comment]
Fix via #174
