### ISSUE TITLE
请问这个如何配置

### ISSUE THREAD

**Issue by fly7632785** [viosey/hexo-theme-material#156]
![6dab5bd4-2aaa-431f-8db1-8607a2243f59](https://cloud.githubusercontent.com/assets/10276266/22091908/dd8d6200-de34-11e6-80e7-4aa4c27d6202.png)

这里的默认邮件地址怎么修改啊？
还有dropdown里面的icon怎么设置   默认有个email 那其他的呢？

**Comment by Halyul** [comment]
mailto:xxxxxxxx@xxxx.xxx

**Comment by Halyul** [comment]
应该是"mailto:xxxxx@xxxxx.xxx"
icon在这里查询https://material.io/icons/

**Comment by fly7632785** [comment]
thanks very much
