### ISSUE TITLE
你好，还有些小问题请教

### ISSUE THREAD

**Issue by fly7632785** [viosey/hexo-theme-material#157]
首先鼓励一下，确实这个主题太棒了
还有些小问题
1、就是有了评论，详情页里面有，但是外面主页面还是显示 暂无评论 ，
2、详情页里面有个 类似收藏的按钮 ，点击无用，如果可用怎么配置？
![5760e520-a2b4-418e-8f84-605dbf1e8c1f](https://cloud.githubusercontent.com/assets/10276266/22091970/6d9a1226-de35-11e6-9d46-d8275c37d0ba.png)
3、侧边栏里面 主题-material 这一栏是不是必须要存在？
4、分享里面只有固定的几个，可不可以增加 QQ空间等？
5、主界面下这个是什么，怎么配置按钮
![b692538a-11d1-433c-a503-a89be5cbe690](https://cloud.githubusercontent.com/assets/10276266/22092149/884167ea-de36-11e6-9ce1-3d69c6fbe98b.png)

一些小建议：
1、建议要么就不要暂无评论了 ，要么就显示个评论数
2、建议访客数量可不可以拿到主页上来显示

**Comment by Halyul** [comment]
Q1 S1 应该是BUG @viosey
Q2 那个地方放Tag的地方
Q3 您可以自己在代码去去除，但不建议
Q4 或许会加入 如果您自己加入可以提交PR
Q5 自定义页面展示按钮

S2 您可以自己做 我觉得这个需求并不是太多

**Comment by neoFelhz** [comment]
此外，提交 issue 请符合规范。否则将不会予以认真处理。

**Comment by neoFelhz** [comment]
@Halyul 那个是多说的问题，这锅咱们不背。

**Comment by Halyul** [comment]
我没说是咱们的bug啊🙃
