### ISSUE TITLE
关于摘要

### ISSUE THREAD

**Issue by waychane** [viosey/hexo-theme-material#16]
在文章首页显示摘要，能否新增通过 Markdown 的引用标记来自行设定摘要文字的功能，而不是选取特定长度的正文内容显示。

**Comment by viosey** [comment]
摘要有两种输出方式：
- 可以通过自定义特定长度输出
- 可在编写文章是添加 `<!-- more -->` 标签进行控制

**Comment by viosey** [comment]
是否还有其他的问题呢？
