### ISSUE TITLE
issues about color code block highllight

### ISSUE THREAD

**Issue by lzq920** [viosey/hexo-theme-material#161]
目前使用了一天，发现代码块渲染这一部分有问题，使用高亮代码显示的行号跟代码没有对齐。
另外，links页面，如果描述内容太长，会很挫，文字超出范围了。
还有，文章内容页面的图片能否像图库页面一样的效果，不然插入的图片太小的话，会显得很不好看。

ps:希望做得越来越好，小小捐赠一下。啦啦啦啦啦啦啦啦啦啦啦啦啦啦..........

**Comment by viosey** [comment]
对的，高亮会有一些问题，正在修复。

**Comment by AkarinServer** [comment]
@lzq920 捐钱就是大爷！这bug立刻修！妥妥的！没毛病！

**Comment by cubesky** [comment]
@AkarinServer ← 这个是吉祥物

**Comment by cubesky** [comment]
Fixed in `1.3.0`
已在 `1.3.0` 修复
