### ISSUE TITLE
allow me to change images used for blog thumbnails

### ISSUE THREAD

**Issue by theonlygusti** [viosey/hexo-theme-material#164]
I've noticed that the theme tries to get images for articles from urls like `/img/random/material-19.png`.

How do we control where the theme gets thumbnail images from? Or what images get put into these elements

**Comment by theonlygusti** [comment]
@gitmagic-bot thank you for your swift reply,

1. I can't add labels, only owners of the repository can do that.
2. Okay, sorry I'll fix that and make the title lowercase
3. I am asking a question though, how do I make it imperative?

**Comment by viosey** [comment]
[Thumbnail function](https://material.viosey.com/en/compose/#Thumbnail-function)

Is it solve your problem?

**Comment by theonlygusti** [comment]
Yes thank you, that solved it.
