### ISSUE TITLE
bug(toc): toc list can not scroll

### ISSUE THREAD

**Issue by cubesky** [viosey/hexo-theme-material#167]
**I certify that I have first consulted** (check all with "x")

- [x] [Hexo documentation](https://hexo.io/docs/)
- [ ] [Material theme documentation](https://material.viosey.com/)
- [x] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request

When Toc list in the post is too long, the list can not scroll with page. So I can't see the whole list.  
当 Toc 列表很长时，Toc 目录无法完整显示，他也不会跟随浏览器滚动，造成无法显示完全。  
![image](https://cloud.githubusercontent.com/assets/8038511/22175973/3ddbad12-e03b-11e6-846c-a204fcf18e1e.png)
上图中 Toc 列表下方依然有未显示完的内容  
[Post with bug/含有bug的页面](https://liyin.date/2017/01/21/Minecraft-with-Docker/)

**Comment by theonlygusti** [comment]
Also the share menu cannot scroll when the post is too short.

**Comment by cubesky** [comment]
fix via #266
