### ISSUE TITLE
disable browser search suggestions

### ISSUE THREAD

**Issue by theonlygusti** [viosey/hexo-theme-material#168]
The search box is obscured by (at least Google Chrome) the browser's own search suggestions:

![http://i.cubeupload.com/f8PsIi.png](http://i.cubeupload.com/f8PsIi.png)

Simply using the HTML attribute `autocomplete="off"` should stop this.

**Comment by pidupuis** [comment]
Fixed in #170

**Comment by theonlygusti** [comment]
@pidupuis any idea on how long it'll take for the patch to be distributed?

**Comment by pidupuis** [comment]
@theonlygusti probably tomorrow
