### ISSUE TITLE
希望添加GoogleAnalytics

### ISSUE THREAD

**Issue by lslvxy** [viosey/hexo-theme-material#17]
希望添加GoogleAnalytics

**Comment by yhyy135** [comment]
按照 [进阶设定](https://material.vss.im/settings/) 将 GoogleAnalytics 的跟踪代码 [添加自定义代码](https://material.vss.im/settings/#add-custom-code) 就可以了

**Comment by lslvxy** [comment]
已经添加上了，刚yml配置写错了一直解析不了
