### ISSUE TITLE
stop local search linking to double url

### ISSUE THREAD

**Issue by theonlygusti** [viosey/hexo-theme-material#179]
I created [an issue](https://github.com/PaicHyperionDev/hexo-generator-search/issues/15) in hexo-generator-search's repository about this, but from what I've been told by them it is more to do with the theme and config files.

So, my blog is on a `/blog` path.

Normal pages are on `/blog/2017/01/21/post/`.

However, when using the search it tries to link to `/blog/blog/2017/01/21/post`, which doesn't work because no page exists there.

You can see my blog [here](http://theonlygusti.github.io/blog/), try using the search box.

**Comment by pidupuis** [comment]
Could you show us your `search.xml` file?

**Comment by pidupuis** [comment]
We don't have any custom parameter to generate the `search.xml` file.
I found this [file](https://github.com/theonlygusti/blog/blob/61a1fd94dd71921931204b1516887a5bbfde4150/search.xml) which should be yours I think.

This file is generated by the `hexo-generator-search` plugin. As you can see in this file, the url are already broken. This seems to be a problem from their plugin, not ours.

**Comment by theonlygusti** [comment]
@pidupuis thank you. This does indeed seem to be the case, and I'll go back to the other plugin.

Also, thanks for all the effort you put into responding to issues! Really awesome :)
