### ISSUE TITLE
问下page.id配置问题

### ISSUE THREAD

**Issue by lslvxy** [viosey/hexo-theme-material#18]
多说 data-thread-key="<%= page.id %>"但是获取到的page。id是undefined

**Comment by w4lle** [comment]
这个问题你是怎么配置的呢？

**Comment by lslvxy** [comment]
在post文章头部加上id

```
title: Redux教程3：添加倒计时
date: 2016-11-14 14:30
comments: on
category: Web
tags: [React,Redux,Web]
id: 201611141430
---
```

**Comment by lslvxy** [comment]
每篇文章加一个唯一的id，或者修改主题的代码`themes/material/layout/_widget/duoshuo.ejs`把page.id修改为 url_for(path),将文章的url作为data-thread-key也可以，文章量不多的话推荐添加id

**Comment by viosey** [comment]
1.1.1版本 会将 url_for(path) 作为默认 thread key。
: )

**Comment by lslvxy** [comment]
我刚刚把所有的id都加上了。。。/(ㄒoㄒ)/~~这个key修改的话以前的评论就都没了，需要在多说后台把文章的key对应再修改为url

**Comment by viosey** [comment]
没事的，会提供两种方式。
默认为 URL，可选为 ID。
因为我自己也是用 ID (^・^)

**Comment by lslvxy** [comment]
顶~\(≧▽≦)/~
