### ISSUE TITLE
多说插件的HTTPS好像有问题

### ISSUE THREAD

**Issue by CaptainTF** [viosey/hexo-theme-material#184]
**I certify that I have first consulted** (check all with "x")

- [ ] [Hexo documentation](https://hexo.io/docs/)
- [ ] [Material theme documentation](https://material.viosey.com/)
- [X] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [ ] bug report
- [ ] feature request
- [X] support request

**Comment by viosey** [comment]
这个是因为多说不支持 https，和主题无关，建议使用 disqus
