### ISSUE TITLE
chrome翻译总是跳出翻译，修改html的lang属性可以解决这个问题。

### ISSUE THREAD

**Issue by EYHN** [viosey/hexo-theme-material#188]
**I certify that I have first consulted** (check all with "x")

- [x] [Hexo documentation](https://hexo.io/docs/)
- [x] [Material theme documentation](https://material.viosey.com/)
- [x] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [ ] bug report
- [x] feature request
- [ ] support request

## Change the "layout.ejs"

```
<html lang="<%- config.language.substring(0,2) %>">
```

chrome翻译总是跳出翻译，修改html的lang属性可以解决这个问题。

**Comment by pidupuis** [comment]
Hi, you could create a PR for this. We'd be pleased to merge it :)
