### ISSUE TITLE
汉堡菜单三条横向间距不同

### ISSUE THREAD

**Issue by Stark2Chen** [viosey/hexo-theme-material#192]
**I certify that I have first consulted** (check all with "x")

- [ ] [Hexo documentation](https://hexo.io/docs/)
- [ ] [Material theme documentation](https://material.viosey.com/)
- [x] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request

汉堡菜单三条横向间距不同

![QQ图片20170204195529.png](https://ooo.0o0.ooo/2017/02/04/5895c14bb4050.png)

**Comment by neoFelhz** [comment]
应该是你的浏览器问题。能不能报一下你的浏览器和设备的有关信息？
还有，请测试一下我的博客 https://blog.neofelhz.space 看一下这个情况会不会复现。
