### ISSUE TITLE
email

### ISSUE THREAD

**Issue by HaojunYinGeek** [viosey/hexo-theme-material#194]
**I certify that I have first consulted** (check all with "x")

- [ ] [Hexo documentation](https://hexo.io/docs/)
- [ ] [Material theme documentation](https://material.viosey.com/)
- [ ] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [ ] bug report
- [ ] feature request
- [ ] support request

i set the email in theme's _config.yml, but it cannot send email! what can i do ?

**Comment by cubesky** [comment]
@HaojunYinGeek You should use mailto:user@yourdomain in dropdown menu setting. If you do this, default email program will startup.
