### ISSUE TITLE
qrcode

### ISSUE THREAD

**Issue by HaojunYinGeek** [viosey/hexo-theme-material#195]
**I certify that I have first consulted** (check all with "x")

- [ ] [Hexo documentation](https://hexo.io/docs/)
- [ ] [Material theme documentation](https://material.viosey.com/)
- [x] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request

it can show qrcode, but the url domain is "yoursite.com"

**Comment by cubesky** [comment]
Please edit your domain in _config.yml in your blog root folder.
