### ISSUE TITLE
the responsive layout doesn't work well in some mobile phone's browser

### ISSUE THREAD

**Issue by esdream** [viosey/hexo-theme-material#196]
**I certify that I have first consulted** (check all with "x")

- [x] [Hexo documentation](https://hexo.io/docs/)
- [x] [Material theme documentation](https://material.viosey.com/)
- [x] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request

The responsive layout doesn't work in some mobile phone's browser, such as huawei mobile phone's built-in browser. However, it work well in the chrome. 
### huawei built-in browser
![huawei built-in browser](https://cloud.githubusercontent.com/assets/14349603/22737543/8789dc34-ee3e-11e6-88ec-6b32c6f0a507.png)
---
### chrome
![chrome](https://cloud.githubusercontent.com/assets/14349603/22737530/7c6086c8-ee3e-11e6-9d4a-2a95db9eca43.png)

**Comment by neoFelhz** [comment]
It was caused by Huawei EMUI built in Browser. If you are using chrome on mobile or other Browser you can avoid this. Sorry, but we won't support Huawei EMUI as well as its Browser.
