### ISSUE TITLE
希望添加打赏的功能

### ISSUE THREAD

**Issue by yinhaojun** [viosey/hexo-theme-material#197]
**I certify that I have first consulted** (check all with "x")

- [ ] [Hexo documentation](https://hexo.io/docs/)
- [ ] [Material theme documentation](https://material.viosey.com/)
- [ ] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [ ] bug report
- [x] feature request
- [ ] support request

the theme is very good, i like it very much!   能不能添加打赏的功能呢？like theme “nextT”

**Comment by cubesky** [comment]
@yinhaojun 你可以自己定义打赏功能，我们不在主题中提供该功能，谢谢您的支持

**Comment by neoFelhz** [comment]
这是一个在 Github 上开源的捐赠页面实例——[donate-page](https://github.com/Kaiyuan/donate-page)
你可以参考一下这个的方案。Hexo 的独立页面是支持 HTML 的。
