### ISSUE TITLE
手机使用这个主题的一些问题

### ISSUE THREAD

**Issue by imitsuha** [viosey/hexo-theme-material#201]
手机使用Termux安装的hexo
这个主题其他正常
但是貌似links没有用
每次deploy之后links页面只有footer

**Comment by imitsuha** [comment]
电脑试了一下，
也是这个问题。。。

**Comment by cubesky** [comment]
@imitsuha 请查看 https://material.viosey.com/compose/ 创建友情链接页面-添加数据
