### ISSUE TITLE
Failed to display dropdown menus such as sns sharing and tags

### ISSUE THREAD

**Issue by nathanielove** [viosey/hexo-theme-material#203]
**I certify that I have first consulted** (check all with "x")

- [ ] [Hexo documentation](https://hexo.io/docs/)
- [ ] [Material theme documentation](https://material.viosey.com/)
- [x] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request

I don't know why the dropdown menus don't work at all. 

![screen shot 2017-02-14 at 5 52 12 pm](https://cloud.githubusercontent.com/assets/6271237/22924170/1dae227a-f2df-11e6-987e-e698c19bf8f3.png)

When I inspect elements, it looks like all the necessary `<li>` tags are there indeed. I also did some manual comparison between this code here and the ones behind your official blog, where all the dropdown menus work perfectly, and I found no difference. 

![screen shot 2017-02-14 at 5 52 35 pm](https://cloud.githubusercontent.com/assets/6271237/22924232/500b18fe-f2df-11e6-8faa-77dd2e3ca173.png)

Thank you in advance!

**Comment by nathanielove** [comment]
OK this only happened on the local development server `hexo server`.

On the real server, everything is fine.

**Comment by neoFelhz** [comment]
In fact, the share and tags menu should be work on local the same as real server. Perhaps It because there are something wrong with your hexo environment on your local device. I think you may reinstall the hexo and the theme, and then have a test again, hopefully everything will be fine.

**Comment by viosey** [comment]
Thanks for your donation~ If you have any problem, welcome to ask me.

**Comment by nathanielove** [comment]
Hi @viosey !

Yesterday when I deployed my site to the Apache server, the sns sharing dropdown menu worked, but before that, I couldn't get it to work on my local development server. Today after I published a few updates, it suddenly stopped working on the server. 

However, when I open it using Chrome browser on my iPhone, the dropdown menu works. It also works in Safari on my Mac. It seems like the problem only occurs when I'm using Chrome on my Mac. 

Can I probably get some clue on what might have gone wrong? I'll be willing to provide more information if necessary.

Thank you in advance!

Nathaniel

**Comment by viosey** [comment]
Could  you post your site's url?

**Comment by nathanielove** [comment]
Hi!!!!! OMG I finally found out why.

The CSS for the social sharing dropdown menu is removed by AdBlock Plus, a Chrome extension. 

After I disable AdBlock Plus for my site, everything works perfectly.

Similarly, the social sharing icons at the bottom left of each page are also blocked by AdBlock Plus by default. 

However, what looks really weird to me is, there's actually no error message in the Chrome developer console when such resources are blocked. Usually, where something is blocked by AdBlock Plus, such as `analytics.js`, there's usually an error message in the console, like this,

```
GET https://www.google-analytics.com/analytics.js net::ERR_BLOCKED_BY_CLIENT
```
 
In my case, I don't see any message like the one above related to the blocked social sharing CSS/JS or whatever.

**Comment by pidupuis** [comment]
That's good to know, thanks for the investigation.

Errors are displayed only when a script is blocked but in this specific case, this is simply a DOM element which is hidden. This does not trigger any error because hiding DOM element is important for some UI/UX like tabs, pagination etc... So I think it is a standard behavior. We could add it to the documentation to prevent further frustration from our users ^^
