### ISSUE TITLE
主题的文档里的compose页面 关于友链的错误

### ISSUE THREAD

**Issue by imitsuha** [viosey/hexo-theme-material#204]
文档地址：https://material.viosey.com/compose/
这是原代码index.md
```
---
title: links
date:
layout: links
---
```
应将date改为data
```
---
title: links
data:
layout: links
---
```
而_date文件夹也应改为_data

**Comment by imitsuha** [comment]
╰(￣▽￣)╭

**Comment by cubesky** [comment]
![image](https://cloud.githubusercontent.com/assets/8038511/22965751/feb0b0d4-f399-11e6-9ed6-ef35707e0b07.png)
这里确实应该是 `date` ，这是标准 `front-matter` 的时间部分
另外没有发现写成 `_date`  的地方
