### ISSUE TITLE
Hey 有神秘阿拉伯语的出现

### ISSUE THREAD

**Issue by ShurongWang** [viosey/hexo-theme-material#208]
**I certify that I have first consulted** (check all with "x")

- [ ] [Hexo documentation](https://hexo.io/docs/)
- [ ] [Material theme documentation](https://material.viosey.com/)
- [ ] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [ ] bug report
- [ ] feature request
- [x] support request

**Comment by ShurongWang** [comment]
我非常喜欢你的 Material design Theme，但是唯一的美中不足就是其中的文字是阿拉伯文（不知道为什么）

**Comment by ShurongWang** [comment]
![image](https://cloud.githubusercontent.com/assets/22816399/23089564/c304aebc-f558-11e6-96d6-0eac8335bdd6.png)

**Comment by ShurongWang** [comment]
![image](https://cloud.githubusercontent.com/assets/22816399/23089568/cca9fa3a-f558-11e6-8401-2049e4dbcbed.png)

**Comment by ShurongWang** [comment]
可以帮我解决一下，谢谢！

**Comment by neoFelhz** [comment]
Plz check your i18n setting.
If the config file is right(was set as zh-CN), then tell us where the strange Arab language is.

**Comment by ShurongWang** [comment]
:) 怪我智障！被我写成了 ch-CN
