### ISSUE TITLE
C++代码显示有问题

### ISSUE THREAD

**Issue by XiaoFanHenNuLi** [viosey/hexo-theme-material#209]
希望作者您能给出解决方法！一是颜色问题，二是#include 与 using namespace std会重叠在一起

**Comment by cubesky** [comment]
@XiaoFanHenNuLi 我们在将要发布的 1.3.0 版本中使用 hexo-prism-plugin 来解决染色问题，1.3.0 版本将在近日发布。

**Comment by cubesky** [comment]
Fixed in `1.3.0`
已在 `1.3.0` 修复
