### ISSUE TITLE
网站为二级目录时，本地搜索功能显示结果的路径不对！

### ISSUE THREAD

**Issue by Cn-Rice** [viosey/hexo-theme-material#210]
例如网站为https://github.com/viosey，添加本地搜索后，搜索结果会变成

`https://github.com/viosey/viosey/xxxxx` 多了一个/viosey

请问如何解决？

**Comment by AkarinServer** [comment]
请问一下使用的场景是什么呢……因为在这边测试的时候发现了新的问题……

**Comment by AkarinServer** [comment]
嗯……或许你可以试一下执行一下 npm update

**Comment by neoFelhz** [comment]
请检查 `站点配置文件` 中关于站点目录和搜索插件有关的配置。请确保你完全掌握绝对地址和相对地址的差别后配置你的 `站点配置文件`。
