### ISSUE TITLE
代码高亮无效果

### ISSUE THREAD

**Issue by arronf2e** [viosey/hexo-theme-material#211]
**I certify that I have first consulted** (check all with "x")

- [ ] [Hexo documentation](https://hexo.io/docs/)
- [ ] [Material theme documentation](https://material.viosey.com/)
- [ ] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request

**Comment by cubesky** [comment]
请稍等，我们正在为 1.3.0 版本的发布做最后的准备，代码染色问题已经在该版本中解决。

**Comment by arronf2e** [comment]
@cubesky OK

**Comment by cubesky** [comment]
Fixed in `1.3.0`
已在 `1.3.0` 修复
