### ISSUE TITLE
能否增加顶栏

### ISSUE THREAD

**Issue by WatsonHS** [viosey/hexo-theme-material#215]
**I certify that I have first consulted** (check all with "x")

- [x] [Hexo documentation](https://hexo.io/docs/)
- [x] [Material theme documentation](https://material.viosey.com/)
- [x] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [ ] bug report
- [x] feature request
- [ ] support request

能否增加一个顶栏？现在博客的汉堡菜单键在移动设备上有时不太明显，并且博客的title也很不明显。

**Comment by viosey** [comment]
Nexus Scheme 将使用顶栏设计但 Paradox 不会添加顶栏设计
