### ISSUE TITLE
Gallery在手机上不是很和谐

### ISSUE THREAD

**Issue by wzcv** [viosey/hexo-theme-material#219]
**I certify that I have first consulted** (check all with "x")

- [x] [Hexo documentation](https://hexo.io/docs/)
- [x] [Material theme documentation](https://material.viosey.com/)
- [x] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request

Gallery在手机上有重叠，希望改进

**Comment by neoFelhz** [comment]
I've no issue when visit my own gallery page.It must be your own problem and we won't make any changes unless there are some certain bugs.
