### ISSUE TITLE
多说迁移

### ISSUE THREAD

**Issue by w4lle** [viosey/hexo-theme-material#22]
集成多说要步骤
```
使用多说需要在 front-matter 中添加

id: id_number
如果是从其他博客系统迁移过来，id 需要和多说后台的 Thread_Key 保持一致。
```
每篇文章都要去添加一个id？这样也太麻烦了吧。
还有Thread_Key是哪里来的。
之前用的NexT主题，配置多说很方便啊。

**Comment by viosey** [comment]
现在多说支持自动获取 title
文档较久，还没更新

**Comment by w4lle** [comment]
```
<div id="comments">
    <!-- 多说评论框 start -->
        <div class="ds-thread" data-thread-key="<% if(theme.comment.duoshuo_thread_key == "id"){ %><%= page.id %><% } else { %><%= page.title %><% } %>" data-url="<%= config.url+ config.root + url_for(path) %>"></div>
    <!-- 多说评论框 end -->
</div>
```
那么现在还需要什么配置吗？
@viosey

**Comment by w4lle** [comment]
![image](https://cloud.githubusercontent.com/assets/7310246/20373204/9d5bbe9e-acab-11e6-9e16-3b666d217378.png)
``data-thread-key="Hexo主题同步"``
而我的多说后台的 thread-key 是这个 ``2016/06/06/Hexo-themes/``
我应该怎么修改呢？

**Comment by viosey** [comment]
大概知道了 Next 主题获取的对象和 Material 主题不一样，我改一下，没问题的话会在 1.1.1版本更新。

**Comment by w4lle** [comment]
我改了下
```
data-thread-key="<% if(theme.comment.duoshuo_thread_key == "id"){ %><%= page.id %><% } else { %><%= page.path %><% } %>"
```
改为``page.path``就ok了。

**Comment by w4lle** [comment]
现在还有个问题，就是同步到多说以后，多说的title没有文章标题，以前用Next是有的。
如下图
![image](https://cloud.githubusercontent.com/assets/7310246/20389610/7058291e-ad05-11e6-8e35-039d16506fcb.png)

**Comment by viosey** [comment]
试试看 1.1.1 版本的。添加了 data-title 的数据，应该是没问题了。
BTW，之前的版本有可能你哪里没有设置好，因为我的多说之前仍会显示标题。

**Comment by viosey** [comment]
先把问题关闭了，你试一试看看
