### ISSUE TITLE
关于多说的未定义duoshuoQuery

### ISSUE THREAD

**Issue by newPdx** [viosey/hexo-theme-material#224]
<% if(theme.comment.use === 'duoshuo') { %>
    
    <script type="text/javascript">
       var queue.offer(function(){                   ====>  去掉var,这里变成私有变量了
            duoshuoQuery = {
                short_name: '<%= theme.comment.shortname %>'
            };
            console.log(duoshuoQuery);
            (function() {
                var ds = document.createElement('script');
                ds.type = 'text/javascript';
                ds.async = true;
                ds.src = '<%= theme.comment.duoshuo_embed_js_url %>';
                ds.charset = 'UTF-8';
                (document.getElementsByTagName('head')[0]
                 || document.getElementsByTagName('body')[0]).appendChild(ds);
            })();
        });
    </script>
    
<% } %>

**Comment by endday** [comment]
我还以为只有我是这样啊，原来如此，这样娶不到duoshuoQuery

**Comment by cubesky** [comment]
我们会尽快修正这个问题

**Comment by Troland** [comment]
把那个footer-option.ejs里面的`var duoshuoQuery`改为`window.duoshuoQuery`就可以了.

**Comment by neoFelhz** [comment]
Would you mind to create a PR to change this? It would be really appreciated :)

**Comment by neoFelhz** [comment]
多说已经停止服务，Material 主题从下个版本开始停止对多说的支持。
