### ISSUE TITLE
请问多tag的编写格式是怎样的。

### ISSUE THREAD

**Issue by wanghaonanlpc** [viosey/hexo-theme-material#225]
**I certify that I have first consulted** (check all with "x")

- [ ] [Hexo documentation](https://hexo.io/docs/)
- [ ] [Material theme documentation](https://material.viosey.com/)
- [ ] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [ ] bug report
- [x] feature request
- [ ] support request

**Comment by wanghaonanlpc** [comment]
如题

**Comment by cubesky** [comment]
请参见 hexo 帮助文档 https://hexo.io/zh-cn/docs/front-matter.html
