### ISSUE TITLE
cant display page

### ISSUE THREAD

**Issue by AdhanIsCuber** [viosey/hexo-theme-material#226]
`Unhandled rejection TypeError: /home/adhaniscuber/project/blog/themes/material/layout/layout.ejs:2`
    `1| <!DOCTYPE html>`
` >> 2| <html lang="<%- config.language.substring(0,2) %>">`
    `3|     <%- partial('_partial/head') %>`
    `4| `
    `5|     <% if(page.layout === 'gallery') { %>`

`Cannot read property 'substring' of null`
`    at eval (eval at <anonymous> (/home/adhaniscuber/project/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:79)`
`   at eval (eval at <anonymous> (/home/adhaniscuber/project/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2346)`
`    at /home/adhaniscuber/project/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15`
`    at _compiled (/home/adhaniscuber/project/blog/node_modules/hexo/lib/theme/view.js:127:30)`
`    at View.render (/home/adhaniscuber/project/blog/node_modules/hexo/lib/theme/view.js:29:15)`
`    at /home/adhaniscuber/project/blog/node_modules/hexo/lib/theme/view.js:40:23`
`    at tryCatcher (/home/adhaniscuber/project/blog/node_modules/bluebird/js/release/util.js:16:23)`
`    at Promise._settlePromiseFromHandler (/home/adhaniscuber/project/blog/node_modules/bluebird/js/release/promise.js:510:31)`
`    at Promise._settlePromise (/home/adhaniscuber/project/blog/node_modules/bluebird/js/release/promise.js:567:18)`
`    at Promise._settlePromise0 (/home/adhaniscuber/project/blog/node_modules/bluebird/js/release/promise.js:612:10)`
`    at Promise._settlePromises (/home/adhaniscuber/project/blog/node_modules/bluebird/js/release/promise.js:691:18)`
`    at Async._drainQueue (/home/adhaniscuber/project/blog/node_modules/bluebird/js/release/async.js:133:16)`
`    at Async._drainQueues (/home/adhaniscuber/project/blog/node_modules/bluebird/js/release/async.js:143:10)`
`    at Immediate.Async.drainQueues (/home/adhaniscuber/project/blog/node_modules/bluebird/js/release/async.js:17:14)`
`    at runCallback (timers.js:637:20)`
`    at tryOnImmediate (timers.js:610:5)`
`    at processImmediate [as _immediateCallback] (timers.js:582:5)`

**Comment by AkarinServer** [comment]
@AdhanIsCuber Please make sure your lang config is set correctly.

**Comment by neoFelhz** [comment]
Plz check your configuration of your language.
