### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by FailScholar** [viosey/hexo-theme-material#228]
![2](https://ooo.0o0.ooo/2017/03/03/58b8c7135add1.png)
![1](https://ooo.0o0.ooo/2017/03/03/58b8c7135a12f.png)

- 在iphone5s,iphone5c上的显示问题，如上图所示
- 在chrome上用手机调试看没有问题

**Comment by AkarinServer** [comment]
@FailScholar 很抱歉本主题的开发人员似乎并没有iPhone……

**Comment by cubesky** [comment]
请尝试
https://itunes.apple.com/ca/app/chrome-web-browser-by-google/id535886823?mt=8

**Comment by FailScholar** [comment]
是因为我的safari浏览器版本太低了

**Comment by neoFelhz** [comment]
@cubesky 我们接下来可能除了封杀 UC、IE8 以外，我们可能还要继续封杀所有低版本的、和国内某些无需点名的浏览器。

**Comment by cubesky** [comment]
@neoFelhz 好！

**Comment by AkarinServer** [comment]
某些的话。。。至少留一个QQ的吧。。。人家好歹是Chrome55。。。封杀说不过去呀。。。QAQ

**Comment by FailScholar** [comment]
@neoFelhz 问下这个主题最低支持的Safari版本是多少？因为在手机分享之后，低版本的浏览器打开都有显示的问题
