### ISSUE TITLE
the exception when user doesn't set language

### ISSUE THREAD

**Issue by JarvisJin** [viosey/hexo-theme-material#229]
预判一下language属性给个默认值更好一点。

INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: C:\Users\xuanlu\masking\BlogByHexo\themes\material\layout\layout.ejs:2
    1| &lt;!DOCTYPE html&gt;
    2| &lt;html lang="&lt;%- config.language.substring(0,2) %&gt;"&gt;
    3|     &lt;%- partial('_partial/head') %&gt
    4|
    5|     &lt;% if(page.layout === 'gallery') { %&gt

Cannot read property 'substring' of null
    at eval (eval at <anonymous> (C:\Users\xuanlu\masking\BlogByHexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:79)
    at eval (eval at <anonymous> (C:\Users\xuanlu\masking\BlogByHexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:2346)

**Comment by AkarinServer** [comment]
@JarvisJin Please make sure your lang config is set correctly.

**Comment by AkarinServer** [comment]
@JarvisJin Please check your config in _config.yml

**Comment by JarvisJin** [comment]
预判一下language属性给个默认值更好一点。还有比较多的地方使用属性的时候没预先判断是否为空

**Comment by cubesky** [comment]
@JarvisJin 这是你的设置问题 我们希望用户可以在阅读 Hexo 官方帮助 与 Material 帮助文档 和 已解决的issues 后不能解决时再开启 issue。也许我们应该将 issue 创建模板加入中文提示
