### ISSUE TITLE
Could't show pages in Isolation scheme?

### ISSUE THREAD

**Issue by Troland** [viosey/hexo-theme-material#232]
**I certify that I have first consulted** (check all with "x")

- [x] [Hexo documentation](https://hexo.io/docs/)
- [ ] [Material theme documentation](https://material.viosey.com/)
- [x] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request

It's very weired that the settings pages could't show after switching to Isolation scheme.My hexo-theme-material version is `1.3.0`.

I open the webdev panel of chrome, there is a javascript error appeared,maybe that's the problem?
Any ideas?

**Comment by AkarinServer** [comment]
Setting pages? Which one do you mean? Through we are foucing on paradox now, however when I test it with just switching the scheme name without other changes, it works well... Can you provide some images for us to check the problem? Thanks.

**Comment by neoFelhz** [comment]
@AkarinServer I think it maybe something wrong in Archive page.

**Comment by neoFelhz** [comment]
#271

**Comment by neoFelhz** [comment]
Fixed in 1.3.4.

**Comment by yifan2223** [comment]
Isolation theme: can not loading article, I don't know what's wrong.
![Screen Shot 2019-04-09 at 10 36 58 AM](https://user-images.githubusercontent.com/25877635/55769507-a4150e80-5ab3-11e9-88ac-84037ca4eca9.png)
![Screen Shot 2019-04-09 at 10 36 58 AM](https://user-images.githubusercontent.com/25877635/55769511-ab3c1c80-5ab3-11e9-9d5d-614a963b96cd.png)
