### ISSUE TITLE
duoshuo评论显示不了

### ISSUE THREAD

**Issue by yinhaojun** [viosey/hexo-theme-material#233]
**I certify that I have first consulted** (check all with "x")

- [ ] [Hexo documentation](https://hexo.io/docs/)
- [ ] [Material theme documentation](https://material.viosey.com/)
- [ ] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request

我在comment中添加多说评论，配置了use和shortname，但是评论显示不出来，duoshuo_thread_key_type和duoshuo_embed_js_url需要进行其他的设置吗？。还有就是我用disqus的时候，总是加载不了评论，出现reload，点击也没有效果。

**Comment by neoFelhz** [comment]
多说：你需要额外配置 `duoshuo_thread_key`，`duoshuo_embed_js_url` 如无必要可以用默认的。详情可阅读多说后台的文档。
Disqus： Disqus 评论系统不能跨域调用。
如果还有其它关于 comment 的问题，可以 reopen 这个 issue。

**Comment by SkylineVagrancy** [comment]
我也配置了use和shortname，但是评论显示不出来。
comment:
    use: "duoshuo"
    shortname:  "zjppzh"
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"

**Comment by cubesky** [comment]
这是一个已知的bug 我们将在下个版本解决这个问题
