### ISSUE TITLE
prism问题

### ISSUE THREAD

**Issue by yinhaojun** [viosey/hexo-theme-material#234]
**I certify that I have first consulted** (check all with "x")

- [ ] [Hexo documentation](https://hexo.io/docs/)
- [ ] [Material theme documentation](https://material.viosey.com/)
- [ ] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [ ] bug report
- [ ] feature request
- [ ] support request

当我引用prism后，hexo g产生了问题：
```
INFO  Start processing
INFO  Files loaded in 671 ms
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'E:\blog\HaojunYinGeek.github.io\
node_modules\prismjs\themes\prism-realtime.css'
    at Error (native)
```

**Comment by AkarinServer** [comment]
@yinhaojun This is an error on prismjs. Please open issue on prismjs project

**Comment by neoFelhz** [comment]
Reinstall the `hexo-prism-plugin` then the issue will be solved. I have the same problem on my CI.
