### ISSUE TITLE
更改css只能在style.min.css里改吗

### ISSUE THREAD

**Issue by Jeffrey95** [viosey/hexo-theme-material#236]
- [ ] [Hexo documentation](https://hexo.io/docs/)
- [x] [Material theme documentation](https://material.viosey.com/)
- [x] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [ ] bug report
- [ ] feature request
- [x] support request

想要更改一下css，发现更改style.css并不生效。使用chrome开发者工具查看，引用的是style.min.css。
想要问一下：
1.要更改的话只能更改style.min.css吗？（style.min.css并没有格式化，改起来不是很方便）。2.style.min.css是style.css生成的吗？我看了下主题根目录下有一个`lint.sh`的文件，貌似是使用这个来生成的。如果我想要更改style.css来生成style.min.css，还需要npm额外安装别的模块来手动生成吗？

**Comment by Halyul** [comment]
Q1: 是的，你需要在编辑器里面将文件格式化。在线的话有[tool.lu](http://tool.lu/)
Q2: 暂不清楚

**Comment by neoFelhz** [comment]
1. 大部分的 css 和 js 我们都开源了未压缩的版本。只是不在生产环境使用
2. 是的
3. 对于大部分需要自定义修改的，我们大部分都做了自定义，比如颜色、图片、字体等。参见 `config_css.ejs`
