### ISSUE TITLE
主题介绍，关于pages部分中英文不一致的问题

### ISSUE THREAD

**Issue by tianma8023** [viosey/hexo-theme-material#237]
**I certify that I have first consulted** (check all with "x")

- [ ] [Hexo documentation](https://hexo.io/docs/)
- [x] [Material theme documentation](https://material.viosey.com/)
- [ ] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request

[pages introduction](https://material.viosey.com/en/intro/#pages)
![intro-en](https://cloud.githubusercontent.com/assets/7833704/23840921/3a861db6-07e4-11e7-969c-efb294e0424e.png)
[中文版pages介绍](https://material.viosey.com/intro/#pages)
![intro-zh](https://cloud.githubusercontent.com/assets/7833704/23840922/3f041a3c-07e4-11e7-9352-39c3e65287e0.png)
明显，中文版的pages示例缩进有问题。

**Comment by neoFelhz** [comment]
![Screenshot_20170313-182404.png](https://ooo.0o0.ooo/2017/03/13/58c67364ea8a5.png)
![Screenshot_20170313-182342.png](https://ooo.0o0.ooo/2017/03/13/58c67364ee4bd.png)

It's fine on my smartphone.

**Comment by tianma8023** [comment]
@neoFelhz 啊，我没有表述清楚，手机上确实是OK的，我是在PC上发现这个问题的，IE是OK的，但是Chrome浏览器上会出现这种问题。 =。=
