### ISSUE TITLE
站内搜索

### ISSUE THREAD

**Issue by summersir** [viosey/hexo-theme-material#24]
下载插件后  站点配置也按照要求配置了  但是没生效 是主题配置也要设置吗

**Comment by viosey** [comment]
主题配置是否有切换？
Integrated Services 中需要设置如下
```yml
search:
    use: local
```

**Comment by viosey** [comment]
文档为 1.0.0 版本的，所以还没完善，我会尽快更新文档。
还有什么其他的问题吗？如果没有的话这个 issue 将在 24h 内关闭。

**Comment by summersir** [comment]
暂时没有了 我看好像更新的1.1.0  github上的文件有的都已经更新了  是不是要马上发布新版本了

**Comment by summersir** [comment]
很好用的主题， 如果我的技术可以了，希望可以加入到开发中，现在只能羡慕和继续学习

**Comment by viosey** [comment]
加油(๑•̀ㅂ•́)و✧
