### ISSUE TITLE
 Cannot find module 'D:\blog\node_modules\hexo-material'

### ISSUE THREAD

**Issue by SmileLxy** [viosey/hexo-theme-material#240]
更新了下hexo-material,然后再hexo server时就报错了。明明有这个模块的

**Comment by VIXNESS** [comment]
+1 npm install hexo-material --save 过了，全局也装过了，hexo g就是报错，moudules文件夹里也有这个文件夹

**Comment by SmileLxy** [comment]
再卸载一下就好了 @VIXNESS

**Comment by neoFelhz** [comment]
@SmileLxy @VIXNESS https://material.viosey.com/start/#NPM-1

**Comment by zhounewz** [comment]
怎么解决的？

**Comment by VIXNESS** [comment]
@zhounewz 按照楼上的方法，或者换个操作系统

**Comment by marsbaiyun** [comment]
@zhounewz 使用 @SmileLxy 的方法解决了，npm uninstall --save hexo-material
