### ISSUE TITLE
无法加入多说评论，报错"缺少 duoshuoQuery 的定义"

### ISSUE THREAD

**Issue by weianke** [viosey/hexo-theme-material#241]
comment: 
    use: "duoshuo"
    shortname: weianke
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"

**Comment by mosaice** [comment]
将 `footer-option.ejs` 中的
```
            var.duoshuoQuery = {
                short_name: '<%= theme.comment.shortname %>'
            };
``` 
修改成如下即可
```
            window.duoshuoQuery = {
                short_name: '<%= theme.comment.shortname %>'
            };
```

**Comment by cubesky** [comment]
duplicate #224

**Comment by weianke** [comment]
Have been solved, thank you very much

**Comment by PolluxLee** [comment]
我设置了 use 的值为 "duoshuo" 之后，评论能够正常显示了，但是 footer 跳到 网页的头部去了

**Comment by neoFelhz** [comment]
多说已经停止服务，Material 主题将从下个版本开始去除多说支持。
