### ISSUE TITLE
How to choose thumbnail image i want for my post each one?

### ISSUE THREAD

**Issue by Lutece** [viosey/hexo-theme-material#243]
**I certify that I have first consulted** (check all with "x")

- [ x ] [Hexo documentation](https://hexo.io/docs/)
- [ x ] [Material theme documentation](https://material.viosey.com/)
- [ x ] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [ ] bug report
- [ x ] feature request
- [ ] support request

How to choose image i want for my post each one?
I want to use the random material images also i want to use other images for my post
but i can't find out this direction

please answer me

**Comment by cubesky** [comment]
Please read this https://material.viosey.com/en/compose/
