### ISSUE TITLE
什么时候能加入markdown对数学符号的支持

### ISSUE THREAD

**Issue by PolluxLee** [viosey/hexo-theme-material#244]

**Comment by cubesky** [comment]
Markdown 本身不支持数学符号，请使用 MathJax 或者其他方法实现。

**Comment by neoFelhz** [comment]
@PolluxLee @cubesky 
Material Theme has already built in a Mathjax, but it is still exprimental. You can enable it by set your post's Front-Matter with `mathjax: true`

**Comment by PolluxLee** [comment]
Thank you very much!
