### ISSUE TITLE
1.3.0版本layout报错

### ISSUE THREAD

**Issue by liseen315** [viosey/hexo-theme-material#245]
Unhandled rejection TypeError: /Users/liseen/blog/themes/material/layout/layout.ejs:2
    1| <!DOCTYPE html>
 >> 2| <html lang="<%- config.language.substring(0,2) %>">
    3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>

请问是要复制之前稳定版本的配置文件到1.3.0版本里面用么？

**Comment by AkarinServer** [comment]
1.3.0有较大更改，请按照config.templete重新修改你的配置文件
