### ISSUE TITLE
thumbnail incorrect

### ISSUE THREAD

**Issue by AkarinServer** [viosey/hexo-theme-material#251]
**I certify that I have first consulted** (check all with "x")

- [x] [Hexo documentation](https://hexo.io/docs/)
- [x] [Material theme documentation](https://material.viosey.com/)
- [x] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request

缩略图无法完全显示，即文章题图显示的有问题，
![image](https://cloud.githubusercontent.com/assets/12603846/24321278/897a9520-119c-11e7-9d4a-3248ef70dd51.png)
上面的是出错的样子
![image](https://cloud.githubusercontent.com/assets/12603846/24321281/9a1edbca-119c-11e7-880b-5f3fb042f065.png)
上图是题图原图

**Comment by neoFelhz** [comment]
这个是样式的问题，我们做的是伪适应。
建议缩略图做好专门的留白，大小建议在 1000*700 左右。
