### ISSUE TITLE
disqus 评论好像用不了  请问要怎么设置这个啊  - - 

### ISSUE THREAD

**Issue by LJ149** [viosey/hexo-theme-material#254]
**I certify that I have first consulted** (check all with "x")

- [x] [Hexo documentation](https://hexo.io/docs/)
- [ ] [Material theme documentation](https://material.viosey.com/)
- [ ] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [ ] bug report
- [ ] feature request
- [ ] support request

**Comment by cubesky** [comment]
Please read docs here [https://material.viosey.com/](https://material.viosey.com/)
