### ISSUE TITLE
能否添加畅言或其它多说的替代器

### ISSUE THREAD

**Issue by kiwiflydream** [viosey/hexo-theme-material#255]
多说已经行将关闭，disqus不管是xx前还是xx后感觉都不太好用，与多说类似有下面这几个
[畅言](http://changyan.kuaizhan.com/)
[友言](http://www.uyan.cc/)
[来必力](https://livere.com/)
还有下面这个脑洞项目，把每条留言commit到github上，再也不用担心其它问题了
**[commentit](https://github.com/guilro/commentit)**

**Comment by neoFelhz** [comment]
We will release 1.3.2 this afternoon. In this version, we will add Chang Yan comment support for Material Theme.
Also we won't add more comment system support by dev team, but we're welcome the contributions from users. So we will be very glad if you can add support for the comment system you mentioned and open Pull Request.

**Comment by AkarinServer** [comment]
@kiwiflydream 欢迎自行pr新的评论系统
