### ISSUE TITLE
thumbnail图片地址如何设置

### ISSUE THREAD

**Issue by vinurs** [viosey/hexo-theme-material#258]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [ ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

**Comment by vinurs** [comment]
我在_posts目录下面每个article有一个同名的目录，每个文章的缩略图我都放在这个目录下面，那么这时候我的thumbnail的图片地址该如何设置呢？

**Comment by neoFelhz** [comment]
请阅读主题的文档中关于 Front-Matter 的部分。
https://material-org.viosey.com/compose/#Front-matter

**Comment by vinurs** [comment]
@neoFelhz 我看过了，例如我设置成：img/thumbnail/1.jpg，这个只会在首页有用，一旦点进文章里面去了以后貌似就找不到图片了，就变成了原来设置的随机图片

**Comment by vinurs** [comment]
可否给我一个你们的thumbnail图片地址的例子，要相对路径的
