### ISSUE TITLE
thumbnail地址处理问题

### ISSUE THREAD

**Issue by vinurs** [viosey/hexo-theme-material#259]
Sorry 我很喜欢这个主题，上次发过一个问题，也许是我没有说清楚，我这里重新说一下。
关于文章的thumbnail是通过在文章里面的frontmatter的thumbnail来进行设置了，我搜索了一下主题的源码：
`<% } else { %>`
`        <!-- Custom Thumbnail -->`
`        <div class="post_thumbnail-custom mdl-card__media mdl-color-text--grey-50" style="background-image:url(<%= post.thumbnail %>)">`
`    <% } %>`
这段代码摘抄自Paradox-post_entry.ejs的line 11-14，从代码上看这里应该是直接使用的frontmatter里面的设置，并没有对url做过任何处理；这个会导致，如果我使用的是相对路径，那么在首页里面的thumbnail图片就显示不出来(url是错误的)，但是点击进入到文章里面以后图片就能正常显示。
	我一般写文章的时候会在_posts目录下面建立一个跟文章同名的目录，然后该篇文章相关的图片都会放在这个目录下面，然后引用的时候都是直接相对路径就OK了。
       我也不知道大家是如何处理这个地址问题的？都是放在一个目录里面然后引用绝对路径吗？
       我原来用过一个主题tranquilpeak，这个里面对thumbnail的url做过处理，仅供参考，不知道是否可以将这段代码移进来。链接如下：
https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/scripts/filters/thumbnail_image_url.js

**Comment by StrickerLee** [comment]
你可以自己修改```layout/_partial/Paradox-post_entry.ejs```来JS来替换路径。
参考我自己的fork中对于这个文件的修改：
https://github.com/StrickerLee/hexo-theme-material/commit/e7b0caa7df896e80f275f83c6ed61fd1ddcc26d3
