### ISSUE TITLE
The Java code blocks do not work well

### ISSUE THREAD

**Issue by TonnyL** [viosey/hexo-theme-material#267]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

When I use a Java code block with annotation, it does not render well.
Here is is an example. The code staggered.

![](https://ww4.sinaimg.cn/large/006tNc79gy1fe9wkvmzjjj30gq046mx9.jpg)

version:1.3.2

Hope it could be fixed soon.

**Comment by neoFelhz** [comment]
Are you using `hexo-prism-plugin` to highlight the code?

**Comment by TonnyL** [comment]
No, I just use the default configuration of material theme. Nothing had I changed it.

**Comment by neoFelhz** [comment]
Material Theme can't fit hexo's built in highlight.js well. So we just advice users to use `hexo-prism-plugin` to highlight the code.

https://material.viosey.com/en/expert/#Code-highlight

**Comment by TonnyL** [comment]
Ok, I will have a try. Thx.
