### ISSUE TITLE
建议添加友言评论系统

### ISSUE THREAD

**Issue by Fanx-jk** [viosey/hexo-theme-material#274]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

建议添加友言评论系统

**Comment by neoFelhz** [comment]
https://blog.nfz.moe/archives/add-comment-system-to-hexo.html
你可以自己根据教程添加。
我们也欢迎用户提交 Pull Request。
