### ISSUE TITLE
summary markdown support

### ISSUE THREAD

**Issue by huangjj27** [viosey/hexo-theme-material#278]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

-----------

some hexo theme can use markdown style in posts' summary like this:
![image](https://cloud.githubusercontent.com/assets/8068443/24845717/0bc5e506-1de7-11e7-8561-7d4754a35691.png)

but the material theme doesn't support:
![image](https://cloud.githubusercontent.com/assets/8068443/24845725/21d3b058-1de7-11e7-9931-b6de32f1d1d6.png)

hope to add the support for md in summary

**Comment by neoFelhz** [comment]
Sorry. As we considered, excerpt is used to show post summary instead of content.

**Comment by huangjj27** [comment]
@neoFelhz  I think so, but the message about who could benifit from the post will be more clear when ust a list

**Comment by neoFelhz** [comment]
Yep. But as you can see, the post card has an aspect ratio as the golden ratio. That means we can't add too more content in the card.

**Comment by huangjj27** [comment]
OK, I will think about this and considering change either the summary or the theme.
