### ISSUE TITLE
Lazyload "switch"

### ISSUE THREAD

**Issue by nonnone** [viosey/hexo-theme-material#279]
Can you add an option of **lazyload** in the theme configure file since i don't want to use it?

**Comment by neoFelhz** [comment]
In version 1.3.4, we fix a bug about idie of queue to improve the lazyload.
Here is the demo: https://blog.nfz.moe

**Comment by nonnone** [comment]
When using cloudflare, the lazyload still don't work. (Thumbnails do not display.) 
But when using others, it do work. I don't actually know what makes this error.

**Comment by nonnone** [comment]
I think my ideal solution will be: 
1. The **gallery** always use lazyload.
2. Provide an option to disable **head page** lazyload in **_config.yml**.

**Comment by viosey** [comment]
Sorry, due to the downward compatibility, we decide not to add switch for lazyload.
We consider it should be a attribute instead of a function.
Moreover, lazyload could enhance the performance of site.

**Comment by viosey** [comment]
If you are using CloudFlare, plz turn off the optimize function.

> In addition, Material Theme has special tech to speed up your site, it's useless to use CloudFlare.
