### ISSUE TITLE
文章中添加代码行号与代码不对应

### ISSUE THREAD

**Issue by lslvxy** [viosey/hexo-theme-material#28]
代码中有空行的时候行号和代码对应不上[![图片](http://lise-blog.oss-cn-shanghai.aliyuncs.com/QQ%E6%88%AA%E5%9B%BE20161117125026.png)](http://lise-blog.oss-cn-shanghai.aliyuncs.com/QQ%E6%88%AA%E5%9B%BE20161117125026.png)

**Comment by lslvxy** [comment]
代码是3行，还有两个空行，生成的页面行号就不对了

**Comment by viosey** [comment]
这个 bug 正在解决中
