### ISSUE TITLE
关于自动翻译常见自定义页的建议

### ISSUE THREAD

**Issue by huangjj27** [viosey/hexo-theme-material#280]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

-----------
在设置自定义页(page)的时候, 发现没有办法自动转译成语言, 于是翻找到`layout/_partial/sidebar-navigation.ejs`:

```ejs
      <% for (var i in theme.sidebar.pages){ %>
        <li>
            <a href="<%= theme.sidebar.pages[i].link %>" title="<%= i %>">
                <% if(theme.sidebar.pages[i].icon){ %>
                    <i class="material-icons sidebar-material-icons"><%= theme.sidebar.pages[i].icon %></i>
                <% } %>
                <%= i %>
            </a>
        </li>
        <% if(theme.sidebar.pages[i].divider === true) { %>
            <li class="divider"></li>
        <% } %>
    <% } %>

```
因为这段代码的实现直接引用了主题`_config.yml`下的`sidebar.pages`里面设定的页面标题, 如
```
sidebar:
  pages:
    about:
      link: '/about'
      icon: bookmark
      divider: false
```
那么展示的自定义入口页就会直接为`about`.

对于常用的自定页(如`about`和`tags`), 能否通过代码优雅地设定其自动化翻译呢?

**Comment by neoFelhz** [comment]
请自行将 about 更换为你自己想要的名字。
请大声朗读文档有关部分二十遍，并抄写二十遍。

**Comment by huangjj27** [comment]
我知道可以通过自行设定想要的名字, 只是觉得这样子做貌似不够优雅, 所以在咨询将这部分进行自动翻译的可行性, 毕竟大家比较常用的`about`, `tags`这样的页面.

**Comment by ghouzenyan** [comment]
I think if you want to achieve the effect you need to refactor 'sidebar-navigation.ejs' and modify i18n language files just as I tried #281

**Comment by viosey** [comment]
about 就中文而言，根据不同的语境可以翻译成 关于，关于我，关于本站，关于网站，个人介绍，介绍。
