### ISSUE TITLE
能否让返回顶部按钮一直保持在右下角而不是只在底部才有?

### ISSUE THREAD

**Issue by NanerLee** [viosey/hexo-theme-material#282]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

类似于google+ 的新建按钮

**Comment by neoFelhz** [comment]
这是原来的设计；考虑到移动端用户体验，后来 @viosey 将 FAB 浮动取消了。

**Comment by NanerLee** [comment]
@neoFelhz , 原来是这样, 其实我觉得可以设置一个选项, 让使用者来决定启用或禁用

**Comment by viosey** [comment]
我正在调整返回顶部的设计，或将在下个版本发布 ：）

**Comment by neoFelhz** [comment]
#318
