### ISSUE TITLE
Could not render MathJax correctly

### ISSUE THREAD

**Issue by ghouzenyan** [viosey/hexo-theme-material#283]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

There is something wrong in #262 .
MathJax could not be used by replacing it as a CDN or local link directly. There is a configuration file like `?config=TeX-AMS-MML_HTMLorMML`. [Read here.](http://docs.mathjax.org/en/latest/configuration.html#configuring-mathjax)
So if the function I want is still valid, the easiest solution is using the original config.
Cloud you please fix that?

**Comment by ghouzenyan** [comment]
@viosey @neoFelhz Guys, have u ever tested the PR? I dont mean that `?config=TeX-AMS-MML_HTMLorMML` added to the config can take effect. If I accept this new commit #295 , I will see some error messages like
> Failed to load resource: the server responded with a status of 404 (Not Found)

And I have tried to add `MathMenu.js` & `MathZoom.js` to `/extension` file, but still not work.

I do not know if I am the only one.

**Comment by neoFelhz** [comment]
@ghouzenyan It causedq by your webserver can't identify query setting of file.
