### ISSUE TITLE
ICP备案号怎么放美观

### ISSUE THREAD

**Issue by JcmeLs** [viosey/hexo-theme-material#284]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

没有艺术细胞的我怎么放都违和。。。不知道有没有建议放在哪块区域才美观

**Comment by AkarinServer** [comment]
@JcmeLs 你可以放在侧边栏的左下角或者底部footer处

**Comment by viosey** [comment]
@JcmeLs 侧边栏或者footer Copyright 位置
