### ISSUE TITLE
gallery 中的缩略图不显示

### ISSUE THREAD

**Issue by NanerLee** [viosey/hexo-theme-material#285]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

缩略图用和原图一个地址, 在gallery页面缩略图不显示,但是全图能够显示.

我发现@viosey 的博客是正常的, 但好像@neoFelhz 的博客的图库的缩略图也不显示.
不知道是什么原因?

**Comment by neoFelhz** [comment]
图库页面启用了 lazyload 特性，对于大量的图片，不会一开始就加载。这是为了尽快完成页面的 DOMLoad
 而做的优化。

**Comment by NanerLee** [comment]
@neoFelhz 感觉不是lazyload的问题, 如果是这个的问题,那么我打开网页等待一会儿缩略图就能显示(viosey的就是这样), 但是我们的gallery页面我等待了几个小时缩略图也没出来

**Comment by neoFelhz** [comment]
请提供控制台的 console log

**Comment by cubesky** [comment]
fix via #287
