### ISSUE TITLE
中文文档漏掉了字符

### ISSUE THREAD

**Issue by WinDaX** [viosey/hexo-theme-material#286]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

中文文档，快速开始，启用「Material」中：
“将 material 文件夹中的 config.template.yml 重命名名为 config.yml。”
应为“将 material 文件夹中的_ config.template.yml 重命名名为 _config.yml。”

**Comment by kmahyyg** [comment]
@WinDaX about this,make a pr
