### ISSUE TITLE
Add `layout: categories` function

### ISSUE THREAD

**Issue by lslvxy** [viosey/hexo-theme-material#29]
目录组件在tags，links，about页面也会显示，但是是没有目录内容的

**Comment by w4lle** [comment]
确实有这个问题

**Comment by neoFelhz** [comment]
由于 Hexo 本身对于分类的一些奇怪的问题，我们打算弱化主题的分类功能，所以我们暂时没有开发独立分类页面的计划。对于分类，我们现在已经在侧边栏提供了分类 dropdown menu 的选项。
