### ISSUE TITLE
主页的logo部分的图片大小问题

### ISSUE THREAD

**Issue by NanerLee** [viosey/hexo-theme-material#290]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

logo部分的图片好像不是填充满的? 这样的话如果我换一个不是白色背景的图片, 在整个页面就会显得很突兀.

**Comment by neoFelhz** [comment]
Please give us a demo.

**Comment by NanerLee** [comment]
@neoFelhz 
![2017-04-15 17-02-57](https://cloud.githubusercontent.com/assets/16791509/25062428/82ec8ac0-21fe-11e7-835b-70410a029ae1.jpg)

由于右边的图片没有填充满, 留白太多, 再加上图片的边界,就显得非常不和谐, 特别是跟左边的填充满的图片放在一起的时候

**Comment by neoFelhz** [comment]
In fact, that is our design. This is used to show a logo, not a picture. So you can just cut that picture as circle.  :-)

**Comment by NanerLee** [comment]
恩, 这样的设计是比较适合放logo, 而不是普通的图片.

但是请考虑放置图片的情景, 因为一个好的logo还是比较难设计, 而好的图片很好找

![2017-04-15 18-47-42](https://cloud.githubusercontent.com/assets/16791509/25063063/691875a6-220c-11e7-9d41-93cb25d78892.jpg)
像上边一样会不会好很多(自己乱替换搞出来的, 如果能全充满就更好了)

我不会前端也没学过设计, 这只是我自己的感觉提出来的建议, 如果有什么不对的勿怪

**Comment by Halyul** [comment]
如果是直接把图片弄成圆形使之像一个logo呢？

**Comment by viosey** [comment]
LOGO 与图片不可兼得也
介于头像已经显示在每个 post card 以及侧边栏，所以此块是用来放置 logo
