### ISSUE TITLE
hexo站内搜索强化

### ISSUE THREAD

**Issue by neoFelhz** [viosey/hexo-theme-material#3]
看到hexo有搜索插件，希望主题的搜索可以支持hexo-generator-search插件，或者借助hexo-generator-json-content生成的字段实现，而不是调用搜索引擎实现。

**Comment by viosey** [comment]
会的，一步一步来。
近期计划先再做一套内嵌样式（scheme）。
然后完善部分细节后正式发布。

第三方会不断完善。
