### ISSUE TITLE
Categories table can not work

### ISSUE THREAD

**Issue by Leiouflying** [viosey/hexo-theme-material#30]
This theme have not got categories table. But have got categories function. So I can visit "example.com/categories/[my_categories]/" but I can not visit "example.com/categories/" and it not only can not return a wrong code but also cause everything which are in this page all broken. I hope you can repair this problem on time. 
Thanks.

**Comment by Leiouflying** [comment]
But I have probably find a way to solve this problem for the time being.
You may try to delete "/categories" this folder. It can return a wrong code when you visit "/categories"

**Comment by viosey** [comment]
#29
