### ISSUE TITLE
Something is wrong.

### ISSUE THREAD

**Issue by kmahyyg** [viosey/hexo-theme-material#304]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

See error log here: 

> https://www.hastebin.com/luradofuge.sql

Something is wrong when running ```hexo g ```

Help wanted! I guess there's something wrong with my config about individual pages icon.

**Comment by viosey** [comment]
What's your theme version?
Is there any error if you use the template config ?

**Comment by viosey** [comment]
If you're updating your theme, make sure you have solve the breaking changes.
https://github.com/viosey/hexo-theme-material/releases

**Comment by kmahyyg** [comment]
i just use ```git clone``` to get the latest version in master branch.

I try to use the template theme config and remain site config unchanged.But
there's still a problem here.the Same error information.

hexo v3.3.0 nodejs4.4.2 , using webide in https://c9.io

2017年4月20日 15:29，"Viosey" <notifications@github.com>写道：

**Comment by neoFelhz** [comment]
@viosey @kmahyyg 
I think I know what is going on.
I have the same problem here, when I updarte to the hexo 3.3.1.
You can set the `relative_url` as `false` in your site config file.

**Comment by kmahyyg** [comment]
also , I am updating from the old version,like 0.9.xx(I don't know,the
```git log``` tells me that the commit which I updated from is merge
issue/pr #73)

2017年4月20日 17:25，"Patrick Young" <kmahyygyyg@gmail.com>写道：

**Comment by neoFelhz** [comment]
@kmahyyg I suggest that you can just download the theme in github's release page, instead of using `git pull` to avoid confilicts. We have refactored the theme before.

**Comment by kmahyyg** [comment]
@neofelhz The ```relative_link``` in my site config is already false. so it
isnot about this preference.

2017年4月20日 17:27，"Patrick Young" <kmahyygyyg@gmail.com>写道：

**Comment by kmahyyg** [comment]
@kmahyyg thx. problem fixed when using the 1.3.4 in your release page.

closed.

maybe you could do a revert.,^_^
