### ISSUE TITLE
提交bug

### ISSUE THREAD

**Issue by DreamYHD** [viosey/hexo-theme-material#316]
-->

**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

为什么java中的代码如果使用注解的话会错位，很乱

**Comment by neoFelhz** [comment]
The Hexo's built in highlight.js can't work well on Material Theme.
Please use `hexo-theme-material` plugin instead.
https://material-org.viosey.com/expert/
