### ISSUE TITLE
Feature request: 独立页面禁用评论选项

### ISSUE THREAD

**Issue by cielpy** [viosey/hexo-theme-material#32]
一些独立页面作为展示用，可能不需要集成评论服务。
之前使用 [Jacman](https://github.com/wuchong/jacman) 的时候可以在 post 中添加一个选项来禁用评论功能，类似这样：

```
---
title: 关于
date: 2014-05-26 13:28:15
type: "about"
comments: false
---
```

希望添加类似的功能。

**Comment by viosey** [comment]
已添加，用法为 `comment: false`

**Comment by cielpy** [comment]
感谢~
