### ISSUE TITLE
希望首页摘要能支持显示 description 的内容

### ISSUE THREAD

**Issue by Yubyf** [viosey/hexo-theme-material#320]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

本主题下主页文章下简介部分是通过设置文字长度来确定的，但是现在很多主题已经支持显示
 `description` 的介绍，希望本主题也能支持这个功能。谢谢

**Comment by cubesky** [comment]
你可以在文章中添加 
```
<!-- more -->
```
来指定首页显示多长的内容

**Comment by EYHN** [comment]
或许可以加一个 description 属性

**Comment by Yubyf** [comment]
@cubesky 我知道这种方法，但是不是特别喜欢这样的手段，毕竟会破坏源文章的结构，而且这个方法也可以准确地显示文章的大概内容。我认为这是一个很人性化的功能，相信有不少有这杨需求的人。

**Comment by Yubyf** [comment]
@EYHN 嗯，这样兼容性应该不会有影响

**Comment by cubesky** [comment]
@Yubyf 你可以尝试在 front-matter 中添加 `excerpt` 项，主题会使用 `excerpt` 中的内容作为摘要

**Comment by Yubyf** [comment]
@cubesky 我试过了，都读取不出来 `excerpt` 的内容

**Comment by ghouzenyan** [comment]
@Yubyf 需要安装 `hexo-front-matter-excerpt` 这个插件，默认是读取 `<!-- more -->`

**Comment by Yubyf** [comment]
感谢 @ghouzenyan @cubesky 通过 `hexo-front-matter-excerpt` 读取 `excerpt` 基本上解决了这个问题。
