### ISSUE TITLE
gallery页面的缩略图不显示

### ISSUE THREAD

**Issue by Michael728** [viosey/hexo-theme-material#325]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

查看了相关的文档，采用了lazyload，但是，我等待了很久，照片依然看不到缩略图，这使用体验很让我困惑，因为点击图片，是能够看到图片的，而之间看gallery页面，都是一个个黑色框，很不美观，希望能够解决该问题。
下面是我gallery.yml的内容：
```
苏州-拙政园:
	  full_link: http://b391.photo.store.qq.com/psb?/V12hsGcd2LIOzX/Dx47vFYIBZdqOU1QJkfVU280IP.di0wR7ZSaizPQ1VQ!/b/dAUKEelbCAAA&bo=VQOAAkAGsAQBCgs!&rf=viewer_4
	  thumb_link: http://b391.photo.store.qq.com/psb?/V12hsGcd2LIOzX/Dx47vFYIBZdqOU1QJkfVU280IP.di0wR7ZSaizPQ1VQ!/b/dAUKEelbCAAA&bo=VQOAAkAGsAQBCgs!&rf=viewer_4
	  descr: "本科毕业旅行-2014年5月-拙政园-小豪陪同我们参观的"
苏州-山塘街:
	  full_link: http://ww1.sinaimg.cn/large/6d9475f6ly1ff108o1rvkj20np0hstbf.jpg
	  thumb_link: http://ww1.sinaimg.cn/thumbnail/6d9475f6ly1ff108o1rvkj20np0hstbf.jpg
	  descr: "本科毕业旅行-2014年5月-吃了至今难忘的鸡爪"
```

**Comment by ghouzenyan** [comment]
如果你是 `master`，以前遇到过相似问题，删除 `source` 文件里的图库相关配置，然后重新配置，并且 `hexo clean`，再调试看看。
如果是 `canary`，#287 好像修复过 queue，后来又有个 #312 取消 localstage，你尝试更新 `canary`，应该没问题。

**Comment by neoFelhz** [comment]
@ghouzenyan localstorage 方案的确是 `canary` ，尚未发布正式版本的。至于之前因 queue 导致的无法加载的 bug，是在 1.3.4 修复了的。
@Michael728 能否提供一下 Demo？

**Comment by viosey** [comment]
@neoFelhz 这是他的图库页面：http://michael728.github.io/gallery/
1.3.4版本

**Comment by cubesky** [comment]
`1.3.4` 版本似乎未包含图库修复
`1.3.4` 版本之后的 `canary` 分支才修复了此问题 [47d936b](https://github.com/viosey/hexo-theme-material/commit/47d936b985fdc3e61b8484e313df45c3c60ee98a)

**Comment by viosey** [comment]
We have fixed this bug at canary version.
After few days, we will release `1.4.0` formal version.
