### ISSUE TITLE
本地搜索无法正常使用

### ISSUE THREAD

**Issue by XiaoFanHenNuLi** [viosey/hexo-theme-material#329]
**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

更新到最新版本之后，本地search无法正常使用了.
确保 搜索插件 已安装、config已设置。但是就是无法正常使用。
每次hexo g生成文件时，会生成serach.xml文件. 
material\layout\_widget\search-local-js.ejs 文件未修改

![image](http://op0fbtmbd.bkt.clouddn.com/bug.png)

[个人博客地址](http://lyfer.club)

**Comment by neoFelhz** [comment]
@XiaoFanHenNuLi 
Material 主题已经适配好了 localsearch 的有关代码（可见 `search-local-js.ejs`），无需手动插入。
另外，你的博客 DIY 的东西太多了，断点都打不下去，没法测试~
建议重新安装主题，先不做任何改动，测试一下功能是否可用。。

**Comment by neoFelhz** [comment]
@XiaoFanHenNuLi 
```html
// A local search script with the help of [hexo-generator-search](https://github.com/PaicHyperionDev/hexo-generator-search)
// Copyright (C) 2015 
// Joseph Pan <http://github.com/wzpan>
// Shuhao Mao <http://github.com/maoshuhao>
// Edited by MOxFIVE <http://github.com/MOxFIVE>
```

这段注释从哪里跑出来哒。。我们的代码中没有这一段。。
