### ISSUE TITLE
The css can not color in normally

### ISSUE THREAD

**Issue by TonnyL** [viosey/hexo-theme-material#333]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

The css can not color in normally from 5.1.2017. I can not find out what's wrong. Here is a screenshot. Hope you could help me find a solution. Thanks a lot. The blog is much important for me.

![](http://ww2.sinaimg.cn/large/006tNbRwgy1ff5tdghiqkj31kw106dt6.jpg)

**Comment by ghouzenyan** [comment]
I think you should use CDN config with your own domain or try calling the local file firstly.

**Comment by neoFelhz** [comment]
@TonnyL Please give us a demo with console log in browser.

**Comment by TonnyL** [comment]
@ghouzenyan  Yes, I am using the cdn with default config.  Here is the code of `_config.yml`.

```yml
materialcdn:
    use: true
    base: https://materialcdn.nfz.moe/hexo/1.3.2
```

And here, is the console log(seems nothing wrong).

![](http://ww4.sinaimg.cn/large/006tNbRwgy1ff5u47kzvij31kw10610t.jpg)

![](http://ww4.sinaimg.cn/large/006tNbRwgy1ff5u47kzvij31kw10610t.jpg)

Thanks for your help so much even it is in holiday.

**Comment by neoFelhz** [comment]
@TonnyL  MaterialCDN is in maintenance...

**Comment by TonnyL** [comment]
@neoFelhz 
😂 Ahhh... OK, how long will it be finished?
