### ISSUE TITLE
网页自适应时，footer部分的瑕疵

### ISSUE THREAD

**Issue by yifer97** [viosey/hexo-theme-material#335]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

如果把博客的自适应界面分为三种情况的话（个人意见）
1.宽屏（一般电脑打开的状态）  2. 手机竖屏   3.居于两者之间（差不多ipad那个状态）
发现在宽屏和手机竖屏状态都还是挺完美的
但是在类似ipad打开时，footer部分的主题版权那一块出现不对称的现象
下面放图：（图1 宽屏（正常）；图2：手机竖屏（正常）；图3 不对称的演示）

![图1宽屏][1]
![图2][2]
![图三][3]

[1]:http://7xlwvm.com1.z0.glb.clouddn.com/image/5.2/1.png
[2]:http://7xlwvm.com1.z0.glb.clouddn.com/image/5.2/3.png
[3]:http://7xlwvm.com1.z0.glb.clouddn.com/image/5.2/2.png

（就随手用了主题作者的博客直接截图了，不算侵权吧..…^-^）
可以很明显的看到
```
Powered by hexo
theme -material
```
没有居中

对于强迫症的人来说，非常致命！望修复！

**Comment by yifer97** [comment]
图2 挂了？
算了反正那个不打紧

**Comment by viosey** [comment]
got it, 将在 1.4.0 版本修复
