### ISSUE TITLE
关于sidebar的footer_image的小问题

### ISSUE THREAD

**Issue by yifer97** [viosey/hexo-theme-material#336]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

sidebar底部的图片在使用多个图片时，其每两个之间会有“-”，不太美观
我觉得有“-”应该不是设计的初衷吧？
上一下图

![][1]

无视图挂....

因为自己没学过前端，所以很多东西自己搞不定。

所以再提一个功能上的建议，就是能不能在sidebar下方加入icp备案这个小模块
因为如果对前端不太在行的人，还是有点难度的，尤其是想调的和整个主题融洽起来
当然，icp备案的位置也可以放在别的地方，如果能在主题集成icp模块并提供几个位置可供选择就很完美了呀

致敬！

[1]:http://7xlwvm.com1.z0.glb.clouddn.com/image/5.3/2.png

**Comment by neoFelhz** [comment]
主题不提供备案号的支持
