### ISSUE TITLE
首页摘要Markdown格式输出

### ISSUE THREAD

**Issue by TangelSaki** [viosey/hexo-theme-material#34]
请问能否使首页的文章摘要以Markdown格式输出呢？
看着密密麻麻的几排摘要文字好不舒服。

**Comment by viosey** [comment]
因为文章入口现有的大小限制，暂时还没有考虑使用 Markdown 输出，毕竟只是几十字的摘要。
大多数以 Markdown 样式输出基本都输出了大半篇原文。

在后续的 Nexus scheme 应该会采用 Markdown 格式输出。

**Comment by yech1990** [comment]
@viosey 
nexus scheme 上面时候上线？
