### ISSUE TITLE
有序列表无法正确渲染

### ISSUE THREAD

**Issue by huangjj27** [viosey/hexo-theme-material#343]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

如下图, 如果有序列表项之间的内容存在着代码\图片或其他内容, 则第二项以后将没有序号:
![image](https://cloud.githubusercontent.com/assets/8068443/25853635/1689277a-3500-11e7-849a-9aeb6bfd5724.png)

**Comment by neoFelhz** [comment]
这不属于 hexo-theme-material 的 Bug。请仔细阅读和学习 Markdown 编写规范。Hexo 使用的是 Markdown，而不是 Microsoft Word。

**Comment by huangjj27** [comment]
我不明白这和Microsoft Word有什么关系. 之前在使用其他的hexo主题的时候, 通过缩进(2或4空格缩进)是可以在有序列表中插入图片和代码的, 然而在material中却不支持.  
并且[daringfireball markdown文档](https://daringfireball.net/projects/markdown/syntax#list)里面也没有任何关于在有序列表中插入图片的示例

**Comment by neoFelhz** [comment]
Hexo 默认使用 marked.js 工具解析 Markdown。除此以外也有基于 parsedown 的插件。你也可以自己使用 Hyperdown 转义 Markdown。生成 page.content 的部分与 hexo-theme-material 完全无关。

**Comment by EYHN** [comment]
经过我测试 material 主题是可以生成和正常显示有序列表。

![image](https://cloud.githubusercontent.com/assets/13579374/25856821/b8e56a20-3509-11e7-960a-2ad54f66a584.png)

下面是我的 markdown

``` markdown
1.  
   ![](https://camo.githubusercontent.com/9b3fabd704524d197350f1059ba43f7c7b8e927e/68747470733a2f2f7472617669732d63692e6f72672f546f72612d6465762f546f72612e7376673f6272616e63683d6d6173746572)
1.   123
   ![](https://camo.githubusercontent.com/9b3fabd704524d197350f1059ba43f7c7b8e927e/68747470733a2f2f7472617669732d63692e6f72672f546f72612d6465762f546f72612e7376673f6272616e63683d6d6173746572)
```

**Comment by huangjj27** [comment]
嗷, 所以是解析工具无法生成所要求的样式, 而我错只需要做的, 是换一个更好的解析器.

**Comment by EYHN** [comment]
@huangjj27 我认为是你语法错误 而不是解释器的问题

**Comment by huangjj27** [comment]
我的语法是:
数字序号.(空格)第一行(行尾双空格)
(2/4空格缩进)![图片](图片链接)

**Comment by EYHN** [comment]
@huangjj27  如果方便请帖上整个markdown文档

**Comment by huangjj27** [comment]
@EYHN 源文档在github上粘贴需要修改比较多的样式, 因此整个副本发至你邮箱. 这里我最后发现的问题.
效果图暂时无法上传(系github的图片上传功能 不支持Ubuntu还是无法支持Ubuntu的拷贝粘贴?)

以下是第一次出现问题的片段, 第三第四项没有序号:
```
1. 安装好`nodejs`和`hexo`  
1. 在gitlab上新建`username.gitlab.io`空仓库  
1. 在本地新建博客目录`blog`, 并初始化:  

        $ cd blog
        $ hexo init

1. 在博客目录中, 初始化git仓库并添加`gitlab`远程仓库:  

        $ git init
        $ git remote add origin git@gitlab.com/username/username.gitlab.io.git
```


而去掉空行之后, 渲染正确:
```
1. 安装好`nodejs`和`hexo`  
1. 在gitlab上新建`username.gitlab.io`空仓库  
1. 在本地新建博客目录`blog`, 并初始化:  
        $ cd blog
        $ hexo init
1. 在博客目录中, 初始化git仓库并添加`gitlab`远程仓库:  
        $ git init
        $ git remote add origin git@gitlab.com/username/username.gitlab.io.git
```
也许是之前使用别的主题, 或者`segmentfault`要求前后有空行才能正确渲染, 所以在这里就错误了.

最后感谢@EYHN的耐心解答

**Comment by huangjj27** [comment]
然而, 这个issue最初提的问题是, 列表项中插入两个图片后, 接下来的列表项就无法正常渲染: 
```
1. 在Google搜索中输入`site:yourname.gitlab.io`, 如下图所示：  
    ![输入site:huangjj27.gitlab.io](/uploads/images/hexo-on-gitlab/site-search.png)  
1. 点击第一个链接，进入到Google搜索控制台，添加属性，选择属性资源为网站，并填入站点域名：  
    ![添加站点属性](/uploads/images/hexo-on-gitlab/add-site.png)  
1. 下载验证文件, 并放到站点源码仓库目录下:  
    ![下载验证文件](/uploads/images/hexo-on-gitlab/validation.png)  
    ![放好验证文件](/uploads/images/hexo-on-gitlab/copy-validation.png)  
1. 修改`.gitlab-ci.yml`文件, 提交并部署站点:  
    ```
    pages:
        script:
            - hexo generate
            - cp googleXXXXX.html public    # add this line for validation
        artifacts:
            paths:
                - public
        only:
            - master

    ```
1. 继续完成验证的步骤. 完成后, 可以看到如下界面:  
    ![完成验证](/uploads/images/hexo-on-gitlab/succeed-validation.png)  
```

**Comment by EYHN** [comment]
第一个问题 `第三第四项没有序号` 为 chrome 的 bug ,具体在哪个版本修复的未知.

**Comment by huangjj27** [comment]
上一条问题, 去掉代码后可以渲染.

**Comment by EYHN** [comment]
> 两个图片后, 接下来的列表项就无法正常渲染

也是 chrome 的 bug

**Comment by EYHN** [comment]
是由 p 标签的 `overflow:hidden` 引起的

**Comment by EYHN** [comment]
http://jsfiddle.net/cpburnz/z96HD/1/

这里是重现

chrome 57.0.2987.133 显示:
![image](https://cloud.githubusercontent.com/assets/13579374/25860507/57e1e72a-3514-11e7-8b1b-b7185ac36b14.png)

chrome 60.0.3087.0 显示:
![image](https://cloud.githubusercontent.com/assets/13579374/25860555/764fa346-3514-11e7-8c8b-997159513241.png)

有毒 orz

**Comment by huangjj27** [comment]
ORZ

**Comment by huangjj27** [comment]
最后的解决方案是, 不在有序列表里面使用fencing code风格的代码, 一切渲染正常.

**Comment by Cikian** [comment]
代码：
```markdown
1. 列表内容
2. 列表内容
3. 列表内容
```
显示：
列表内容
列表内容
列表内容

语法没错，不显示序号是什么原因

**Comment by Cikian** [comment]
代码：
```markdown
1. 列表内容
2. 列表内容
3. 列表内容
```
显示：
列表内容
列表内容
列表内容

语法没错，不显示序号是什么原因
