### ISSUE TITLE
代码块中 @ 后面内容 格式会乱

### ISSUE THREAD

**Issue by xubinux** [viosey/hexo-theme-material#344]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

![20170511149446993136119.png](http://on2bs9q7q.bkt.clouddn.com/20170511149446993136119.png)

如图 `@SuppressWarnings("unchecked")` 格式出错

**Comment by cubesky** [comment]
从1.3.0开始我们使用 `hexo-prism-plugin` 进行高亮渲染，请查看文档
[https://material.viosey.com/expert/#代码高亮样式](https://material.viosey.com/expert/#代码高亮样式)
