### ISSUE TITLE
About the TOC of article

### ISSUE THREAD

**Issue by NanerLee** [viosey/hexo-theme-material#345]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

先看下面的两个图片
![2017-05-12 16-04-50](https://cloud.githubusercontent.com/assets/16791509/25989009/005e854c-372d-11e7-84ba-231956b4e910.png)

![2017-05-12 16-06-06](https://cloud.githubusercontent.com/assets/16791509/25989023/0ca863fe-372d-11e7-8c0b-1c4998e49f7a.png)

可以看到生成toc的时候自动给标题加上了序号, 但是如果章节标题本身就带有序号, 就会像第二幅中那样出现两个标号. 最最重要的是, 自动加序号会使这些标题的链接改变 , 导致跳转到某一章节的链接失效而不能跳转.

我觉得明显标题的序号应该是写文章的人应该负责的东西, 这不是程序需要做的.

**Comment by neoFelhz** [comment]
This might be a problem. We will consider about it and decide whether remove it or not.
