### ISSUE TITLE
something is wrong when deploying with netlify ci

### ISSUE THREAD

**Issue by kmahyyg** [viosey/hexo-theme-material#350]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

我用netfily ci想deploy，因为他家会自动安装package.json里的依赖并使用对应版本的nodejs，我的deploy命令就只是 ```hexo g```，ci的publish目录为repo下的public.

同样的配置，在我的工作环境，cloud9 webide，正常运行。
但是用ci的时候，主题的post.ejs报错了，而且disqus没有办法正常加载。

1.disqus支持force https吗？
2.CI LOG: 

https://hastebin.com/zacesohitu.xml

repo地址： github.com/kmahyyg/rr.hostpot.ml

**Comment by neoFelhz** [comment]
Your `config.yml` has some fault that need to be solved..

**Comment by kmahyyg** [comment]
could you plz help me check it out?

directly view it at github.com/kmahyyg/rr.hostpot.ml

neoFelhz <notifications@github.com>于2017年5月14日周日 15:32写道：

**Comment by neoFelhz** [comment]
Err....
You should get into your local repo and edit the `.gitignore` in your theme dir, and remove `_config.yml`.
Your config just simply haven't push into the Github

**Comment by kmahyyg** [comment]
er......that's the problem.I'll try and reopen this issue if the problem is still existed.
