### ISSUE TITLE
申请添加新的特性或功能

### ISSUE THREAD

**Issue by WangChangQin** [viosey/hexo-theme-material#352]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [ ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

多说快关闭了，可以新增网易云跟帖吗？

**Comment by cubesky** [comment]
网易云跟帖将在下个版本提供

**Comment by neoFelhz** [comment]
#351
