### ISSUE TITLE
代码高亮失败

### ISSUE THREAD

**Issue by Ryan-Miao** [viosey/hexo-theme-material#359]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

我在本地渲染页面后发现无法代码高亮，代码块重叠。
```java
@RequestMapping(value = "saveOrUpdate", method = RequestMethod.POST)
public String saveOrUpdate(HttpServletResponse response, @RequestBody Order order){
	CodeMsg result = null;
	try {
		result = orderService.saveOrUpdate(order);
	} catch (Exception e) {
		logger.error("save failed.", e);
		return this.renderString(response, CodeMsg.error(e.getMessage()));
	}
	return this.renderString(response, result);
}

@ResponseBody
@ResponseStatus(HttpStatus.BAD_REQUEST)
@ExceptionHandler(HttpMessageNotReadableException.class)
public CodeMsg messageNotReadable(HttpMessageNotReadableException exception, HttpServletResponse response){
    LOGGER.error("请求参数不匹配。", exception);
    return CodeMsg.error(exception.getMessage());
}
```

显示为结果请查看我的文章里的java代码。
https://ryan-miao.github.io/2017/05/20/spring400/

想问下是代码高亮还需要配置吗？

**Comment by neoFelhz** [comment]
Of course you haven't read the docs carefully.
See #267 for more details.
