### ISSUE TITLE
bug about search 

### ISSUE THREAD

**Issue by zsjsll** [viosey/hexo-theme-material#362]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [ ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

I write a blog about C++, and use the keyword"C++"to search,  a bug was found ...
the "+" has something wrong like this ...

there is an extra "+" between "C" and "++"

**Comment by neoFelhz** [comment]
Can you give us a demo?

**Comment by zsjsll** [comment]
@neoFelhz 
![tim 20170524173208](https://cloud.githubusercontent.com/assets/16866928/26397185/025d056a-40a8-11e7-935f-fe69b24811dc.png)
![tim 20170524173228](https://cloud.githubusercontent.com/assets/16866928/26397187/02adf074-40a8-11e7-99a7-43bd7a8e3c70.png)

**Comment by neoFelhz** [comment]
@zsjsll 
Well. It caused by the `hexo-generator-search`. As you can see, even though you are using Yilla theme now.

**Comment by zsjsll** [comment]
@neoFelhz but i found that the same as using the `hexo-generator-search` of  Next theme , the bug does not exist
