### ISSUE TITLE
我们博客现在以及将来都会保持极简的界面吗

### ISSUE THREAD

**Issue by Ryan-Miao** [viosey/hexo-theme-material#364]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

发现我们主题的博客很清爽，但太简约了吧，电脑浏览的时候旁边给个推荐啥的不好吗。我们版本就是简洁至上吗？

**Comment by neoFelhz** [comment]
是的。我们希望没有最简洁，只有更简洁。
实际上，现在的样式已经偏花哨了，有这么多的图片和动画，不是么？

**Comment by Ryan-Miao** [comment]
但是间接到只能看到本文章，相关的信息很少。如果想写一个专题系列的话咋搞，只能通过标签吗

**Comment by neoFelhz** [comment]
@Ryan-Miao 善用分类和标签功能。
