### ISSUE TITLE
可以增加来必力评论支持吗

### ISSUE THREAD

**Issue by zjlx** [viosey/hexo-theme-material#365]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [ ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

希望增加来必力评论，万分感谢！

**Comment by neoFelhz** [comment]
OK. I will add it to the ToDo List.

**Comment by zjlx** [comment]
非常感谢

**Comment by xdevs23** [comment]
@zjlx Y u do tits

**Comment by neoFelhz** [comment]
fixed in version [1.5.0](https://github.com/viosey/hexo-theme-material/releases/tag/1.5.0)
