### ISSUE TITLE
感觉翻页方向反了

### ISSUE THREAD

**Issue by lslvxy** [viosey/hexo-theme-material#37]
新篇和旧篇是不是交换下比较好，感觉向后翻是下一个向前是上一个的意思

**Comment by lslvxy** [comment]
还有下面的分页希望能加强页码列表，现在只有个当前页

辛苦作者了

**Comment by viosey** [comment]
不是的，旧篇是 older，新篇是 newer。

**Comment by lslvxy** [comment]
我的意思是旧篇现在不是一个→但是向右箭头一般不都是表示下一个的意思么？下一个不应该是newer么

**Comment by viosey** [comment]
参考 [Google Security Blog](https://security.googleblog.com/2016/11/sha-1-certificates-in-chrome.html)
newer 为左箭头，older 为右箭头。

**Comment by viosey** [comment]
### Newer: 
![google-official-blog-newer.png](https://ooo.0o0.ooo/2016/11/23/5835c9b59ed7e.png)

---

### Older: 
![google-official-blog-older.png](https://ooo.0o0.ooo/2016/11/23/5835c9b59e0e5.png)
