### ISSUE TITLE
图库的缩略图不显示

### ISSUE THREAD

**Issue by janostudio** [viosey/hexo-theme-material#371]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

你好：
我根据文档在gallery.yml文件夹内输入
```
gallery:
	full_link: full_img.jpg
	thumb_link: thumb_img.jpg
```
但是缩略图未显示，查看网站代码发现`image lazy`class未设置background-image属性，是我哪里书写错误了吗？

**Comment by cubesky** [comment]
您好，这个 bug 已经在最新的开发版本中被修复了，我们将尽快发布，感谢您的使用~

**Comment by qiguoqiang** [comment]
同样碰到了这个问题

**Comment by neoFelhz** [comment]
@qiguoqiang 升级 1.4.0
