### ISSUE TITLE
About of Analytics Systems

### ISSUE THREAD

**Issue by NanerLee** [viosey/hexo-theme-material#373]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [X] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [X] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [X] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [X] support request | 请求技术支持

在最新发布的1.4.0版本中，统计分析服务做了改变，是不是改动之后不能同时使用多家的统计服务？

**Comment by neoFelhz** [comment]
嗯，是的。。。
暂时的应对方案是使用“自动义代码”特性（https://material.viosey.com/expert/#添加自定义代码），即将其它统计服务的统计代码复制到 `head.yml` 中。
后期对于多种统计服务会做优化。

**Comment by NanerLee** [comment]
好的， 不过回复的好快

**Comment by neoFelhz** [comment]
fixed in version [1.5.0](https://github.com/viosey/hexo-theme-material/releases/tag/1.5.0)
