### ISSUE TITLE
添加网易云跟帖评论功能

### ISSUE THREAD

**Issue by xiongxianzhu** [viosey/hexo-theme-material#375]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

楼主可以添加[网易云跟帖评论](https://gentie.163.com/index.html)吗？谢谢～

**Comment by cubesky** [comment]
网易云跟帖从 1.4.0 版本起已被支持，设置主题的 `_config.yml`

```yaml
comment:
    use: 163gentie
    gentie_productKey: 你的网易云跟帖Key
```

即可

**Comment by xiongxianzhu** [comment]
谢谢楼主， 原来npm的不是最新版本， 我还是从github下载吧

**Comment by BarryLiu1995** [comment]
@cubesky 你好，我按照上面的成功添加了网易跟帖，但是发现在pc网页上点击评论按钮时没有任何反应，而在手机浏览器上评论却有效果，请教一下这是怎么回事
![qq 20170625104429](https://user-images.githubusercontent.com/20590350/27513296-7be5c1d4-5993-11e7-9a1b-c532bd37c87e.jpg)

**Comment by cubesky** [comment]
@BarryLiu1995 已在当前测试版本中解决此问题

**Comment by BarryLiu1995** [comment]
@cubesky 意思是material 主题的测试版本已经解决了这个问题？

**Comment by cubesky** [comment]
@BarryLiu1995  是的

**Comment by BarryLiu1995** [comment]
@cubesky 那最新正式版什么时候有

**Comment by BarryLiu1995** [comment]
@cubesky 你好，我当前使用测试版发现上面的问题还是存在，好像 并没有解决。配置如下
![163](https://user-images.githubusercontent.com/20590350/27667329-99b3956c-5cac-11e7-8ba5-cfc17fa9b5cd.jpg)
而使用来必力发现博文会变空白
