### ISSUE TITLE
滚动条移至最下方会出现页面不断抖动情况

### ISSUE THREAD

**Issue by xiongxianzhu** [viosey/hexo-theme-material#376]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

https://blog.viosey.com/archives/2017/04/ 发现一个bug， 本人使用google chrome 58.0.3029.110 (64-bit) , 当归档里存在至少2篇文章， 将滚动条移到最下方会出现不断抖动的情况

**Comment by neoFelhz** [comment]
@viosey

**Comment by neoFelhz** [comment]
@viosey On archives page with only two posts, the `totop` button will cause some issue.

**Comment by cubesky** [comment]
fixed #406

**Comment by neoFelhz** [comment]
fixed in version [1.5.0](https://github.com/viosey/hexo-theme-material/releases/tag/1.5.0)
