### ISSUE TITLE
使用网易云跟帖评论会存在缓存问题

### ISSUE THREAD

**Issue by xiongxianzhu** [viosey/hexo-theme-material#377]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

本人已正确配置网易云跟帖， 在页面第一次访问时能正常加载网易云跟帖， 再次刷新就不能加载网易云跟帖了， 只有将浏览器缓存清空， 刷新页面时才正常加载， 再次刷新则又不能正常加载～～
示例如下： https://www.zhuxiongxian.cc/2017/05/21/hello-world/

**Comment by neoFelhz** [comment]
@EYHN

**Comment by EYHN** [comment]
请你试试 #378 我不确定一定有效

**Comment by neoFelhz** [comment]
@EYHN 你确定是因为把网易云跟帖丢进了 localstorage？

**Comment by EYHN** [comment]
不确定 但网易云跟帖确实往里面丢东西了

**Comment by BarryLiu1995** [comment]
@xiongxianzhu 我想问问你有没有遇见网易云跟帖时隐时现，有时有有时就没有？

**Comment by TakWolf** [comment]
@BarryLiu1995 同样的问题，有一定几率评论框不现实。不清楚问题是什么

**Comment by BarryLiu1995** [comment]
@TakWolf 可能是bug吧

**Comment by TakWolf** [comment]
@BarryLiu1995 
移动端模式表现状态是，刚加载页面是是有评论框的。这时候页面没加载完成，等页面加载完成抻了一下，评论框就消失了。

div 是在的，但是就是显示没了。现在基本百分百出现。文章底部有一段空白，不知道是不是这个原因。

![image](https://user-images.githubusercontent.com/6064962/27513854-8d568e92-59a9-11e7-9673-e68a8310a037.png)

**Comment by neoFelhz** [comment]
![image](https://user-images.githubusercontent.com/19367350/27513875-2c1d3c60-59aa-11e7-811d-bfed1cb9f525.png)

It works functionally.

**Comment by TakWolf** [comment]
@neoFelhz 
PC模式下也有几率出现

![image](https://user-images.githubusercontent.com/6064962/27513939-74ad6d5e-59ac-11e7-8932-b086c7d23469.png)

我不知道出现问题的原因，我无法稳定复现这个问题。但是出现的概率很大。

我的配置是这样的，感觉没有什么问题。

![image](https://user-images.githubusercontent.com/6064962/27513944-a75d7488-59ac-11e7-98ae-12be502041f1.png)

=====================

我不确定是不是网易的 BUG，感觉和页面 resize 有关系。

因为 dom 节点确实渲染了，但是实际上却不显示

**Comment by TakWolf** [comment]
@neoFelhz 
重新测试了一下，全屏模式下没啥问题。

在缩放和移动端模式下，会有问题。
测试地址：http://blog.takwolf.com/2017/04/05/android-log-wtf/

**Comment by BarryLiu1995** [comment]
@TakWolf 对，情况也就这样，很难稳定复现，但是如果刷新之后就能看见评论区

**Comment by xiongxianzhu** [comment]
@BarryLiu1995 是的哦， 网易云跟帖的确有点问题， 目前还不知道是什么情况， 所以我目前采用disqus评论；
@TakWolf 顺便说一下， 你的博客<http://blog.takwolf.com>使用了prettify代码高亮， 请禁用其他代码高亮，如网站根目录配置文件_config.yml下的：
```
highlight:
  enable: false
```

**Comment by BarryLiu1995** [comment]
@xiongxianzhu 你好，我昨天一直打不开disqus的网站，感觉好像不能用了

**Comment by xiongxianzhu** [comment]
@BarryLiu1995 那是因为有墙...

**Comment by BarryLiu1995** [comment]
@xiongxianzhu 我已翻墙了，但还是打不开他们的网站

**Comment by xiongxianzhu** [comment]
@BarryLiu1995 那是因为墙高， 你墙不过去，反正我能访问， 哈哈...
![](https://cloud.githubusercontent.com/assets/7270968/21770121/d5071132-d6bc-11e6-9f7a-a149fcc9aa59.jpg)

**Comment by duxinfeng** [comment]
![image](https://user-images.githubusercontent.com/8338102/27962449-85fe57e6-6364-11e7-8677-6273568e6413.png)
刚配置好。。。

**Comment by neoFelhz** [comment]
@duxinfeng
@BarryLiu1995
@xiongxianzhu
@TakWolf

The 163gentie will stop services soon.. So I will close this issue..
