### ISSUE TITLE
搜索站内文章

### ISSUE THREAD

**Issue by summersir** [viosey/hexo-theme-material#38]
搜索站内文章 点击并跳转 地址不是站内的地址
yoursite.com.....的某个地址

跳到了这个地址
http://144.dragonparking.com/?site=yoursite.com&t=1479735343&s=ccd206c62478149f8d18d9442fb853bd

不知是何原因

**Comment by viosey** [comment]
https://material.vss.im/start/#URL
请参考这个文档。
如果还有什么错误再 reopen 这个 issue。
