### ISSUE TITLE
新增功能支持prettify theme实现代码高亮

### ISSUE THREAD

**Issue by xiongxianzhu** [viosey/hexo-theme-material#383]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

建议新增功能支持`prettify theme`实现代码高亮,
[code-prettify](https://github.com/google/code-prettify)
[color-themes-for-google-code-prettify](https://jmblog.github.io/color-themes-for-google-code-prettify/)
本人在hexo-theme-material v1.4.0版本下加入了`prettify theme`, 在google chrome浏览器下效果如下:
<https://www.zhuxiongxian.cc/2017/06/05/Ubuntu1604-install-sublimetext3/>
p.s. 等待数秒代码高亮渲染完后即可看到效果.
![screenshot from 2017-06-08 02-50-27](https://user-images.githubusercontent.com/5771876/26895897-a4f9c8e6-4bf5-11e7-8123-09452809c4b1.png)
主题使用方法在主题配置文件_config.yml下的使用方法如下:
```
prettify:
   enable: true
   theme: "vibrant-ink" # "这里你可以定义上面下载的themes主题包里面样式文件名，不带.css后缀"
```
为方便以后hexo-theme-material的升级, 建议楼主能加入该代码高亮支持, 万分感谢~

**Comment by neoFelhz** [comment]
@xiongxianzhu You can simply fork the repo then open a PR.

**Comment by TakWolf** [comment]
@xiongxianzhu 
询问一个关于 prettify 的问题。
prettify 是快内换行，没有横向滚动。
这种自动折行对代码阅读体验非常不好。
怎么解决这个问题？

![image](https://user-images.githubusercontent.com/6064962/27514152-a5170268-59b4-11e7-9b07-d7ce5c9e9b21.png)

**Comment by xiongxianzhu** [comment]
@TakWolf OK， 已改善
`source/css/prettify.css`更改如下：
```
@charset "UTF-8";

/* for color-themes-for-google-code-prettify */
/* Auto add scrollbar instead of line feed */
pre{
    /*white-space: pre-wrap;
    word-break: break-all;
    word-wrap: break-word;*/
    /*overflow-y: hidden!important;
    overflow-x: auto!important;*/
    white-space: nowrap;
}

#post-content .prettyprint{
    padding: 1.2em;
    border-radius: 0;
}

#post-content ol,#post-content ul{
    padding-left: 51px;
    font-size: 1rem;
    margin: 0;
    overflow: initial;
}

#post-content pre code, #post-content pre tt {
    padding-right: 2em;
}

#post-content .prettyprint li.L0, #post-content .prettyprint li.L1,
#post-content .prettyprint li.L2, #post-content .prettyprint li.L3,
#post-content .prettyprint li.L4, #post-content .prettyprint li.L5,
#post-content .prettyprint li.L6, #post-content .prettyprint li.L7,
#post-content .prettyprint li.L8, #post-content .prettyprint li.L9 {
    padding-left: 0.8em;
}
```
最后请压缩`source/css/prettify.css`成`source/css/prettify.min.css即可。

@neoFelhz 请更新`source/css/prettify.css`和`source/css/prettify.min.css
fix(prettify): Auto add scrollbar instead of line feed
测试PC端和移动端通过<https://www.zhuxiongxian.cc/2017/06/17/Ubuntu1604-install-jdk8/>
