### ISSUE TITLE
这个主题能够解析latex吗

### ISSUE THREAD

**Issue by volcanoh** [viosey/hexo-theme-material#384]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [ ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

**Comment by volcanoh** [comment]
这个主题能够解析latex吗，如果不能，那可以通过其他方式解析吗？

**Comment by ghouzenyan** [comment]
支持 mathjax

**Comment by volcanoh** [comment]
是在_config.yml中添加mathjax: true 吗

**Comment by volcanoh** [comment]
@ghouzenyan  是在_config.yml中添加mathjax: true 吗
