### ISSUE TITLE
Wrong layout design of bottom of page

### ISSUE THREAD

**Issue by ghouzenyan** [viosey/hexo-theme-material#386]
**I certify that I have first consulted** (check all with "x")

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

---

There will be a blank to the right of the page when IE or Edge scrolls to the bottom.
Demo: https://blog.viosey.com/

![image](https://user-images.githubusercontent.com/8360126/27002448-4516d2bc-4e15-11e7-9a37-12df0d22a56f.png)

Also happens when the page is less than two articles on chrome with 100% zoom of 1920x1080 resolution.
Demo: https://blog.viosey.com/archives/2017/04/

Another place worthy of improvement is the footer is not always at the bottom of the page.
Demo: https://blog.viosey.com/archives/2017/06/

I think all above are caused by the wrong RWD.

**Comment by neoFelhz** [comment]
#376

**Comment by cubesky** [comment]
fixed #406

**Comment by neoFelhz** [comment]
fixed in version [1.5.0](https://github.com/viosey/hexo-theme-material/releases/tag/1.5.0)
