### ISSUE TITLE
Cannot read property 'use' of undefined

### ISSUE THREAD

**Issue by yajore** [viosey/hexo-theme-material#400]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

我按照hexo官网以及hexo Material Theme配置一步一步下去
当我执行 "hexo generate",
发生了一个错误 "Cannot read property 'use' of undefined"
```
Unhandled rejection TypeError: /root/home/src/blog/themes/material/layout/post.ejs:44
    42|                 <!-- Post Comments -->
    43|                 <% if(page.comment !== false) { %>
 >> 44|                     <%- partial('_partial/comment') %>
    45|                 <% } %>
    46|             </div>
    47| 
```
下面是我的配置
```
# Comment Systems
# Available value of "use":
#     disqus | disqus_click | changyan | 163gentie
comment:
    use: disqus
```
上面的问题是什么地方引起的,请指教

**Comment by zhengrz** [comment]
themes下那个主题hexo默认读取_config.yml,把那个模版yml改名就好啦，认真看下官网

**Comment by neoFelhz** [comment]
@zhengrz Yep!
