### ISSUE TITLE
添加多个独立页面报错

### ISSUE THREAD

**Issue by qiguoqiang** [viosey/hexo-theme-material#403]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

在配置文件中添加多个独立页面，配置如下
![image](https://user-images.githubusercontent.com/12483064/27368903-b6708168-5687-11e7-921c-3000b4d49b3e.png)
重新构建的时候报错
报错如下
![image](https://user-images.githubusercontent.com/12483064/27368918-ce6aeba0-5687-11e7-9af7-fff09cd4d32e.png)
去掉第二个独立页面，只保留第一个没有问题，将第一个的指向地址改为gallery也没有问题

**Comment by neoFelhz** [comment]
请尝试给 `相册` 带上双引号 `'相册'`，同时确保缩进的空格数量和位置都正常。

**Comment by qiguoqiang** [comment]
@neoFelhz 已解决，问题是此处添加的时候前面的缩进不能用tab来缩进，必须使用空格

**Comment by dansenpir** [comment]
@qiguoqiang
