### ISSUE TITLE
字体图标国内网络无法访问

### ISSUE THREAD

**Issue by qiguoqiang** [viosey/hexo-theme-material#407]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

在国内网络无法获取字体图标，翻墙正常
![image](https://user-images.githubusercontent.com/12483064/27383498-d7f2630c-56bd-11e7-95dd-db9c5684fb13.png)

**Comment by neoFelhz** [comment]
@qiguoqiang 主题内置了字体 host 设置功能，除了内置谷歌官方字体库、中科大反代字体库、360 爆米兔前端公共库意外，主题还支持自定义谷歌镜像字体库地址。
