### ISSUE TITLE
Isolation 模式下，图标icon引用地址似乎存在问题

### ISSUE THREAD

**Issue by TakWolf** [viosey/hexo-theme-material#408]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

# 正文 #

## 首页 ##

主题选择 Isolation，基本为文档的默认配置，没有开启cdn，图标icon不显示
首页是正常的：

![image](https://user-images.githubusercontent.com/6064962/27467411-d0dd254a-5814-11e7-950e-275a04799cc3.png)

![image](https://user-images.githubusercontent.com/6064962/27467464-46f5c976-5815-11e7-8ee9-9b09acd66841.png)

## 内部 ##

但是跳转到内部链接，引用地址貌似不正确？
![image](https://user-images.githubusercontent.com/6064962/27467424-ef2216c8-5814-11e7-9fcc-f977d33fb452.png)

404错误：
![image](https://user-images.githubusercontent.com/6064962/27467430-044c667a-5815-11e7-8bdf-63dfd9ac64b8.png)

相对路径的问题，这似乎是一个BUG?

**Comment by cubesky** [comment]
已经在即将发布的 `1.4.5` 版本中解决 #402

**Comment by neoFelhz** [comment]
fixed in version [1.5.0](https://github.com/viosey/hexo-theme-material/releases/tag/1.5.0)
