### ISSUE TITLE
标签云不显示

### ISSUE THREAD

**Issue by w4lle** [viosey/hexo-theme-material#41]
```
/source/tags
➜ tags git:(post) ✗>cat index.md
---
title: tags
date: 2016-01-29 14:10:01
type: "tags"
---
```

打开tags页面不显示标签呢

**Comment by viosey** [comment]
用法错误了。
请参考 [创建「标签云」页面](https://material.vss.im/compose/#创建「标签云」页面)

**Comment by kismet-cruz** [comment]
@w4lle 我遇到了跟你类似的问题。我打开timeline的页面却没有显示
![90](https://user-images.githubusercontent.com/22890026/32162050-970b62bc-bd92-11e7-8405-65a3ef62e5f8.png)
![89](https://user-images.githubusercontent.com/22890026/32162054-9aa6fcf6-bd92-11e7-8bdd-9e58d0b7db18.png)

**Comment by bobby285271** [comment]
@kismet-cruz 
按照 [hexo 的官方文档](https://hexo.io/docs/front-matter.html) 好像是要去掉第一行的 `---` 的... 不然偶尔会被识别为绘制横线，下面的就成正文部分了...

**Comment by kismet-cruz** [comment]
@bobby285271 
thanks. I think there is something wrong with the material docs. 它第一行有---的。
