### ISSUE TITLE
一个小小的bug

### ISSUE THREAD

**Issue by Yorathgz** [viosey/hexo-theme-material#411]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

如图，当打开侧边栏时，由于滑动条消失，导致博客背景整体向右轻微移动；关掉侧边栏时博客整体又向左移动回原状态。

![mark](http://oqp90iv18.bkt.clouddn.com/img/170624/Jmm9GefE3K.gif)

因为移动端没有滑动条，所以移动端没有这个问题；但是对于大多数PC用户常用的chrome、Microsoft Edge等浏览器都出现了该问题。

所以：**建议在打开侧边栏时，固定博客背景。**

我的思路：打开侧边栏的情况下，令博客背景可以滚动。

**Comment by Yorathgz** [comment]
可能是图片太小，演示不明显，但是在**电脑屏幕的大小下**，这个地方会显得很突兀 : (

**Comment by neoFelhz** [comment]
Just as I said. We won't fix it.

**Comment by neoFelhz** [comment]
Chrome has already used `Overlay Scrollbars` in Chrome 61. Just use it then avoid this problem

**Comment by Yorathgz** [comment]
已经使用 Version 61 ，问题没有得到解决，接着我在 os x 下的 safari 也发现了同样的问题，可以参考next主题，做出渐变移动的效果。

![](http://oqp90iv18.bkt.clouddn.com/img/170625/63dHbkcAiC.gif)

感谢您们提供如此美的主题，如果能把细节做好就更完美了。

**Comment by neoFelhz** [comment]
#90
