### ISSUE TITLE
请问如何添加顶部导航条？

### ISSUE THREAD

**Issue by lichnow** [viosey/hexo-theme-material#414]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

在移动端,用侧边栏很不错,但是在PC端点那个很容易被忽略的按钮拉出导航很容易被用户忽略而找不到需要的标签和分类,请问此主题可以添加顶部导航条吗？如何添加？

**Comment by neoFelhz** [comment]
目前不能。
