### ISSUE TITLE
关于集成评论系统的建议

### ISSUE THREAD

**Issue by BarryLiu1995** [viosey/hexo-theme-material#415]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

material主题集成的多说已被下架，disqus好像被墙，代理后也打不开，畅言需要备案，请问该怎么解决集成评论系统的问题，不知能否集成网易云跟帖

**Comment by neoFelhz** [comment]
网易云跟帖已经集成
