### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by arony-sky** [viosey/hexo-theme-material#419]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

![image](https://user-images.githubusercontent.com/16434647/27524293-4bae1ab0-5a66-11e7-9c1d-6ddae019d230.png)
这里生效的是Material.min.css里面的字体设置

![image](https://user-images.githubusercontent.com/16434647/27524314-7e9dc434-5a66-11e7-94ad-7734b156c12d.png)
这里生效的是主题设置里的字体设置

我觉得正文中那个应该要按主题设置的来吧？不知道是不是个bug

**Comment by neoFelhz** [comment]
@arony-sky Please add your own fonts' css at `head.yml`.
