### ISSUE TITLE
提 issue 之前请先阅读文档。Please read the Docs first.

### ISSUE THREAD

**Issue by viosey** [viosey/hexo-theme-material#42]
[material.viosey.com](https://material.viosey.com/)

**Comment by viosey** [comment]
[了解配置文件](https://material.vss.im/intro/#主题配置文件介绍)

**Comment by neoFelhz** [comment]
包括[Hexo 的官方文档](hexo.io/docs)！

**Comment by pidupuis** [comment]
@viosey This issue is not required anymore
