### ISSUE TITLE
该主题的 canary 分支在部署至子目录下时无法加载 css 等资源文件

### ISSUE THREAD

**Issue by bloodtox3710** [viosey/hexo-theme-material#420]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

使用的 hexo 版本为 1.0.3
这是站点配置文件与路径有关的部分
![image](https://user-images.githubusercontent.com/29591012/27571066-94910204-5b35-11e7-9133-c5fa2bf25e8f.png)
Console log.
![image](https://user-images.githubusercontent.com/29591012/27571109-d886c3e0-5b35-11e7-9e46-1b600a89c6da.png)
望迅速修复，谢谢。

**Comment by neoFelhz** [comment]
Already fixed in `canary` branch.
We will release a new version soon.

**Comment by bloodtox3710** [comment]
貌似路径问题并没有得到修复，我个人推测问题可能出在 lib 的 css_lsload.js 那里。
我通过查看 head.ejs 发现使用了 cssLsload 这个函数来加载 css ，这里使用了 config.root 来补全路径，可能您说的修复是指补全了路径，从 log 看出也确实是补全了，但不知为何子目录重复了一遍。
![image](https://user-images.githubusercontent.com/29591012/27750209-6792d58a-5e09-11e7-813a-eb211246ad92.png)
望您能看一下这个问题，谢谢。

**Comment by bloodtox3710** [comment]
Closed  by #423
