### ISSUE TITLE
来必力评论系统不显示

### ISSUE THREAD

**Issue by BarryLiu1995** [viosey/hexo-theme-material#421]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

Cancry分支下使用来必力评论系统
主题配置如下：
![default](https://user-images.githubusercontent.com/20590350/27624706-73be358a-5c14-11e7-838d-5603922ba949.jpg)
一开始生成部署的时候还会有提醒，但后面我重复几次生成部署后就没有了
![bug](https://user-images.githubusercontent.com/20590350/27624746-9f84fff0-5c14-11e7-923f-b0f6b8e04d22.jpg)

**Comment by neoFelhz** [comment]
Please give us the full log.

**Comment by neoFelhz** [comment]
oops... I know why.

**Comment by BarryLiu1995** [comment]
@neoFelhz 换成livere后文章内容变空白，而且来必力也没有起效果

**Comment by LiguangZhang** [comment]
博主配置出错了:
livere/main.ejs:

<div id="lv-container" data-id="city" data-uid="<%= theme.comment.livere_data_uid %>"></div>
<script type="text/javascript">
 (function(d, s) {
     var j, e = d.getElementsByTagName(s)[0];

     if (typeof LivereTower === 'function') { return; }

     j = d.createElement(s);
     j.src = 'https://cdn-city.livere.com/js/embed.dist.js';
     j.async = true;

     e.parentNode.insertBefore(j, e);
 })(document, 'script');
</script>

**Comment by LuckyXiang** [comment]
**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

----
1. 现在还支持 “来比力” 评论？
2. 还有怎么设置页面跳转时的链接协议，我希望链接是https的，但是在实际点击跳转中是http，这个如何解决？

这是我的配置文件的评论部分:
![default](https://user-images.githubusercontent.com/19492991/29878185-6cc494da-8dd4-11e7-85e5-824e79eabb21.png)
这是log:
![default](https://user-images.githubusercontent.com/19492991/29878157-5ac1d3e2-8dd4-11e7-8ec3-27db292bbd38.png)
