### ISSUE TITLE
When i use materialcdn feature, the 'back to top' FAB animation will missing.

### ISSUE THREAD

**Issue by go3k** [viosey/hexo-theme-material#422]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

I can confirm that the materialcdn feature works fine, but the 'back to top' FAB animation just missing, the FAB keeps in the right bottom corner of the page. I think it's a bug, waiting for your reply, thanks.

**Comment by neoFelhz** [comment]
It may be your css was cached by CDN server. Simply flush it at your CDN console and try it again.

**Comment by go3k** [comment]
... Yeah, you're right. It's my fault.
