### ISSUE TITLE
MarkDown 渲染错误

### ISSUE THREAD

**Issue by BarryLiu1995** [viosey/hexo-theme-material#424]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

在MarkDown编辑器写好博文后生成部署，最后却发现网页显示错乱，不知原因为何
![default](https://user-images.githubusercontent.com/20590350/27786473-d6e3b952-6013-11e7-91e2-eed6eb8e1fe4.jpg)

**Comment by neoFelhz** [comment]
请检查你的 markdown 原文是否带了 ` ``` ` 或者缩进，导致误判为代码块。
Hexo 默认使用 marked.js 进行解析。

**Comment by BarryLiu1995** [comment]
@neoFelhz 原文确实有```和缩进，但为啥在编辑器当中显示完好，难道是主题默认解析跟编辑器解析不同吗？

**Comment by neoFelhz** [comment]
@BarryLiu1995  Hexo 默认解析使用 marked,js 解析器解析 Markdown。

**Comment by cubesky** [comment]
@BarryLiu1995 在代码块和缩进之后多换一行试试

**Comment by BarryLiu1995** [comment]
@neoFelhz @cubesky 我严格按照GFM格式书写，现在也把缩进去掉，为啥还是代码块错乱显示
![1](https://user-images.githubusercontent.com/20590350/27822582-aa9cee84-60d8-11e7-9558-4837d7197d59.jpg)

**Comment by BarryLiu1995** [comment]
@neoFelhz @cubesky 现在我发现同样的语法，有些地方解析正确，有些地方解析错误
![2](https://user-images.githubusercontent.com/20590350/27833331-f435c0a8-6104-11e7-8491-217693f8e007.jpg)

**Comment by BarryLiu1995** [comment]
我明白了，行内代码块使用单个```
