### ISSUE TITLE
MathJax Error

### ISSUE THREAD

**Issue by qiankanglai** [viosey/hexo-theme-material#425]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

我发现在post里打开mathjax之后会有俩404

    mathjax.js?config=TeX-AMS-MML_HTMLorMML:19 GET http://127.0.0.1:4000/extensions/MathMenu.js?V=2.7.1 
    mathjax.js?config=TeX-AMS-MML_HTMLorMML:19 GET http://127.0.0.1:4000/extensions/MathZoom.js?V=2.7.1 

我debug了一下发现有两个地方有点问题
- MathJax.js的大小写必须这么干，不能全小写...因为这个js会在页面里搜索所有script标签，然后用`/(^|\/)MathJax\.js(\?.*)?$/`去匹配
- 这个库还有一堆config/fonts/jax文件没有导入进来

需要的话我可以弄个PR，但是这样会弄一堆小文件进来...

**Comment by ghouzenyan** [comment]
I think you meet the same issue like #283

**Comment by qiankanglai** [comment]
The same case but still unresolved with release 1.4.0
