### ISSUE TITLE
不知能否在footer中加入v2ex

### ISSUE THREAD

**Issue by hryg** [viosey/hexo-theme-material#428]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

**Comment by neoFelhz** [comment]
Please give us the icon of v2ex with svg format yourself, black background needed.
Our UI/UX designer has already escaped.

**Comment by hryg** [comment]
我回家尝试一下能不能做出来

**Comment by neoFelhz** [comment]
Finish it in version [1.5.0](https://github.com/viosey/hexo-theme-material/releases/tag/1.5.0)
