### ISSUE TITLE
Need to add a new feature of daily pic

### ISSUE THREAD

**Issue by kmahyyg** [viosey/hexo-theme-material#43]
Maybe you can add a Json parser to pull this json returned from the URL:

     http://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US             //(json)
     http://www.bing.com/HPImageArchive.aspx?format=rss&idx=0&n=1&mkt=en-US           //(xml)

Then check out the photo link in the json,automatically change the daily photo.
If you like this idea,please add it ASAP.

**Comment by kmahyyg** [comment]
Also , You can add email config in ./_config.yml in order to help one who use gravatar service to configure avatar.

More details please see API of GRavatar.
Its link format is

     https://www.gravatar.com/avatar/HASH.jpg

HASH should be replaced with:

 **md5 of your all lower cased email address**

Thanks a lot.

**Comment by viosey** [comment]
The gravatar function is somehow complex.
Besides the logic of the priority settings, there also need a javascript to generate a md5.
It is more convenience to custom the avatar by self.
I will provide a hash calculator in the Docs.

**Comment by kmahyyg** [comment]
Reply to F3: Okay,that's nice.
Reply to F2: Thanks a lot.And I think that you could offer some suggestions and color-related links in your docs to help one who enabled the  ' 'bing ' function ( background of the blog section).
And just re-use it in the daily-pic module is enough.

such as this: 

    bing:
        bg_enable: true
        daily_enable: true
        parameter_daily: type=N
        parameter_bg: new


that's enough.

Thank you again.

**Comment by kmahyyg** [comment]
Also, you must make sure that the photo in daily_pic and background should be different.

Please don't forget to notice user that GRAVATAR need a hash of *all-lower-cased email address*.

**Comment by BlenderViking** [comment]
The daily picture is an interesting request.

A solution to retrieve the json would be to use a public `JSONP Proxy service` like [yql](https://developer.yahoo.com/yql/) (provide by yahoo) for call the json retrieve directly in the JavaScript code like :
```js
    var url = '//query.yahooapis.com/v1/public/yql' + 
        '?q=' + encodeURIComponent('select * from json where url=@url') +
        '&url=' + encodeURIComponent('https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1') +
        '&format=json&callback=?';
    $.getJSON(url, function(result) {
        $('#daily_picture_container').css("background-image", "url(//www.bing.com" + result.query.results.json.images.url + ")");
    });
```

**Comment by kmahyyg** [comment]
Wow, there's someone who gave a solution.thanks to the last floor.

Another issues:

1.local search & rss didn't work,and also where's entrance?(isolation theme)
4.
2.maybe you could learn something from repo: forsigner/fexo .  Front-matter config need a big improvement.

3.Whaat!About-me Page isn't generated automatically?!(Ex-fexo-theme user)

compare the two:
https://kmaahyyg.github.io (revert back to fexo)
http://kmahyyg.coding.me (still material)

**Comment by BlenderViking** [comment]
I can help you for your first question, you can add these plugins in hexo :
- [search](https://github.com/PaicHyperionDev/hexo-generator-search) : But the config are set inside the _config.yml of material theme.
- [RSS (atom)](https://github.com/hexojs/hexo-generator-feed) The config can be set in the _config.yml in root of hexo (not in config file of theme).

**Comment by viosey** [comment]
[local search](https://material.vss.im/services/#本地搜索)
[RSS](https://material.vss.im/start/#RSS)
[pages](https://material.vss.im/intro/#pages)

**Comment by kmahyyg** [comment]
thanks to you all above.
i have to say that i ensure the config is correct and in the correct place.

2016年11月30日 09:23，"Viosey" <notifications@github.com>写道：
