### ISSUE TITLE
照pages的方法配置图标只能输入一个单词

### ISSUE THREAD

**Issue by siyuanlau** [viosey/hexo-theme-material#430]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

如果按照[pages](https://material.viosey.com/intro/#pages)的方法配置图标则会出现只能输入一个单词的问题。
例如，使用[rss feed](https://material.io/icons/#ic_rss_feed)时，会产生如下情况。
![2017-07-07 13-49-36屏幕截图.png](https://ooo.0o0.ooo/2017/07/07/595f21333f8a5.png)

**Comment by neoFelhz** [comment]
Try `rss_feed`
