### ISSUE TITLE
生成报错

### ISSUE THREAD

**Issue by ghostsf** [viosey/hexo-theme-material#434]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x ] support request | 请求技术支持

hexo g ，生成时报错：

![image](https://user-images.githubusercontent.com/9978816/28199315-43719612-6897-11e7-8950-5f72a90a5242.png)

**Comment by neoFelhz** [comment]
Please use Node 6.11 or newer.

**Comment by neoFelhz** [comment]
Also, please check if the `script` folder exists

**Comment by ghostsf** [comment]
OK.
I try Node 6.11.
It exists.

**Comment by ghostsf** [comment]
it worked,thanks!
