### ISSUE TITLE
使用报错

### ISSUE THREAD

**Issue by BigBigSeven** [viosey/hexo-theme-material#436]
默认的 _landscape_ 是正常的，但是一旦设置`theme: material`就会报错。大概是什么问题呢
![et1tx8 e188gg f6qpx 2m](https://user-images.githubusercontent.com/15307317/28358847-fb460de0-6ca2-11e7-8cfe-82c97238b138.png)

**Comment by xhusky** [comment]
仔细看一下文档：
`为防止造成冲突，主题以 _config.template.yml 文件取代 _config.yml 文件，用以参考配置。
需要手动将 material 文件夹中的 _config.template.yml 复制一份并重命名为 _config.yml`
