### ISSUE TITLE
必应图片不显示

### ISSUE THREAD

**Issue by ElderJames** [viosey/hexo-theme-material#446]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

我的设置在[这里](https://github.com/ElderJames/elderjames.github.io/blob/files/themes/material/_config.yml#L70)，前端页面能显示完整的url路径，直接访问是能跳转到图片地址的，但是主题没有请求背景图片并显示。

如果按文档的说明（也可能有歧义） type=: S 前端输出会显示[object]

**Comment by neoFelhz** [comment]
May fixed in #393 .

**Comment by ElderJames** [comment]
但是，type参数传了S但是没有不是宇宙的图片诶

**Comment by Halyul** [comment]
@ElderJames 估计是api没更新 如果真的没有 那就是上古遗留问题了

**Comment by neoFelhz** [comment]
@halyul The historical bug of Bing background has already solved. Currently issue is API.

**Comment by neoFelhz** [comment]
I will.update the API soon.

**Comment by boru626** [comment]
我还以为是我的设置问题 原来是api问题啊 我的也不显示

**Comment by neoFelhz** [comment]
fixed in version [1.5.0](https://github.com/viosey/hexo-theme-material/releases/tag/1.5.0)
