### ISSUE TITLE
请求新特性：自动抓取github followers到友情链接页面

### ISSUE THREAD

**Issue by ElderJames** [viosey/hexo-theme-material#447]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

把头像、昵称和链接抓取下来合并成友情链接页面，可以省去手动添加的麻烦 ：-）

**Comment by neoFelhz** [comment]
You can do it just by yourself.
You can run a robot on Travis CI or use ajax to start a request to GitHub API.
