### ISSUE TITLE
使用Nexus分支报错

### ISSUE THREAD

**Issue by ElderJames** [viosey/hexo-theme-material#448]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

错误信息：
```
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at <anonymous>:1:92903
    at <anonymous>:1:93124
    at Object.lsloader.runjs (localhost/:124)
    at localhost/:124
    at XMLHttpRequest.xhr.onreadystatechange (localhost/:124)
```
还是喜欢Nexus这种布局多一点，希望添加更多特性！

**Comment by neoFelhz** [comment]
Sorry about that, but *Nexus* Scheme is still under development.
