### ISSUE TITLE
[Typos / Doc] 创建时间轴页面的文档有错别字

### ISSUE THREAD

**Issue by rosuH** [viosey/hexo-theme-material#451]
**I certify that I have first consulted**

**我确认我已经查看了** 
- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a** 

**我正在申请** 

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

### 主题文档的【开始创作】>>【创建时间轴页面】 部分最后一行字写错了：
> 如果想添加「标签云」页面的入口，请参考 独立页面。

“ **标签云** ” -->  “ **时间轴** ”。

问题文档链接直达：[创建时间轴](https://material.viosey.com/compose/)

![c](https://user-images.githubusercontent.com/15865017/28615504-dde5156e-722b-11e7-8713-27edfd4686ab.png)

- - - - - 
// 会不会有点吹毛求疵...
P.S. 感谢带来这么出色的作品 Lol

**Comment by neoFelhz** [comment]
OK.got it.
Will fixed when the docs update.
