### ISSUE TITLE
建议：相册独立页面分相册显示功能

### ISSUE THREAD

**Issue by qiguoqiang** [viosey/hexo-theme-material#453]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

现在相册独立页面所有的图片都是在一个页面，建议增加里面区分相册显示的功能。

**Comment by neoFelhz** [comment]
Material 主题的图库不是专门为了展示图片而生的。我们建议使用专门的相册程序来存放图片。
