### ISSUE TITLE
更改hexo的root目录可能导致文件夹生成错误

### ISSUE THREAD

**Issue by INT-ZC** [viosey/hexo-theme-material#481]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

制作者您好，感谢您的付出！
我的网站是zc.int.xyz。可以看到存在一些问题
此问题并没有在使用hexo s预览时出现，
但在直接打开本地public文件夹中复现。

查看控制台后发现，应加载目录应为D:/hexo/web/articles，实际加载目录为D:/article。
将应加载目录下的css、js、img文件夹复制到实际加载目录后问题初步解决。
此时console状态如下（浏览器版本版本 ：Chrome 62.0.3180.0（正式版本）canary （64 位））：

index.html:54 Failed to load file:///D:/article/css/material.min.css?Z7a72R1E4SxzBKR/WGctOA==: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
lsloader.iocss @ index.html:54
index.html:54 Failed to load file:///D:/article/css/style.min.css?txqx9XtqXvKduoBrVEUmSA==: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
lsloader.iocss @ index.html:54
index.html:54 Failed to load file:///D:/article/js/jquery.min.js?qcusAULNeBksqffqUM2+Ig==: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
lsloader.iojs @ index.html:54
index.html:54 Uncaught TypeError: Cannot read property 'appendChild' of null
    at Object.lsloader.runjs (index.html:54)
    at Object.lsloader.jsfallback (index.html:54)
    at XMLHttpRequest.xhr.onreadystatechange (index.html:54)
    at Object.lsloader.iojs (index.html:54)
    at Object.lsloader.requestResource (index.html:54)
    at Object.lsloader.load (index.html:54)
    at index.html:223
index.html:54 Failed to load file:///D:/article/js/lazyload.min.js?1BcfzuNXqV+ntF6gq+5X3Q==: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
lsloader.iojs @ index.html:54
index.html:54 Failed to load file:///D:/article/js/js.min.js?ffyN6nCpcbPqRFNtUXcbbw==: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
lsloader.iojs @ index.html:54
index.html:54 Failed to load file:///D:/article/js/nprogress.js?pl3Qhb9lvqR1FlyLUna1Yw==: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

**Comment by cubesky** [comment]
请认真阅读 Hexo 文档
