### ISSUE TITLE
如果想在主页隐藏某些文章。

### ISSUE THREAD

**Issue by jskyzero** [viosey/hexo-theme-material#483]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

Material 原质 主题提供了很好的归档功能，但是出于若干需求，有时候可能不希望某些文章出现在首页（当然可以在文章的归档中找到它）因而建议增加一个隐藏在主页显示的设置。例如文章头中添加`visible: hide`即可以在主页隐藏这篇文章
Hexo的某主题的对应实现可以参考[这个](https://forwardkth.github.io/2016/05/08/next-theme-post-visibility/).  这里我们对应的找到`themes/layout/index.ejs` 然后将
```
            <% if(theme.scheme === 'Paradox') { %>
                <!-- Paradox Thumbnail -->
                <%- partial('_partial/Paradox-post_entry', { post: post, index: true }) %>
            <% } %>
            <% if(theme.scheme === 'Isolation') { %>
                <!-- Isolation Thumbnail -->
                <%- partial('_partial/Isolation-post_entry', { post: post, index: true }) %>
            <% } %>
```
修改为：
```
        <% if ( !( (post.visible === 'hide') && (page.path === "index.html") ) )   { %>
            <% if(theme.scheme === 'Paradox') { %>
                <!-- Paradox Thumbnail -->
                <%- partial('_partial/Paradox-post_entry', { post: post, index: true }) %>
            <% } %>
            <% if(theme.scheme === 'Isolation') { %>
                <!-- Isolation Thumbnail -->
                <%- partial('_partial/Isolation-post_entry', { post: post, index: true }) %>
            <% } %>
        <% } %>
```
即可。

只是增加了一个判断。

（希望主题越来越好w）

**Comment by neoFelhz** [comment]
We suggest you to create a new page instead of post, then it will not be shown in the archives.
