### ISSUE TITLE
不知道改到了什么，无法生成页面

### ISSUE THREAD

**Issue by hibetterheyj** [viosey/hexo-theme-material#485]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

不知道改到了什么，无法生成页面，请求支持，多谢！
以下是命令行报错

```
Unhandled rejection TypeError: F:\coding\blog_by_PhilHE\themes\material\layout\layout.ejs:42
    40|                     <%- partial('_partial/footer') %>
    41|
 >> 42|                     <%- partial('_partial/import_js') %>
    43|                 </main>
    44|             </div>
    45|         </body>

F:\coding\blog_by_PhilHE\themes\material\layout\_partial\import_js.ejs:36
    34|             var inputArea = document.querySelector('#search');
    35|             var getSearchFile = function() {
 >> 36|                 var path = '<%= config.search.path %>';
    37|                 searchFunc(path, 'search', 'local-search-result');
    38|             }
    39|

```

**Comment by cubesky** [comment]
看错误应该是你打开了 local 模式的搜索，但是没正常设置

**Comment by cubesky** [comment]
@cubesky 1

**Comment by hibetterheyj** [comment]
嗯嗯，我最后强行把主题配置文件重新配置了一遍，就弄好了。还有问一下 [toc] 生成目录为什么会自动生成序号呢？如果生成序号，正文中就得把自己所写的多级序号去掉，看起来有点奇怪。希望能够增加一个（是/否需要自动生成序号的功能）谢谢！

**Comment by cubesky** [comment]
@hibetterheyj 这个功能将在下个版本 1.5.0 中支持，现在的测试版本已经拥有这个功能了

**Comment by TidePeng** [comment]
同遇到这个问题，将主题配置文件中的local修改为google则解决，感谢~~  ；）
