### ISSUE TITLE
文章内容不显示了

### ISSUE THREAD

**Issue by JianingWang** [viosey/hexo-theme-material#490]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

首先感谢作者提供这么精致的作品. 我的问题是主页不显示每个文章, 但是鼠标可点击, 点击后的页面也是只显示头部, 文章内容不显示.

如下图

<img width="1071" alt="screen shot 2017-08-18 at 3 49 04 pm" src="https://user-images.githubusercontent.com/11001224/29450353-f6b5f966-8430-11e7-868c-908fe3dc7e8e.png">

<img width="1061" alt="screen shot 2017-08-18 at 3 49 27 pm" src="https://user-images.githubusercontent.com/11001224/29450405-281ad184-8431-11e7-838c-ba11db0e81f7.png">

另:

* `hexo g` 不报错, `hexo clean` 之后, 重新 `hexo g`, 还是这样.
* 更换其他主题, 如 next, 页面正常显示.

**Comment by cubesky** [comment]
看起来是你的某些资源没有成功加载，你可以尝试关闭 `js_effect` 中的 `fade`

**Comment by JianingWang** [comment]
我关闭之后确实管用了.

但是我想问, 问题出在哪里, 我之前用的时候没出问题. 

怎样才能在开启 `js_effect` 的状态下继续使用? 我挺喜欢这个渐显效果的. 谢谢

**Comment by cubesky** [comment]
@JianingWang 你可以在 fade: true 状态下打开 F12 控制台查看是否是 nprogressbar 的 js 加载没有成功

**Comment by JianingWang** [comment]
@cubesky 

控制台是这个样子的: 

<img width="923" alt="screen shot 2017-08-18 at 5 39 06 pm" src="https://user-images.githubusercontent.com/11001224/29453432-3bab3102-843c-11e7-946b-1473ddb8d8a8.png">

**Comment by cubesky** [comment]
@JianingWang 应该是 js 没有成功获取到，检查下你的 CDN 设置

**Comment by JianingWang** [comment]
@cubesky 我改动太多了, 重装了一下, 目前运行良好. 谢谢
