### ISSUE TITLE
如何切换国家文字，显示的不知道是哪国的语言？

### ISSUE THREAD

**Issue by iBotasky** [viosey/hexo-theme-material#497]
一开始用的是其他主题，切换成Material的时候一些固定的如`首页`、`阅读更多`等文字的语言不是中文，官方文档也找不到设置的地方！看了一下`.yml`文件也没有发现设置的地方。如图：
![wx20170826-204529](https://user-images.githubusercontent.com/13627665/29741460-ef188208-8a9f-11e7-866e-f16f93b1dea3.png)

**Comment by iBotasky** [comment]
@apisznasdin hello...........

**Comment by cubesky** [comment]
@iBotasky Please read Hexo Config to set language.

**Comment by neoFelhz** [comment]
We won't answer any issue unless your finish the questionnaire the issue provided.
