### ISSUE TITLE
设置随机图片没显示出来

### ISSUE THREAD

**Issue by iBotasky** [viosey/hexo-theme-material#498]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

按照文档的走：
1.在`/img/random/`文件夹下放入自己的图片，并命名为`random-`开头，17张
2.配置`_configu.yml`下面的`random_amount: 17`跟`random_thumbnail: "/img/random/random-"`

运行起来没有生效，
我放的图片是`jpg`格式，不是缩略图。不知道是什么原因导致的随机图没有生效，图片的大小基本上都在`500kb`一下！

@qiankanglai 求帮助

**Comment by neoFelhz** [comment]
Sorry, random images only support png format.

**Comment by iBotasky** [comment]
OK, thanks
Will this proble be solve in the future? 
@neoFelhz

**Comment by neoFelhz** [comment]
@iBotasky In fact, team is still discussing about whether remove random thumnail feature in the future orq not.

**Comment by iBotasky** [comment]
I try to change the image format to `png`, but it's not working too. The image's size is `1-2MB`, is there also have a limit for the image size?
I like the thumnail.
Don't do it. ToT
@neoFelhz

**Comment by neoFelhz** [comment]
@iBotasky You have changed the ｀random_amount` config, haven't you?

**Comment by iBotasky** [comment]
@neoFelhz 
Yeah, I check the `/img/random/` there are 17 images
and i set the `random_amount: 17` in the `_config.yml`

**Comment by iBotasky** [comment]
and the `random_thumbnail: "/img/random/random-"` is set in _config.yml.
My image is named with `random-`

**Comment by neoFelhz** [comment]
Emm, I might know.what happend.
When you setup `purecolor`, the random thumbnail will be.automatically disabled.
Try to remove the configuration of `purecolor` and try again?

**Comment by iBotasky** [comment]
= =Yeah . it's working . 
I think you should change the document.
there is not the point about this.
Whatever , Thanks for help @neoFelhz

**Comment by Helianus** [comment]
I have same issue. Even though I delete the "purecolor", it still displays pure blue color.
