### ISSUE TITLE
Categories function is't working 

### ISSUE THREAD

**Issue by iBotasky** [viosey/hexo-theme-material#499]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

@neoFelhz Hello again.
I got a problem about category function. 
I setup these code in the `_config.yml` :
`    categories:
        use: true
        icon: chrome_reader_mode
        divider: false`

and run in debug mode and the `category` is show in the sidebar menu, but there is not any categories show in here:
<img width="288" alt="wx20170827-135937 2x" src="https://user-images.githubusercontent.com/13627665/29747527-669f6be4-8b30-11e7-8ea4-dd8a58a3a853.png">

And i'm sure that mine archive is setup the `tags` in MarkDown files.like this:
```
title: Java内存区域与Java垃圾回收
date: 2017-02-04 14:25:49
tags: [Java基础]
```

So how can I solve this problem?

**Comment by neoFelhz** [comment]
Categories has its own front-matter.

**Comment by iBotasky** [comment]
@neoFelhz I don't under stand. Is there a document?

**Comment by neoFelhz** [comment]
@iBotasky I don't think you have read the hexo docunmentions at all.

**Comment by iBotasky** [comment]
@neoFelhz I got it, it's `categories ` but not `tags`! 
Thanks !
