### ISSUE TITLE
c++的代码高亮好像有点问题啊

### ISSUE THREAD

**Issue by LucidaLu** [viosey/hexo-theme-material#50]
主题使用的时候，发现在c++代码中如果出现了#include字样，渲染就会有问题。研究了好久也无果，也尝试改变高亮风格也没用。
[link](https://lucidalu.github.io/2016/10/10/BZOJ3110/)

**Comment by viosey** [comment]
got it，具体解决方式还是很清楚。

**Comment by pangjian** [comment]
好像除了c++,很多高亮的时候都会有问题，在iOS上渲染字体会变大

**Comment by leonlibraries** [comment]
目前已知 Java、JavaScript的代码高亮都有问题，望解决，谢谢

**Comment by Halyul** [comment]
@leonlibraries 已经修复地差不多了，下个版本发布时应该不再会有这个问题

**Comment by cubesky** [comment]
已在 `1.3.0` 修复
