### ISSUE TITLE
畅言评论系统需要备案

### ISSUE THREAD

**Issue by yinhaojun** [viosey/hexo-theme-material#507]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x ] support request | 请求技术支持

Disqus好像需要翻墙才能用，然后我的博客是托管到github的，畅言评论系统提示需要备案，这该如何处理呢？

**Comment by cubesky** [comment]
@yinhaojun 请您自己权衡使用各个评论系统的利弊
我们只提供评论系统的嵌入，您如何使用评论系统与本主题无关
请询问评论系统提供商以获得解决方案

**Comment by neoFelhz** [comment]
我们主题**的兼容 `来必力` `Valine` `gitment` 等等不属于你国的评论系统，你都**的看不见文档和代码提交记录吗？
没法用 `友言` 又和我们主题没关系，找你国有关部门去。你国有关部门说了，你国的互联网是 `公开，平等，有序` 的。
