### ISSUE TITLE
友链出错了，，，):

### ISSUE THREAD

**Issue by OnlyTO** [viosey/hexo-theme-material#510]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

您好!我在添加友链的时候除了点问题，在点击友情链接后，一直出现：`Cannot GET /function%20link()%20%7B%20%5Bnative%20code%5D%20%7D/`,一下是配置文件中写的东西。
```yml
     pages:

        友情链接: "/links/"

        时间轴归档: "/timeline/"`

```
```
---
title: links

date:

layout: links
---
```

```
"xxx":

    link: xxx

    avatar:

    descr: "xxx" 
```

但是单独访问 "localhost:4000/links",又能看到添加的友链。

**Comment by neoFelhz** [comment]
Give more information about your dictionaries

**Comment by OnlyTO** [comment]
![5](https://user-images.githubusercontent.com/31723022/30282845-099a1d2a-9749-11e7-871b-7b9ff6ead182.png)

![4](https://user-images.githubusercontent.com/31723022/30282840-06b1a22c-9749-11e7-8ef3-b7f6ee3a0d71.png)

![3](https://user-images.githubusercontent.com/31723022/30282837-046141da-9749-11e7-88c0-6c7a647413e5.png)
![1](https://user-images.githubusercontent.com/31723022/30282825-00d822ae-9749-11e7-8ccb-a597c0b24e2b.png)

**Comment by neoFelhz** [comment]
Emmm...
Your configuration of `pages` are wrong . . .
We gave you a example below, as the annotated one.

**Comment by OnlyTO** [comment]
yeah! I make it, I used to refer to this picture to revised the configuration file . So the page of link is wrong. Thank you so much.
![6](https://user-images.githubusercontent.com/31723022/30311450-d3cd3a72-97c7-11e7-8f80-b2a42de73f67.png)
