### ISSUE TITLE
请问怎么添加about页面？

### ISSUE THREAD

**Issue by xtz1990** [viosey/hexo-theme-material#512]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

**Comment by cubesky** [comment]
@xtz1990 请认真阅读主题帮助文档

**Comment by neoFelhz** [comment]
我知道你根本没有阅读文档。
所以本人锁定了这个 issue，禁止你再在本条 issue 下回复。
