### ISSUE TITLE
请求技术支持

### ISSUE THREAD

**Issue by locustbaby** [viosey/hexo-theme-material#513]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

为什么默认安装后，左面侧边栏的语言是这样的
![hexo](https://user-images.githubusercontent.com/21237232/30441122-1014afbc-99ab-11e7-9f42-70bdfe7b9310.png)
这个是在哪设置的，然后 想做成 https://blog.viosey.com/ 这个效果 是怎么改动的
如果 有文档可以告诉我在哪看这么详细的
我看过Material主题文档，讲了很多配置，但是 好像没有这么详细的

如果方便，是否有别的联系方式，类似邮箱 or 微信

**Comment by cubesky** [comment]
@locustbaby 请认真阅读 Hexo 配置文档 和 Material 配置文档
