### ISSUE TITLE
无法用valine评论

### ISSUE THREAD

**Issue by butwedo** [viosey/hexo-theme-material#515]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

您好！
在使用你的主题过程中，我打算使用valine的评论，然而发现我修改了appid和key并且把use设成valine后仍无法显示评论。若直接修改post.ejs的话最多支持到1.1.3，更新的版本能够显示评论但无法发表。求解决。

**Comment by neoFelhz** [comment]
@butwedo 请直接联系 Valine 开发者获取技术支持。
