### ISSUE TITLE
请问如何修改才能去除文章中链接的下划线呢？

### ISSUE THREAD

**Issue by LJ147** [viosey/hexo-theme-material#517]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

你好，我的[网站](hellogod.cn)我希望能够去除图中链接中的下划线，请问该如何修改呢？

是修改CSS还是修改render呢？

先表示感谢！
![Uploading QQ20170918-025944.png…]()

**Comment by neoFelhz** [comment]
If you are not using Material theme, please **DO NOT** ask us for *ANY* support request.

@iissnan It is your business.
