### ISSUE TITLE
我遇到了一个很奇怪的error

### ISSUE THREAD

**Issue by crown3** [viosey/hexo-theme-material#519]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

![jietu20170918-132533](https://user-images.githubusercontent.com/19649900/30529941-1a56919e-9c75-11e7-9b3e-6e26c2c236f4.png)

这个错误你们遇到过吗?我不确定它是由什么引起的的?

**Comment by cubesky** [comment]
@crown3 检查你浏览器的广告过滤器

**Comment by crown3** [comment]
@cubesky 谢谢指点!这个问题可以关闭了
