### ISSUE TITLE
Feature Request: TOC 独立禁用选项

### ISSUE THREAD

**Issue by neoFelhz** [viosey/hexo-theme-material#52]
希望可以在 Front-matter 里加入 TOC 是否禁用的设置。
默认 TOC 是启用的，也可以人为设置 `TOC: false`

> 友情链接页面、标签云等一些独立页面，以及一些文章不需要 TOC。

**Comment by viosey** [comment]
TOC 禁用选项已添加。
但对于友情链接等页面似乎无法使用，之后会对这些独立页面进行过滤
