### ISSUE TITLE
映像页面在MBP的Safari浏览器中样式失效

### ISSUE THREAD

**Issue by pengfeigao** [viosey/hexo-theme-material#520]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

映像页面在MBP的Safari浏览器中样式失效，包括您的个人blog也是

**Comment by neoFelhz** [comment]
Update your MacOS and use the newest Safari.

**Comment by pengfeigao** [comment]
<img width="1238" alt="2017-09-21 1 04 51" src="https://user-images.githubusercontent.com/9261499/30657129-0d8082ae-9e69-11e7-9ad7-7710bc882ae6.png">
This is my Safari version and update log.Your MBP has not this error?Your Safari version is this?

**Comment by pengfeigao** [comment]
![2017-09-21 1 08 00](https://user-images.githubusercontent.com/9261499/30657201-57a8ea1a-9e69-11e7-8db5-2ff72f319fec.png)
My MBP Configration!
