### ISSUE TITLE
当预览中有用到LaTeX时无法正确渲染

### ISSUE THREAD

**Issue by dragonJACson** [viosey/hexo-theme-material#529]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

![image](https://user-images.githubusercontent.com/13308034/30872863-17c7e580-a2b1-11e7-9c56-4f02bb162826.png)
![image](https://user-images.githubusercontent.com/13308034/30872889-2951fad4-a2b1-11e7-9ffd-2a76cd7f5cbf.png)
如图所示

**Comment by hibetterheyj** [comment]
我是全文都不能渲染。除了在**Front-matter**处添加`mathJax: true`，还需要注意什么嘛？求教

**Comment by dragonJACson** [comment]
@hibetterheyj 有在 `_config.yml` 中的 `vendors: ` `mathjax: ` 里面加上 pubilc cdn 的链接吗？

**Comment by hibetterheyj** [comment]
添加了一个*MathJax*的cdn
```
    # MathJax 2.7.0-2.7.1
    mathjax: http://mathjax.josephjctang.com/MathJax.js?config=TeX-MML-AM_HTMLorMML
```
或
```
    mathjax: http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
```
似乎都没用 @dragonJACson

**Comment by dragonJACson** [comment]
@hibetterheyj 把 `MathJax.js` 后面的部分去掉试试？

**Comment by hibetterheyj** [comment]
@neoFelhz 我似乎也遇到了这个问题

**Comment by huangjj27** [comment]
同样的问题. 在页面控制台里面, 确认已经注入了`MathJax`: 
![image](https://user-images.githubusercontent.com/8068443/31124331-a684f0e0-a876-11e7-82d8-743c038c9e68.png)

但是就是没有预览效果:
![image](https://user-images.githubusercontent.com/8068443/31124355-b9d213f8-a876-11e7-8e0e-55e2e92cf41d.png)

**Comment by huangjj27** [comment]
:100: 渲染问题解决了!
解决无法渲染的方法是:
在`Font-matter`中加入`mathjax: true`, 注意需要纯小写,

而配置没有生效的问题仍然没有解决. 附上渲染后的效果图~
![image](https://user-images.githubusercontent.com/8068443/31124922-10a339da-a879-11e7-9554-0b8525bf6252.png)

**Comment by dragonJACson** [comment]
@huangjj27 你在主页浏览文章摘要时，MathJax是否生效呢

**Comment by huangjj27** [comment]
@dragonJACson 不生效, 在 #278  中已经讨论过`material`主题的摘要不支持`MathJax`甚至`Markdown`样式的问题.

**Comment by dragonJACson** [comment]
@huangjj27 好的，谢谢告知。 @neoFelhz 可以关闭该 issue 了，抱歉，打扰了
