### ISSUE TITLE
关于logo图片问题

### ISSUE THREAD

**Issue by wesleylzw** [viosey/hexo-theme-material#536]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x ] support request | 请求技术支持

作者你好，我想修改logo图，但是无论换成什么图，都无法去掉白边，请求解决办法，谢谢！
![default](https://user-images.githubusercontent.com/32089024/31021290-f6694c9e-a567-11e7-8cfb-46051968b832.PNG)

**Comment by neoFelhz** [comment]
You should modify your logo.
It is not the theme's business

**Comment by neoFelhz** [comment]
It's area for logo, not for a picture.
