### ISSUE TITLE
disqus_click 失效

### ISSUE THREAD

**Issue by OYE93** [viosey/hexo-theme-material#537]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

你好，主题升级之后，disqus_click功能失效，我按照之前的设置评论为disqus_click，但是评论会自动出现，而不是点击出现

**Comment by neoFelhz** [comment]
`Disqus_click` is now able to check the visitors' network status. As the vistor can connect disqus normally, the disqus will load comment automatically.
