### ISSUE TITLE
Docs bug: 主题配置->菜单设定->hompage位置出错

### ISSUE THREAD

**Issue by huangjj27** [viosey/hexo-theme-material#539]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

![image](https://user-images.githubusercontent.com/8068443/31082486-b8a1108e-a7c1-11e7-87c2-ae6c58f731f1.png)
如图所示, 在阅读该主题的文档时, 发现[这里](https://material.viosey.com/docs/#/config/menu)的homepage应为下一个配置项的标题, 不应出现在引用部分中.

**Comment by cubesky** [comment]
@huangjj27 在引用后面多换行一次

**Comment by cubesky** [comment]
@huangjj27 这是 Hexo 渲染器的事

**Comment by huangjj27** [comment]
亲~ 我这个是发现你们[文档](https://material.viosey.com/docs/#/config/menu)中的渲染问题呀~

浏览器: chrome Version 61.0.3163.100 (Official Build) (64-bit)
OS: Ubuntu mate 16.04.3 LTS

**Comment by cubesky** [comment]
@huangjj27 啊呀…… @neoFelhz 出来改文档啦！

**Comment by neoFelhz** [comment]
@cubesky Roger that.
