### ISSUE TITLE
npm install hexo-deployer-git --save报错没有权限

### ISSUE THREAD

**Issue by Mr-houzi** [viosey/hexo-theme-material#540]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

--------------------------------------
npm install hexo-deployer-git --save报错没有权限
提示\node_modules\fsevents\node_modules\aproba\index.js此文件没有访问权限
用管理员权限访问后依然没有权限
请问如何解决 这步操作不了，就没法hexo deploy
--------------------------------------
报错源代码

$ npm install hexo-deployer-git --save
npm ERR! path D:\HouziPlanet\HouziPlanet.github.io\node_modules\fsevents\node_modules\aproba\index.js
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'D:\HouziPlanet\HouziPlanet.github.io\node_modules\fsevents\node_modules\aproba\index.js'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'D:\HouziPlanet\HouziPlanet.github.io\node_modules\fsevents\node_modules\aproba\index.js'
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'D:\\HouziPlanet\\HouziPlanet.github.io\\node_modules\\fsevents\\node_modules\\aproba\\index.js\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'D:\\HouziPlanet\\HouziPlanet.github.io\\node_modules\\fsevents\\node_modules\\aproba\\index.js' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     `C:\Users\hasee-pc\AppData\Roaming\npm-cache\_logs\2017-10-03T03_23_29_758Z-debug.log

**Comment by huangjj27** [comment]
请提供相应的hexo配置文件`_config.yml`, 谢谢!

**Comment by Mr-houzi** [comment]
问题已解决了

**Comment by sunweiguo** [comment]
可以说一下如何解决的吗

**Comment by 2631478675** [comment]
怎么解决的？
