### ISSUE TITLE
bug(docs): 捐赠途径QR Code 404

### ISSUE THREAD

**Issue by huangjj27** [viosey/hexo-theme-material#542]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

![image](https://user-images.githubusercontent.com/8068443/31131044-a44746e2-a88b-11e7-8ef4-9caa3691a240.png)
如上图所示, 这些捐赠渠道404了

**Comment by neoFelhz** [comment]
Already fixed in `nightly` build of the docs, but the realease version of docs hasn't deploy yet.
