### ISSUE TITLE
feature request: 新增gittalk评论插件的支持

### ISSUE THREAD

**Issue by huangjj27** [viosey/hexo-theme-material#547]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

因为[gitment作者好像弃坑](https://github.com/imsun/gitment/issues/71#issuecomment-328752634)了, 然后发现有一个类似的 [gittalk](https://github.com/gitalk/gitalk), 所以请求主题进行支持~

**Comment by bobby285271** [comment]
同求...

**Comment by ElderJames** [comment]
这个不错，我试试加入，gitment也是我加入的

**Comment by ElderJames** [comment]
已提交pr #554 ，可到我的博客预览效果 https://yangshunjie.com/influxdb-in-dotNEt-Core-2-ioc-and-repository-pattern.html
