### ISSUE TITLE
请求优化友链站点图像(矩形)显示效果

### ISSUE THREAD

**Issue by WoadZS** [viosey/hexo-theme-material#553]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

主题 Material Isolation 
版本 1.5

问题所在：友链独立页面
问题描述：友链各站点图标是以 `width` 为基准设置的 `72 px`
这会造成高比宽小的矩形图片显示效果不佳。

举例：
以@neoFelhz 的友链 Avatar 图像为例：
![](https://i.v2ex.co/Q4661K0b.png)
原图大小 275*256 px, 非正方形图标
在默认设置下，此图片的相关 HTML 代码为：
``` HTML
<img src="https://i.v2ex.co/Q4661K0b.png" alt="neoFelhz" width="72px">
```
显示效果是：
![_20171015125406](https://user-images.githubusercontent.com/18167899/31587028-faafc5de-b1a7-11e7-8b00-a0c4ed7fb236.png)
图片下部有残缺，但将代码中的 `width` 更改为 `height`, 以图像高度作为基准，显示效果就正常了:
``` HTML
<img src="https://i.v2ex.co/Q4661K0b.png" alt="neoFelhz" height="72px">
```
![_20171015125720](https://user-images.githubusercontent.com/18167899/31587050-6fadc192-b1a8-11e7-96fc-f3630a11ff80.png)

**Comment by neoFelhz** [comment]
I will check it.

**Comment by neoFelhz** [comment]
Emmm, it is caused by the avatar is not square.
