### ISSUE TITLE
Valine评论系统的main.ejs文件提供函数参数与官方readme文件中示例用法参数个数不符。

### ISSUE THREAD

**Issue by Jinxiapu** [viosey/hexo-theme-material#555]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

Valine评论系统作者好像增加几个了new 一个Valine对象时的[参数](https://github.com/xCss/Valine/blob/master/README.md#options)，与主题中默认valine的[代码](https://github.com/viosey/hexo-theme-material/blob/master/layout/_widget/comment/valine/main.ejs)不同。
目前发现博客生成的页面没有评论框出现，但是利用valine提供的demo文件测试有评论框出现，因为不太懂前端，不懂是哪里的原因。

**Comment by neoFelhz** [comment]
The `Valine` theme built in is an old version.

**Comment by neoFelhz** [comment]
The developer of `Valine` has helped us update the version. See #558.

**Comment by xCss** [comment]
@Jinxiapu `Valine`实例化对象的时候，除了`el`/`app_id`/`app_key`三个**必要属性**，其他都是可有可无并带有`默认值`的。
