### ISSUE TITLE
为什么上传主题会提示缺少样式表

### ISSUE THREAD

**Issue by daisyboy** [viosey/hexo-theme-material#557]
正在解压缩安装包…

正在安装主题…

无法安装这个包。 主题缺少style.css样式表。

主题安装失败。

**Comment by ysc3839** [comment]
请描述清楚，你是上传到哪？怎么个安装？

**Comment by WoadZS** [comment]
这个不是 `WordPress` 主题，这个是 `hexo` 主题，@daisyboy 你是不是误会了什么
