### ISSUE TITLE
generate several pages

### ISSUE THREAD

**Issue by kismet-cruz** [viosey/hexo-theme-material#567]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

When generating several pages, error happens
我格式哪里写错了吗？

![93](https://user-images.githubusercontent.com/22890026/32228050-19967c62-be88-11e7-89e3-a16590fb0f3f.png)
![94](https://user-images.githubusercontent.com/22890026/32228051-19cd03f4-be88-11e7-81fa-ef2c630962a1.png)

**Comment by bobby285271** [comment]
估计是空格的问题...

**Comment by kismet-cruz** [comment]
吓的我也不敢用tab缩进了。哈哈。
谢谢了，最近已经回答了我两个问题了
