### ISSUE TITLE
_config.yml in .gitignore(MAY CAUSE Unhandled rejection TypeError )

### ISSUE THREAD

**Issue by vivian27** [viosey/hexo-theme-material#570]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

主题中默认的 .gitignore 文件中包含了 _config.yml 文件；因此将主题 clone 到本地后直接修改重命名是无法直接 push 到远程服务器上的，我看了其他的 issue 可能也是这个原因导致的。希望您修改 gitignore 以排除这种情况或在文档中提示一下这个问题的可能性，谢谢。

**Comment by neoFelhz** [comment]
We have already add information in about it in canary branch.
When we realeasenext version, those infomation will be shown in README.md.
https://github.com/viosey/hexo-theme-material/blob/canary/README.md
