### ISSUE TITLE
建议在文章详情页添加回到主页按钮

### ISSUE THREAD

**Issue by imoyao** [viosey/hexo-theme-material#572]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

**Comment by imoyao** [comment]
[示意图](http://oh6j8wijn.bkt.clouddn.com/sp20171119_191303.png)
另外是否有考虑暗色调的代码高亮方案？或者说主题默认方案中存在可配置项？

**Comment by cubesky** [comment]
@imoyao 代码高亮方案可以使用主题内建的或者使用 prism.js 染色插件

**Comment by neoFelhz** [comment]
1. “首页”按钮位于抽屉，默认配置为第一项。
2. 请告知你所使用的代码高亮选项。

**Comment by imoyao** [comment]
@neoFelhz  你好，我知道抽屉里面有这个按钮，但是再阅读页面回到首页属于高频操作，是否直接展示较好？

**Comment by imoyao** [comment]
各位，目前使用高亮方案为：
```
prettify:
  enable: true
  theme: "vibrant-ink" # default value: "vibrant-ink"   # theme-name without '.css'
```
