### ISSUE TITLE
数学公式再本地可以正常显示，上传到github.io上无法显示

### ISSUE THREAD

**Issue by zuoxiang95** [viosey/hexo-theme-material#574]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

您好，我想请问一下，我再编写博客时，在markdown文件头添加了：
mathJax: true
在我本地测试 hexo s登录到localhost:4000上可以看到数学公式正确显示了。但是我上传到github.io上之后无法正确显示出来？这是我有什么配置项没有配置好么？

**Comment by zuoxiang95** [comment]
我修改成mathjax: true了，在localhost:4000上无法显示，上传到github上也是无法正确显示

**Comment by StevenShiChina** [comment]
我这也不能显示公式

**Comment by StevenShiChina** [comment]
找到一种解决方法，需要在文章的开始插入以下代码：
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
tex2jax: {inlineMath: [['$','$'],['\\(','\\)']]}
});
</script>
<script type="text/javascript" async
 src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML">
</script>

**Comment by zuoxiang95** [comment]
@StevenShiChina 我的这个还是不行诶。能麻烦你把你的config文件传给我看一下么。

**Comment by StevenShiChina** [comment]
我还没彻底换这个主题，就是上面那段代码贴到你的需要插入公式的 markdown 文件中即可，后续我也折腾一下，共勉

**Comment by zuoxiang95** [comment]
问题找到了，需要在配置文件的mathjax设置为 https://cdn.bootcss.com/mathjax/2.7.0/MathJax.js 。之后在md文件中设置mathjax: true即可！

**Comment by EtoDemerzel0427** [comment]
请问你使用的material版本是1.5么？
我在1.4版本的主题配置文件中没有找到`mathjax`.

**Comment by hanspond** [comment]
类似问题，**在localhost:4000上正常**显示，上传到github上却无法正确显示

已经尝试了md文件独立插入代码，
还有配置主题添加
```
mathjax: 
        enable: true
```
和总体配置的yml添加
```
math:
  engine: 'mathjax' # or 'katex'
  mathjax:
    src: "https://cdn.bootcss.com/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML" #custom_mathjax_source
    config:
```

GitHub上面就是不渲染
