### ISSUE TITLE
设置了略缩图，但主页不会显示

### ISSUE THREAD

**Issue by bfdyanshe** [viosey/hexo-theme-material#576]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

设置了略缩图，但主页不会显示。查看页面元素能看到设置的略缩图的文件名，但就是不显示，只有纯色。点开文章能看到略缩图。

**Comment by neoFelhz** [comment]
console log.

**Comment by neoFelhz** [comment]
#498

**Comment by bfdyanshe** [comment]
Thank you
