### ISSUE TITLE
创建友情链接入口问题

### ISSUE THREAD

**Issue by NimaQu** [viosey/hexo-theme-material#579]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

![5ra941sdss 88 zabe9d](https://user-images.githubusercontent.com/26685881/33731903-94735118-dbbf-11e7-9c83-cc4432051987.png)
创建的友情链接入口打开是这样子，帮助文档里创建独立页面的链接打开404
![1fgb5vi khgzq asn 4ll2](https://user-images.githubusercontent.com/26685881/33731968-d56ec83c-dbbf-11e7-912c-c090ea6a6826.png)
![iv 3 tnnhyp8o7 e46lht l](https://user-images.githubusercontent.com/26685881/33732004-f03fb6bc-dbbf-11e7-90a3-2cea2f93d1da.png)

**Comment by ElderJames** [comment]
文档上已经有说了，具体[看这里](https://material.viosey.com/docs/#/pages?id=%e5%88%9b%e5%bb%ba%e3%80%8c%e5%8f%8b%e6%83%85%e9%93%be%e6%8e%a5%e3%80%8d%e9%a1%b5%e9%9d%a2)

> 在 hexo 目录下的 source 文件夹内创建一个名为 links（只是建议，可根据自己喜好修改）的文件夹。
>然后在文件内创建一个名为 index.md 的 Markdown 文件。

**Comment by NimaQu** [comment]
已经按文档创建写入了，可是打开就是图上那个样子

**Comment by ElderJames** [comment]
我博客这样配置是没问题的
https://raw.githubusercontent.com/ElderJames/elderjames.github.io/files/source/friends/index.md

**Comment by NimaQu** [comment]
之前没注意。。我以为是主题文件夹的source，按文档操作以后本地调试就打不开了，这样报错
![ky_ br vh4 _ _m5e73a](https://user-images.githubusercontent.com/26685881/33869017-81ababcc-df41-11e7-90c4-4a31a9209377.png)
这是两个文件夹里的文件
![o_l 7w qk f 8v of9o e](https://user-images.githubusercontent.com/26685881/33869032-a2d51090-df41-11e7-8180-5715db31144c.png)
![b o a22 fe__hbl5vc_o](https://user-images.githubusercontent.com/26685881/33869041-b2145700-df41-11e7-9e20-ea17eb5e831c.png)

**Comment by NimaQu** [comment]
![image](https://user-images.githubusercontent.com/26685881/34028251-a489057e-e19c-11e7-98e3-f4b565abff6e.png)
唯一觉得有问题的就是这里了。。文档上没有说清楚name指的是什么。。。。。
![image](https://user-images.githubusercontent.com/26685881/34028344-58ccc14c-e19d-11e7-80b1-b3315563d83b.png)

**Comment by automano** [comment]
对于你上面这个例子， About就是这个独立页面的名字。叫什么名字不重要，重要的是页面的link需要配置正确。

**Comment by automano** [comment]
注意。不论对配置做任何修改, 请先运行hexo clean，再做其他调试。

**Comment by NimaQu** [comment]
谢谢，hexo clean以后问题解决了
