### ISSUE TITLE
java代码高亮有问题

### ISSUE THREAD

**Issue by heinika** [viosey/hexo-theme-material#58]
java代码高亮，后面的代码全是注释状态。。。
应该是不识别单行注释：//

**Comment by co2y** [comment]
同样问题

**Comment by viosey** [comment]
代码高亮调用的是 [highlight.js](https://highlightjs.org/)
我也发现了在其他语言下的一些问题。
但导致该 bug 的具体原因还不明。

**Comment by trumi** [comment]
显示@Override错位了，夹在了两行之间

**Comment by heinika** [comment]
能不能优先解决代码高亮问题，这个严重影响程序员使用。

**Comment by TheNetAdmin** [comment]
能否改用prism来高亮呢，这里有个插件![Hexo-Prism-Plugin](https://github.com/ele828/hexo-prism-plugin)，但是即使安装并设置了这个插件也不能改变material主题调用hilight.js的设置

**Comment by cubesky** [comment]
@TheNetAdmin 谢谢您的反馈，我们已经发现了很多高亮问题，正准备改为使用 prism 插件，请等待一段时间

**Comment by AnCorleone** [comment]
http://jiji262.github.io/2016/04/15/2016-04-15-hexo-github-pages-blog/  可以把代码高亮做成这样的吗，这个主题是yilia，代码显示的太差了，感谢！

**Comment by marktony** [comment]
好像对注解的支持也不是太好，@Override 注解直接飘到了每一行的开始

**Comment by neoFelhz** [comment]
@marktony 会一并修复。

**Comment by cubesky** [comment]
已在 `1.3.0` 修复
