### ISSUE TITLE
跳转地址错误

### ISSUE THREAD

**Issue by Mashiroiswife** [viosey/hexo-theme-material#580]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

![snipaste_2017-12-15_11-41-50](https://user-images.githubusercontent.com/28353930/34025849-33411abe-e18d-11e7-8da8-a0926aa2995f.png)
![snipaste_2017-12-15_11-42-06](https://user-images.githubusercontent.com/28353930/34025850-338210fa-e18d-11e7-9202-3a2107d593e8.png)
当我写完一篇文档并push之后，每一个文档界面都会对应添加当前当前网页地址到每一个网页属性上，导致缩略图以及跳转地址错误，请问我是哪里配置错误了？
![snipaste_2017-12-15_11-47-27](https://user-images.githubusercontent.com/28353930/34025949-bf17a634-e18d-11e7-8572-f88da0436a7f.png)

**Comment by automano** [comment]
大概是因为你的站点配置文件出了错。查看一下URL中 url和root的配置是否正确。

**Comment by Mashiroiswife** [comment]
URL: #域名？
root：#仓库名？

**Comment by Mashiroiswife** [comment]
问题已解决，感谢

**Comment by Leezj9671** [comment]
遇到了同样的问题，站点配置文件为
 ```yml
url: http://yoursite.com
root: /
 ```
不知道如何解决
