### ISSUE TITLE
如果不想刷新时更换背景，该去哪里设置成固定背景呢

### ISSUE THREAD

**Issue by wjx0908** [viosey/hexo-theme-material#581]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

**Comment by ysc3839** [comment]
https://github.com/viosey/hexo-theme-material/blob/6fd8fe99d5ad69ac41b82e1bed947e2ddeca58c3/_config.template.yml#L57
改成 1，然后背景文件名改为 `material-1.png`。

**Comment by bazingajunxiang** [comment]
这样不就是所有图片都是一样的了吗0.0

**Comment by wjx0908** [comment]
可能问的有点错误,意思是:如何不用随机生成略缩图,而是用自己的图片.

**Comment by neoFelhz** [comment]
@wjx0908 https://material.viosey.com/docs/#/compose?id=front-matter
