### ISSUE TITLE
修改静态文件生成模板问题

### ISSUE THREAD

**Issue by NimaQu** [viosey/hexo-theme-material#582]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

我想在版权声明下多添加一条内容，可是每次hexo g以后都需要重新修改生成的html文件，请问能不能用修改模板的方式使每次生成的文件自带我想添加的内容

**Comment by Leezj9671** [comment]
文档中[footer_text](https://material.viosey.com/docs/#/config_customize?id=footer_text)的应该可以做到你想要的功能

**Comment by NimaQu** [comment]
请问footer_text应该加在配置文件的哪个地方，没有在配置文件中找到。不知是不是我使用的版本过低（稳定版1.4.0）我尝试加在此处，但并没有看见效果
![image](https://user-images.githubusercontent.com/26685881/34264317-7c00570e-e6ad-11e7-9d44-6c99fd482614.png)

**Comment by Leezj9671** [comment]
@NimaQu 是的，这是[1.5.0](https://github.com/viosey/hexo-theme-material/releases)新出的功能，建议theme目录下做`git pull`更新
