### ISSUE TITLE
地址跳转错误问题

### ISSUE THREAD

**Issue by Leezj9671** [viosey/hexo-theme-material#586]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

比如在归档的目录/archives/2017/12下，再点击侧边栏的标签，则地址会跳转到/archives/2017/12/tags/。
我的站点配置文件是
```yml
url: http://yoursite.com
root: /
```

**Comment by musheng66** [comment]
应该是路径中的／问题，可以看一下主题配置文件的 sidebar 属性，找到自定义的 pages 配置，看看是否缺少／，比如：link:"tags"改成 link:"/tags"。
