### ISSUE TITLE
markdown有序列表和无序列表解析渲染错误

### ISSUE THREAD

**Issue by colorblank** [viosey/hexo-theme-material#588]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

有序列表的数字和后面的内容隔了一行，无序列表也一样。但只是在电脑上是这样。手机上有序列表的数字消失了，无序列表还在，但电脑上渲染错误的无序列表也不见了.就像下面的图片
![vyPRx.png](https://s1.ax1x.com/2017/12/25/vyPRx.png)

**Comment by NanerLee** [comment]
这个我也碰到过, 不过是在内嵌列表的时候出现的, 我当初以为是 render 的原因, 换了好几个hexo markdown的 render 发现都是这样, 难道是主题的原因?

**Comment by musheng66** [comment]
有序列表和无序列表显示错位的问题我也遇到了，可能是因为列表的两行之间不能存在空行，我把空行删除之后就显示正常了。

**Comment by NanerLee** [comment]
@musheng66 确实没有空行就正常了, 但是有空行才应该是正确的语法

标准的 Markdown 和 CommonMark 是必须要同时有缩进和空行

GFM是对有缩进, 有空行且有缩进支持, 对只有空行不支持, 

感觉上应该还是 hexo 的 markdown render有问题
