### ISSUE TITLE
icons无法显示的问题

### ISSUE THREAD

**Issue by Metr05** [viosey/hexo-theme-material#592]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

![Alt text](http://ww3.sinaimg.cn/large/0060lm7Tly1fnas66hw4hj30fb0edaac.jpg)
![Alt text](http://ww3.sinaimg.cn/large/0060lm7Tly1fnas66hhnmj30em09x0so.jpg)

**Comment by codgician** [comment]
我发现此情况在 Microsoft Edge 和 IE 上出现，而在 Chrome / Firefox 上是正常的。
This issue seems to be appearing only on Microsoft Edge and Internet Explorer. The icon shows up on Chrome / Firefox.

**Comment by Rictusempra** [comment]
edge IE无法渲染 woff2 字体
因此可能无法修复

**Comment by codgician** [comment]
edge支持woff2字体啊...
