### ISSUE TITLE
Why not remove _config.yml from .gitignore?

### ISSUE THREAD

**Issue by EddyGuo** [viosey/hexo-theme-material#596]
When I don't know the problem, I push my theme files to my coding repository. Then I pull them in another computer, I can't generate my blog.

**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

**Comment by cubesky** [comment]
@EddyGuo We use config.template.conf to avoid git merge fast-forward

**Comment by EddyGuo** [comment]
@cubesky Thank you! So is there a way to avoid what I encounter? Maybe a warning is necessary.

**Comment by EddyGuo** [comment]
@cubesky Thank you!
