### ISSUE TITLE
Uncaught TypeError: Cannot read property 'contains' of undefined at HTMLButtonElement.<anonymous> (<anonymous>:1:95295)

### ISSUE THREAD

**Issue by PerfectForNi** [viosey/hexo-theme-material#598]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

所有页面点击呼出侧边菜单栏都会报错（1.5.0 和 1.5.2 都会出现此报错，1.4.0 没有）
`Uncaught TypeError: Cannot read property 'contains' of undefined at HTMLButtonElement.<anonymous> (<anonymous>:1:95295)`

![1](https://user-images.githubusercontent.com/12109556/35195375-8aee677a-fefd-11e7-8ded-e911ce7f21bf.PNG)
![2](https://user-images.githubusercontent.com/12109556/35195391-a5c218b2-fefd-11e7-82ab-cb99ec4610b4.PNG)

**Comment by ibreathebsb** [comment]
+1

**Comment by itning** [comment]
同问题

**Comment by itning** [comment]
我在 #651  中 已经提交修复

**Comment by PerfectForNi** [comment]
Closed by @itning .
Reference: #654 .
