### ISSUE TITLE
Isolation 左侧菜单顺序调整

### ISSUE THREAD

**Issue by cielpy** [viosey/hexo-theme-material#6]
如果开启 about，关于会固定在第二位置，再添加独立页面，如「标签云」等时，则顺序往下排，「关于」的位置不可调整。

希望可以调整「关于」的位置。:)

**Comment by viosey** [comment]
因为「关于」的入口使用了 i18n，当初是考虑到「关于」算是一个标配，所以主题直接定义了入口的多语言文字，设计成默认固定位置。
>其他排序是手动修改入口文字和链接来实现

这也是算个遗留问题的吧

**Comment by cielpy** [comment]
「关于」这个可以不是标配，这样这个页面怎么叫主题使用者可以随意设置，「关于」「关于我」about, About, About me 之类的，这样似乎更好一些。

**Comment by viosey** [comment]
OK，下个版本更新
