### ISSUE TITLE
阅读模式reading的bug不对其

### ISSUE THREAD

**Issue by summersir** [viosey/hexo-theme-material#60]
![qq20161209-200510](https://cloud.githubusercontent.com/assets/20942887/21049111/e029e5da-be4d-11e6-9ebe-33e900ec76f4.png)
这是Material 
![qq20161209-200818](https://cloud.githubusercontent.com/assets/20942887/21049133/0742ef40-be4e-11e6-8c99-7d780ddab5ca.png)
这是Github 的
![qq20161209-200833](https://cloud.githubusercontent.com/assets/20942887/21049140/1462af1c-be4e-11e6-9425-b8d7ba3695be.png)
这是Plain的
Material 和Plain 都有不对其的现象

**Comment by viosey** [comment]
谢谢反馈，只优化了Github 的样式，忘记修改其他两个了

**Comment by summersir** [comment]
Material 的阅读模式文字那部分看起来还是很好看的 只是代码样式这里 突出的这个淡灰色的东西 感觉怪怪的 不知道能不能也同时解决一下
还有就是用markdown写的时候有个“> 文字。。。”，但是这个样式没有缩进 和其他的样式对比起来就感觉看起来怪怪的 不知能否解决 

![qq20161210-085149](https://cloud.githubusercontent.com/assets/20942887/21069586/6783df32-beb6-11e6-95bd-e4a85c35cf13.png)

**Comment by viosey** [comment]
因为和代码高亮冲突，所以新的版本移除了 Material 的样式
同时也修复了 Plain 样式的 bug
