### ISSUE TITLE
YAMLException: bad indentation of a mapping entry at line 2, column 9:

### ISSUE THREAD

**Issue by LoveMinOS** [viosey/hexo-theme-material#600]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

ERROR Process failed: _data/links.yaml
YAMLException: bad indentation of a mapping entry at line 2, column 9:
之前没有错误，但是添加友情链接数据后和自定义添加代码后YAML报错，检查_config.yaml内冒号后已添加英文输入状态下的空格，请求技术帮助，感谢！

**Comment by jovensun** [comment]
我也遇到过类似的问题。原因是自己对YAML语法不熟悉。
比如在""里面的引号要全部换成 ''

**Comment by LoveMinOS** [comment]
@jovensun 我想在</body>加入心知天气的代码，网页自动生成的，您能试试吗？

**Comment by jovensun** [comment]
@LoveMinOS  抱歉，我不是web开发工作者。不能帮你实现。

**Comment by LoveMinOS** [comment]
@jovensun 好的，感谢！
