### ISSUE TITLE
稳定版1.4.0是没有内置prettify hanabi。

### ISSUE THREAD

**Issue by Gengry** [viosey/hexo-theme-material#606]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [ ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

稳定版没有内置代码高亮的两个功能，但是文档没有明确指出，在这里疑惑了好久。希望在文档中提示一下。

**Comment by cubesky** [comment]
@Gengry 文档永远指向最新稳定版的功能

**Comment by Gengry** [comment]
这个没有更新 ，指向的是1.4.0。没有注意直接下载的1.4.0
![qq 20180206104154](https://user-images.githubusercontent.com/16619358/35839307-aabbb20e-0b2a-11e8-8f85-ae2bc2546133.jpg)

**Comment by LoveMinOS** [comment]
@Gengry 文档是针对1.5.0版本

**Comment by ufan0** [comment]
同为这个问题，折腾了好几个小时才发现版本有问题……还是看到文档最后主题版本号，直接下载稳定版本还是1.4的，希望大家注意这个问题。
应该去所有版本自行选择1.52下载
