### ISSUE TITLE
不兼容 Markdown 反斜杠效果

### ISSUE THREAD

**Issue by siyuanlau** [viosey/hexo-theme-material#607]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

[Markdown 语法说明(简体中文版)](http://wowubuntu.com/markdown/) 说：

> Markdown 可以利用反斜杠来插入一些在语法中有其它意义的符号

下述代码：

![5a7a576895375.png](https://i.loli.net/2018/02/07/5a7a576895375.png)

在 GitHub 自带编辑器上显示如下：

![5a7a580ab9386.png](https://i.loli.net/2018/02/07/5a7a580ab9386.png)

而在 Material 主题上：

![5a7a5855aba11.png](https://i.loli.net/2018/02/07/5a7a5855aba11.png)

**Comment by neoFelhz** [comment]
Not the problem of thew theme
