### ISSUE TITLE
SNS Menu don't display in Chrome.

### ISSUE THREAD

**Issue by NewtonLee95** [viosey/hexo-theme-material#61]
- SNS Menu don't display in Chrome.
- But SNS Menu can display in Edge.
- So my configuration is right.

**Comment by viosey** [comment]
Please show your site's url.
Whether [my blog](https://blog.viosey.com)'s SNS menu displays in your Chrome?

**Comment by NewtonLee95** [comment]
- Your blog's SNS menu don't display  in my Chrome. 
- My site is https://newtonlee95.github.io/.
- My Chrome version is 55.0.2883.75 m.

**Comment by viosey** [comment]
- What's your OS?
- OS X El Capitan is normal.
![Screen Shot 2016-12-10 at 11.58.20 AM.png](https://ooo.0o0.ooo/2016/12/10/584b7d79ad21d.png)

**Comment by NewtonLee95** [comment]
- Win 10 . 
- Your blog.
![qq 20161210152213](https://cloud.githubusercontent.com/assets/15571048/21071951/b3e92dc4-beec-11e6-8c8c-f9a10ba81341.png)

**Comment by viosey** [comment]
weird, use the Developer Tools to check  is there any error.

**Comment by NewtonLee95** [comment]
- This problem may only occur on my computer.
- The Font Awesome icons for other sites will not be displayed on my Chrome.
- So my Chrome configuration may have problems.
- Thanks.
- This issue can be closed.

**Comment by viosey** [comment]
Try to reinstall Chrome, maybe can solve this problem.
