### ISSUE TITLE
c++ 代码块包含 #include 时会导致换行异常。

### ISSUE THREAD

**Issue by daizhirui** [viosey/hexo-theme-material#613]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

c++ 代码块包含 #include 时会导致换行异常。
<img width="450" alt="2018-02-17 10 10 10" src="https://user-images.githubusercontent.com/26495795/36337164-249b61d4-13cb-11e8-9333-460947aebca9.png">
<img width="451" alt="2018-02-17 10 09 53" src="https://user-images.githubusercontent.com/26495795/36337165-24cc9ff6-13cb-11e8-88a9-2eec53272300.png">

**Comment by siyuanlau** [comment]
要在 Hexo 博客主配置文件（非 material 主题文件夹中的）中取消代码高亮，而是用 Material 自带的。

**Comment by daizhirui** [comment]
我知道了，请问prettify的行号要怎么关闭？
