### ISSUE TITLE
两种内置的代码块问题反馈

### ISSUE THREAD

**Issue by jovensun** [viosey/hexo-theme-material#616]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

Material的开发者们你们好，我在使用该主题中发现了下面两个问题。
1.prettify 代码过长时没有水平滚动条而是直接换行，如下图
__prettify__
![](https://ws1.sinaimg.cn/large/e43f160dgy1fomyp0o8tyj20oc03tjrv.jpg)
__hanabi__
![](https://ws1.sinaimg.cn/large/e43f160dgy1fomyrsb0j5j20nr03b74m.jpg)

2.hanabi 无法解析 & 运算符。在代码中会显示成 `&amp;`
![](https://ws1.sinaimg.cn/large/e43f160dgy1fomyshdmjtj20lw00xwem.jpg)

虽然说在功能上没有什么影响，但是确实影响了美观。希望开发者们至少能够解决其一。十分感谢。

**Comment by VeronicaF** [comment]
期待解决第一个，手机浏览体验有点差。

**Comment by iCyris** [comment]
可以参考 https://github.com/viosey/hexo-theme-material/issues/383 进行修改，能解决你的第一个问题。

**Comment by Macr0phag3** [comment]
Cooool. thx @iCyris

**Comment by Singularity0909** [comment]
thx very much @iCyris
