### ISSUE TITLE
七牛提供的cdn加速服务

### ISSUE THREAD

**Issue by lirawx** [viosey/hexo-theme-material#618]
看到七牛提供的cdn加速服务，希望hexo-theme-material 也能用上cdn ，我已经在七牛cdn repo 下提前发起了一个push request 。这样提高国内的访问速度，国外的话，七牛云的cdn可能照顾不到，甚用。

具体请戳[➡️](http://staticfile.org/)
pull request 地址 请戳[➡️](https://github.com/staticfile/static/pull/499)
希望得到官方的支持。
谢谢。

**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

**Comment by neoFelhz** [comment]
Material 主题目前的公共 CDN 库服务由 jsDelivr 提供，在全球都有节点（包括由 CloudFlare Fastly Stackpath 运行的海外节点和由网宿运行的中国大陆节点），详情已经列明在 README 之中；staticfile 公共库已经很久没有更新，也不支持 HTTP/2。

**Comment by lirawx** [comment]
好的，明白了，我就是想看看两个cdn 哪个快一点，staticfile仓库我看几天前还更新了一下，也没说停止维护的。
