### ISSUE TITLE
如何添加鼠标点击效果功能的js插件

### ISSUE THREAD

**Issue by labuboco** [viosey/hexo-theme-material#620]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

想问下如何添加鼠标点击效果的js插件?具体步骤:例如需要修改什么文件,js文件放置位置等,看了hexo的文档里面没有介绍清楚.

**Comment by idawnlight** [comment]
@labuboco 伸手党无敌

**Comment by labuboco** [comment]
在网上搜了下,全是说修改swig文件的,但是咱们主题好像没有swig文件,所以引用js要加在哪儿...小白求教

**Comment by labuboco** [comment]
@idawnlight 不是伸手我是找不到咱们主题的相关说明,搜到的全是隔壁主题的...

**Comment by idawnlight** [comment]
因为这主题用的是 EJS 啊，当然找不到 swig...

**Comment by labuboco** [comment]
@idawnlight 懂了 那就是不能魔改了
