### ISSUE TITLE
Excerpt样式改进建议

### ISSUE THREAD

**Issue by marcopolocai** [viosey/hexo-theme-material#623]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ x ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [ x ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ x ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ x] feature request | 申请添加新的特性或功能
- [ x] support request | 请求技术支持

您好， 首页文章的Excerpt目前只能选一个数值（default 80）以截断文章， 但截断后在首页显示时会出现无排版格式的情况（无空行，或完整代码块不能显示），如下：

<a data-flickr-embed="true"  href="https://www.flickr.com/photos/95862377@N08/40757400031/in/dateposted-public/" title="Screen Shot 2018-03-11 at 6.01.35 PM"><img src="https://farm5.staticflickr.com/4797/40757400031_80c6590abf_o.png" width="752" height="115" alt="Screen Shot 2018-03-11 at 6.01.35 PM"></a>

<a data-flickr-embed="true"  href="https://www.flickr.com/photos/95862377@N08/25886914507/in/dateposted-public/" title="Screen Shot 2018-03-11 at 6.01.50 PM"><img src="https://farm5.staticflickr.com/4802/25886914507_c46a9742f9_o.png" width="749" height="89" alt="Screen Shot 2018-03-11 at 6.01.50 PM"></a>

希望能够完善，感谢！

**Comment by script74** [comment]
赞同啊，体验太差了，（首先我是非常感谢作者写出这么好的主题免费提供给大家的，单我只是一个普通用户不懂开发，我从普通用户的角度提几点建议）现在的首页样式感觉也只能做demo用，另外首页标题位置直接是白色字体叠加在图片上的，如果图片正好是浅色就看不清标题了，整体来说，主题的风格对文章编辑和图片编辑要求太高，风格稍有不对就看起来花里胡哨的，感觉只能做纯技术类博客用了，所以希望能得知还有首页缩略图的高度，我自己想修改一下，把标题另起一栏放到图片下面去，图片太狭长无法使用照片之类的图片，所以我需要修改图片高度，另外因为简略我设置成240字，但是字符间距行距完全没有排版看着很费眼，所以希望作者能够告知以上需求我应该修改那个文件（因为不懂开发，各种内容搜索派上了我还是找不到应该在那里修改数值），以上，万分感谢！
