### ISSUE TITLE
系统题序和我自己写的题序重叠，建议给系统题序一个开关

### ISSUE THREAD

**Issue by skyArony** [viosey/hexo-theme-material#624]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

目录自带的题序和我写的题序重叠了，我要是自己不写题序，文档阅读起来感觉没有层次感，而且有时候文章要放到其他地方，也不能没有自己的题序，所以建议这里的这个题序可以有一个开关。

![image](https://user-images.githubusercontent.com/16434647/37477296-509037f0-28b2-11e8-833b-d4091c350f41.png)

**Comment by neoFelhz** [comment]
We already have it.
