### ISSUE TITLE
文档打不开

### ISSUE THREAD

**Issue by zdRan** [viosey/hexo-theme-material#627]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [ ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ x] support request | 请求技术支持

就没人发现主题文档打不开了么？一直是正在加载

**Comment by zhaodongxx** [comment]
我也遇到这个问题，文档打不开。我把文档工程下载到本地运行，还是打不开。一直显示 “正在加载“
