### ISSUE TITLE
独立页面编辑报错

### ISSUE THREAD

**Issue by DerekHey** [viosey/hexo-theme-material#638]
#但是在根据教程进行友链独立页面编辑的时候，在_data文件夹内创建links.yaml后，一直报错：
ERROR Process failed: _data/links.yaml
YAMLException: missed comma between flow collection entries at line 1, column 184:
... 033\themelangfe2052\themelangcs0{\fonttbl{\f0\fbidi \froman\fcha ..

**Comment by neoFelhz** [comment]
Check your yaml format
