### ISSUE TITLE
source 目录下的 HTML 文件可以不渲染吗

### ISSUE THREAD

**Issue by cielpy** [viosey/hexo-theme-material#64]
因为站长平台或者一些服务需要放一个文件进行验证，现在的情况是被渲染成页面，这样就验证了不了，有没有选项可以禁用某些文件的渲染？

**Comment by neoFelhz** [comment]
请仔细阅读[Hexo 官方文档](hexo.io/docs)。

**Comment by cielpy** [comment]
文档中没有找到才问的

**Comment by cielpy** [comment]
你贴的链接 404 了
