### ISSUE TITLE
Missing tag Cloud & timeline page documentation

### ISSUE THREAD

**Issue by utkuufuk** [viosey/hexo-theme-material#640]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

----

Hi, 

I'm trying to add **tag cloud** and **timeline** pages to my site. I have read all the docs and looked at related issues but I couldn't find anything, mostly because the doc links are broken. 

I created a `tags` folder within the `source` folder, and an `index.md` file inside the `tags` folder:
```yaml
---
title: tags
date:
layout: tags
---
```
Likewise I created a `timeline` folder within the `source` folder, and an `index.md` file inside the `timeline` folder:
```yaml
---
title: timeline
date:
layout: timeline
---
```

But the pages don't show up like is should as in the [demo](https://blog.viosey.com/).

For example in [this doc page](https://material.viosey.com/docs/#/en/pages), it says:
*"If you'd like to add an entry to the Timeline page, please refer to the page settings."* and
*"If you'd like to add an entry to the Tag Cloud page, please refer to the page settings."*

But the given page link is broken: <https://material.viosey.com/docs/#/en/intro/?id=pages>

Furthermore in issue #130, another link is given but it's also broken:
<https://material.viosey.com/intro/#pages>

Finally the link in issue #41  is also broken:
<https://material.vss.im/compose/#创建「标签云」页面>

Please can you assist me in creating tag cloud and timeline pages? 
It would be better if you could direct me to the correct documentation page.

Thanks.

**Comment by LunaSusie** [comment]
你必须在主题配置文件 _config.yml添加页面

![image](https://user-images.githubusercontent.com/15190244/39077095-ef4e8356-4531-11e8-9362-25230c64d870.png)

**Comment by xuanxiaodeyu** [comment]
@LunaSusie  请问新增的pages，如标签等，它的icon是在哪设置的？或者说icon的路径在哪？

**Comment by neoFelhz** [comment]
As @LunaSusie said, you have to add page enter at theme _config.yml
