### ISSUE TITLE
关于自建页面的一点建议

### ISSUE THREAD

**Issue by LunaSusie** [viosey/hexo-theme-material#641]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

我建议文档里面可以写一个自建页的例子，比如关于我页面怎么做，给一些没有前端基础的人一些建议或者例子，比如我。。。，至少让使用该主题的人可以快速把博客搭建起来

**Comment by heliumyc** [comment]
似乎目前自建页面只支持**gallery, links, tagcloud, timeline** 和最基础的**post**

如果你想在除了 **_posts** 里面的页面以外建立独立页面, 可以在 **source** 下面自建文件夹, 比如建立 **foo** , 然后在 **foo** 下面建立一个 **index.md**, layout里面填以上几种之一, 那么访问 **yoursite.com/foo/**就会显示这个页面.
实际上source内的文件结构最后就是网站的目录结构, 例如:
**./source/foo/test.md -> yoursite.com/foo/test.html**
**./source/test.md -> yoursite.com/test.html**

这个页面可以放在侧边栏里面, 也可以链接到首页的daily_pic或者是logo上 (在 **_config.yml** 的**url:** 后面修改)
