### ISSUE TITLE
点击左侧按钮报错

### ISSUE THREAD

**Issue by SamoZ** [viosey/hexo-theme-material#645]
如图，当我点击左侧菜单展开时，js报错，搜索了一下，不知道从哪着手
![f t d6 w p ltpy46 v](https://user-images.githubusercontent.com/25240164/39222207-0b7c3b6a-486e-11e8-92c8-6b7b9bc25525.png)
![z1 2omli 3vrdzp1p rur6](https://user-images.githubusercontent.com/25240164/39222210-0d623538-486e-11e8-8792-e82dc9e60a9e.png)

**Comment by TequiLaSS** [comment]
我也出现了这个问题，我用的谷歌浏览器

**Comment by itning** [comment]
我在 #651 中 已经提交修复

**Comment by neoFelhz** [comment]
Merged
