### ISSUE TITLE
这个主题categories是没用的吗?

### ISSUE THREAD

**Issue by eightHundreds** [viosey/hexo-theme-material#65]

**Comment by eightHundreds** [comment]
看到了,在文章的右下角有,请问没有专门显示所有分类的页面吗?

**Comment by eightHundreds** [comment]
在archives页面下有个true,在线Demo这边也有
![image](https://cloud.githubusercontent.com/assets/18695431/21219259/042f0046-c2ef-11e6-9374-9aaa4f6ce1e0.png)

**Comment by neoFelhz** [comment]
true 这个应该最新一次 commit 里修复了

**Comment by viosey** [comment]
true 已修复，category 还没有

**Comment by viosey** [comment]
#29
