### ISSUE TITLE
希望可以支持多级分类

### ISSUE THREAD

**Issue by HuangYiCheng1997** [viosey/hexo-theme-material#659]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

有强迫证，希望有多级分类的功能，当然，我也知道作者忙，我也有上网找过实现方法。

在[网上](https://www.jianshu.com/p/e6e54389c88f)看到可以通过修改layout/_widget/category.ejs文件实现多级分类，

然而在该主题的文件夹下找不到category.ejs

如果作者能抽空实现多级分类这个功能当然最好~

但如果太忙~  能否指点下去修改哪些文件可以实现多级分类的效果呢？

**Comment by neoFelhz** [comment]
It's the issue of hexo.

**Comment by EqualMa** [comment]
我在这个fork version中加入了多级分类菜单的显示：https://github.com/EqualMa/hexo-theme-material-awesome
