### ISSUE TITLE
如何开启友链与标签云？

### ISSUE THREAD

**Issue by RioHsc** [viosey/hexo-theme-material#668]
弄了好久，都不懂在哪里开启

**Comment by HZoi-WildRage** [comment]
[创建「标签云」页面](https://material.viosey.com/docs/#/pages?id=%E5%88%9B%E5%BB%BA%E3%80%8C%E6%A0%87%E7%AD%BE%E4%BA%91%E3%80%8D%E9%A1%B5%E9%9D%A2)  
先去看看文档

**Comment by RioHsc** [comment]
@HZoi-WildRage Hexo提示如下
```bash
$ hexo s
INFO  Start processing
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/data/data/io.neoterm/files/home/hexo/source/_data/gallery.yaml'
$
```

**Comment by neoFelhz** [comment]
如果你不花一分钟时间看一眼 issue 模板甚至删掉它，那么我一秒钟都不会花在你的 issue 上。
