### ISSUE TITLE
关于友链数据添加

### ISSUE THREAD

**Issue by AD1024** [viosey/hexo-theme-material#67]
不添加Name字段时能够正常显示（名字为"Name"）。设置Name后友链界面就没有数据了...配置如下：
```
Name: STUB
    link: http://example.com/
    avatar: http://example.com/
    descr: "http://example.com/"
```

link 和 avatar 在实际的设置中，link与avatar都没有问题。

**Comment by viosey** [comment]
请详细阅读该文档 [友情链接 添加数据](https://material.vss.im/compose/#添加数据)

**Comment by AD1024** [comment]
谢谢！我明白了。
