### ISSUE TITLE
Hope Wechat can be added to share menu

### ISSUE THREAD

**Issue by Jingyi97** [viosey/hexo-theme-material#674]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [x] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

Dear developers,
The material theme is of great help in building my blog. Thanks to all the developers.
The sns_share have 7 items for users to choose from. But I have found that Wechat is not included in the sns_share items. What about adding Wechat to the share menu ? I think this feature will be helpful for readers to share blog's posts to their Moments of Wechat.    
Best wishes,
Jingyi

**Comment by cubesky** [comment]
WeChat share need a WeChat Appid and WeChat Appid can not set all url as "Secure URL". So, it can not use as a share button in this theme. You can register an Appid and add WeChat JSSDK to use WeChat Share Button.
