### ISSUE TITLE
新装hexo，然后解压主题安装，执行hexo s 或者 hexo g 都有错误，没改任何文件。

### ISSUE THREAD

**Issue by arleyGuoLei** [viosey/hexo-theme-material#684]
主题通过修改配置已经切换到material，主题配置文件也拷贝更名，没做任何修改。（默认主题不会报错）

报错如下：

INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: E:\Blog\Arley\themes\material\layout\layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         

E:\Blog\Arley\themes\material\layout\_partial\head.ejs:20
    18|
    19|     
 >> 20|     <%- partial('_widget/dnsprefetch') %>
    21|
    22|     
    23|     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

E:\Blog\Arley\themes\material\layout\_widget\dnsprefetch.ejs:2
    1| <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 2| <% if(theme.vendors.materialcdn) { %>
    3|     <link rel="dns-prefetch" href="<%= theme.vendors.materialcdn %>"/>
    4| <% } %>
    5| <% if( (theme.leancloud.enable === true) || (theme.comment.use == "valine") ) { %>

Cannot read property 'materialcdn' of undefined

**Comment by BeautyYuYanli** [comment]
所以这是什么情况?这里也有同样的问题

**Comment by cubesky** [comment]
@BeautyYuYanli 请阅读文档以设定初始配置文件

**Comment by arleyGuoLei** [comment]
我也还没解决，更新nodejs 等都没用，主题配置文件没从头到尾全部修改完，就修改了head部分，可能要全部配置完。 @ @BeautyYuYanli

**Comment by BeautyYuYanli** [comment]
已经解决了。这里直接使用了1.5.0的配置文件放进1.5.5导致出错

**Comment by arleyGuoLei** [comment]
@BeautyYuYanli 正确的配置文件还没更新上来吗？ 我下载1.5.2的替换进去  也是报错

**Comment by BeautyYuYanli** [comment]
事实上直接用155的样例配置文件都不行。或许需要更详细的配置吧？
