### ISSUE TITLE
Cannot read property 'materialcdn' of undefined

### ISSUE THREAD

**Issue by ThreeAndTwo** [viosey/hexo-theme-material#688]
ERROR /Users/kai/Code/hexoBlog/themes/material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         

/Users/kai/Code/hexoBlog/themes/material/layout/_partial/head.ejs:22
    20|
    21|     
 >> 22|     <%- partial('_widget/dnsprefetch') %>
    23|
    24|     
    25|     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

/Users/kai/Code/hexoBlog/themes/material/layout/_widget/dnsprefetch.ejs:2
    1| <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 2| <% if(theme.vendors.materialcdn) { %>
    3|     <link rel="dns-prefetch" href="<%= theme.vendors.materialcdn %>"/>
    4| <% } %>
    5| <% if( (theme.leancloud.enable === true) || (theme.comment.use == "valine") ) { %>

Mac, 1.5.6 版本，在hexo generate时报的错，能否指教一下？

**Comment by Nineburning** [comment]
我也遇到同样的问题，请问你现在解决了吗

**Comment by ThreeAndTwo** [comment]
没有，我觉得是官方的 Bug

**Comment by Nineburning** [comment]
我之后重新安装了，并且用回了1.5.2版本就没问题了

**Comment by Nineburning** [comment]
`/themes/material/_config.yml`的这里改false看能不能解决
```yaml
# Enable generate structured-data as JSON+LD for SEO or not.
    # Set as 'false' if it cause some wrong when `hexo g`.
    structured_data: false
```

**Comment by michaelcai** [comment]
1. 在主题文件夹下新建一个_config.yml文件，并将_config.template.yml里的配置复制到_config.yml文件。
2. 修改layout/_widget/dnsprefetch.ejs文件。修改内容如下：
`
<% } else if(theme.comment.use.startsWith("disqus")) { %>
// to
<% } else if(theme.comment.use && theme.comment.use.startsWith("disqus")) { %>
`

**Comment by NathanDai** [comment]
OK it has works

**Comment by cubesky** [comment]
Please use newest `_config.yml` . If you upgrade from old version, please check `_config.template.yml` and merge them manually.

**Comment by Doracoin** [comment]
今天遇到了这个问题，按着楼上的解答排查了一下，发现新版本的yml文件里增加了`gallery`节点，补充上这个节点问题就解决了

**Comment by akring** [comment]
另一个解决思路，主题配置文件 `_config.yml`的 `use: ` 随便填一项，只要不空着就可以了
```yml
comment:
    use: disqus
    shortname: # duoshuo or disqus shortname
```
