### ISSUE TITLE
创建私有页面

### ISSUE THREAD

**Issue by w4lle** [viosey/hexo-theme-material#69]
按照文档创建私有页面
加入 ``layout: private``不生效

**Comment by viosey** [comment]
![Screen Shot 2016-12-19 at 2.20.46 PM.png](https://ooo.0o0.ooo/2016/12/19/58577c6101844.png)

加入后需执行 `hexo clean && hexo g` 重新生成

**Comment by w4lle** [comment]
```
---
layout: private
title: title
date: 2016-12-19 11:16:53
---

# private
```

pwd : /source/_posts

hexo clean && hexo g 重新生成依然可以在首页看到

**Comment by w4lle** [comment]
要新建private目录吗？？

**Comment by viosey** [comment]
首页可以看到入口，但是文章没有内容

**Comment by w4lle** [comment]
哦，私有页面是这个意思啊。了解了。
