### ISSUE TITLE
为什么部署到服务器后图标不能正常显示

### ISSUE THREAD

**Issue by lawler61** [viosey/hexo-theme-material#690]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

部署到服务器后用 手机 查看一些图标下的字体被显示出来了，如图
[ 如图所示 ](http://www.freeze61.me/img/test.jpg)

**Comment by Nineburning** [comment]
@jeffery5461 你换用其他浏览器试试看，我在测试的时候发现搜狗浏览器打开网页时图标显示不正常，与你所说的情况一模一样。

**Comment by jeffery5461** [comment]
@Nineburning 可能真是浏览器问题，我又测试了下手机上其他浏览器，uc好像也不能正常显示。感谢老哥了
