### ISSUE TITLE
Footer中的社交图标无法正常显示

### ISSUE THREAD

**Issue by AngelMsger** [viosey/hexo-theme-material#692]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

---

Footer中的社交图标无法正常显示(size 0*0?)，包括README中的来自[liyin's Blog](https://liyin.date/)的Demo。

**Comment by cubesky** [comment]
![image](https://user-images.githubusercontent.com/8038511/44310432-c238dc00-a408-11e8-80f2-6d84a7e39d8b.png)
It seems ok. What's wrong?

**Comment by AngelMsger** [comment]
@cubesky social link icon broken in [my page](https://blog.angelmsger.com/), also the [demo](https://liyin.date/) in the doc with the latest version, while I get size 0*0 in the code when inspect it in the broswer(newest chrome).

**Comment by cubesky** [comment]
@AngelMsger 
![image](https://user-images.githubusercontent.com/8038511/44330552-e264ab80-a499-11e8-98a0-f5f5b371be84.png)   
I visit your blog via Firefox 61 and Chrome 68. I don't find any issue with socal link icon.

**Comment by cubesky** [comment]
And I test Chrome 69 via BrowserStack. 
![image](https://user-images.githubusercontent.com/8038511/44331149-5489c000-a49b-11e8-81cc-e252eca0ab99.png)

**Comment by AngelMsger** [comment]
@cubesky oh, finally I find that my adblock plus' **blocked social media icons tracking** is enabled, thus removing the icon from page, no error with this theme, thanks a lot!

**Comment by MizoreYo** [comment]
> @cubesky社交链接图标在[我的页面中](https://blog.angelmsger.com/)损坏，也是文档中具有最新版本的[演示](https://liyin.date/)，而在浏览器（最新的chrome）中检查时，代码中的尺寸为0 * 0。

我也遇到了这个问题，用chrome就不显示图标

**Comment by AngelMsger** [comment]
> > @cubesky社交链接图标在[我的页面中](https://blog.angelmsger.com/)损坏，也是文档中具有最新版本的[演示](https://liyin.date/)，而在浏览器（最新的chrome）中检查时，代码中的尺寸为0 * 0。
> 
> 我也遇到了这个问题，用chrome就不显示图标

我当时是因为启用了广告拦截器中关于社交媒体图标的配置, 导致这些图标被屏蔽了.

**Comment by MizoreYo** [comment]
> > > @cubesky社交链接图标在[我的页面中](https://blog.angelmsger.com/)损坏，也是文档中具有最新版本的[演示](https://liyin.date/)，而在浏览器（最新的chrome）中检查时，代码中的尺寸为0 * 0。
> > 
> > 
> > 我也遇到了这个问题，用chrome就不显示图标
> 
> 我当时是因为启用了广告拦截器中关于社交媒体图标的配置, 导致这些图标被屏蔽了.

我已经解决了，我没有开启广告拦截器（我不知道chrome是否自带且自动开启），我在安卓和pc上的chrome都无法正常显示，但是我尝试更改了图标（我本来用的pixiv的图标（和它本来图标近乎一样，不知道是不是这个原因））。换成了其他的p字母的图标后就可以正常显示了
