### ISSUE TITLE
Metadata info and opengraph info

### ISSUE THREAD

**Issue by Ratne** [viosey/hexo-theme-material#70]
Hello, it's seams that your theme does not have any metadata info to show to serp and no open graph tag. Can it be a new feature?

**Comment by viosey** [comment]
There actually have these info, please view the source of this [page](https://blog.viosey.com/).
And the info is below `<!-- Meta & Info -->` & `<!-- The Open Graph protocol -->`
If I misunderstand your meaning, could you show me something detail for e.g.?

**Comment by Ratne** [comment]
I mean for each post. Like in yours blog there is not any meta data for single post but only a general keyword metadata and open graph

**Comment by viosey** [comment]
got it!

**Comment by Ratne** [comment]
ok let we know when will be done ;)

**Comment by Halyul** [comment]
I'll undertake this. But currently I'm busy...

**Comment by pidupuis** [comment]
Is https://github.com/viosey/hexo-theme-material/pull/138 fixing it?

**Comment by neoFelhz** [comment]
It also support OpenGraph now.
