### ISSUE TITLE
关于 [不蒜子] 更换域名

### ISSUE THREAD

**Issue by cntanglijun** [viosey/hexo-theme-material#704]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

![image](https://user-images.githubusercontent.com/13279117/47283541-63652e00-d616-11e8-846c-845630df54e1.png)

![image](https://user-images.githubusercontent.com/13279117/47283484-344ebc80-d616-11e8-8f09-bd25508982ab.png)

http://ibruce.info/2015/04/04/busuanzi/

**Comment by cubesky** [comment]
fixed, thanks @cntanglijun
