### ISSUE TITLE
ERROR Asset render failed: css/duoshuo.css

### ISSUE THREAD

**Issue by kekeimiku** [viosey/hexo-theme-material#713]
mac hexo g的时候会提示失败
```
ERROR Asset render failed: css/duoshuo.min.css
...
ERROR Asset render failed: css/duoshuo.css.
...
```
- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

**Comment by lanact** [comment]
> 我刚想问这个问题呢，和你一样的错误

唔～我的最后是很玄学的解决了，，，重新下载了两遍好了...
