### ISSUE TITLE
文章标题图放缩

### ISSUE THREAD

**Issue by xiaoLit** [viosey/hexo-theme-material#726]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x ] support request | 请求技术支持

请问如何可以把首页每个文章的图片样式设置为不默认缩放呢？否则如果不是合适的比例就会被放缩导致图片显示异常难看。

**Comment by xiaoLit** [comment]
我解决了。改一下style.min.css中的背景样式就好。

**Comment by Saigyouji-Yuyuko** [comment]
> 我解决了。改一下style.min.css中的背景样式就好。

想问下怎么做的。。。

**Comment by xiaoLit** [comment]
> > 我解决了。改一下style.min.css中的背景样式就好。
> 
> 想问下怎么做的。。。

可以看一下
https://xiaolit.com/posts/9fb021fa/
