### ISSUE TITLE
How to change color palette

### ISSUE THREAD

**Issue by yuri-karadzhov** [viosey/hexo-theme-material#74]
Is it possible to configure material design color palette?

I tried to change `source/css/material.css` and `source/css/material.min.css` with file generated by [material theme generator](https://getmdl.io/customize/index.html), but it affects nothing.

**Comment by viosey** [comment]
The theme's color seems could only changed by setting the [uiux](https://material.vss.im/en/intro/#uiux)
- theme_color
- theme_sub_color
- hyperlink_color
- button_color

**Comment by yuri-karadzhov** [comment]
Yes, I see. Probably there is a sense to adjust theme by downloading css file from here.

**Comment by viosey** [comment]
The `_config` color's priority is higher than the css file.
Maybe future will combine the both color palette function.

**Comment by yuri-karadzhov** [comment]
Yes, I've checked the code already, but it is not possible to configure all the colors in the `_config`. I will remove colors from config and use ones from palette. It will be easy to change by replacing it with another palette file.

**Comment by viosey** [comment]
Thanks for your suggestion. It will be awesome if you could pull request of this function.

**Comment by yuri-karadzhov** [comment]
Sure, if you find it useful i will do PR.

**Comment by viosey** [comment]
Yeah~
