### ISSUE TITLE
gallery插件如何使用

### ISSUE THREAD

**Issue by xwdMrBear** [viosey/hexo-theme-material#76]
如题,我在主题中发现有一个gallery插件,但是不知道如何导入图片和基本设置.求教

**Comment by viosey** [comment]
https://material.vss.im/compose/#创建「图库」页面

**Comment by xwdMrBear** [comment]
你好,额 为何按照教程在配置了_data这个文件夹之后,会报这种错误
![_20161228173156](https://cloud.githubusercontent.com/assets/24367288/21518982/f87c7680-cd24-11e6-8274-29a3eca3552c.png)
相关文档格式按照教程配置的.
不知道哪里出的问题
本人初学hexo,求教,多谢了

**Comment by xwdMrBear** [comment]
你好,额 为何按照教程在配置了_data这个文件夹之后,会报这种错误
![_20161228173156](https://cloud.githubusercontent.com/assets/24367288/21519041/4a7b45ba-cd25-11e6-90a3-36b787724069.png)
相关文档格式按照教程配置的.
不知道哪里出的问题
本人初学hexo,求教,多谢了 @viosey

**Comment by viosey** [comment]
请附上 gallery.yml 的内容

**Comment by xwdMrBear** [comment]
![_20161228180016](https://cloud.githubusercontent.com/assets/24367288/21519374/858435fc-cd27-11e6-9dcd-f648d59c9a7a.png)
hi,是我哪里写错了吗? @viosey

**Comment by viosey** [comment]
把空行去掉试试看

**Comment by Halyul** [comment]
issue #89

**Comment by gaoxianglyx** [comment]
我的画廊也报错了，在yml的第二个name报错，请问是怎么回事？

**Comment by viosey** [comment]
@gaoxianglyx 命名不能相同

**Comment by gaoxianglyx** [comment]
我有尝试改不同的名字，但是还是报错，报第二个name的错，我靠楼上那位老哥的名字也是一样的

**Comment by Halyul** [comment]
@gaoxianglyx 请附上你的相册yml截图，我看看

**Comment by gaoxianglyx** [comment]
http://ww2.sinaimg.cn/large/96ea1c33gw1fbexrtqjs4j20yf0f0wox.jpg
麻烦你了下面是报错的图
http://ww3.sinaimg.cn/large/96ea1c33gw1fbexs80gxrj20x30hztm7.jpg

**Comment by viosey** [comment]
你把相册的 yml代码贴过来一下，我试试看

**Comment by Halyul** [comment]
@gaoxianglyx 你的问题我并没有复现，需要原文件

**Comment by gaoxianglyx** [comment]
```
 洪崖洞:
    full_link: http://ww3.sinaimg.cn/large/96ea1c33gw1fbeuvqszykj21kw11ohdt.jpg
    thumb_link: http://ww3.sinaimg.cn/mw690/96ea1c33gw1fbeuvqszykj21kw11ohdt.jpg
    descr: "2016-12-24 平安夜 重庆洪崖洞之看我后期补妆"
洪崖洞2:
    full_link: http://ww1.sinaimg.cn/large/96ea1c33gw1fbevjwe8qgj21kw11ohdt.jpg
    thumb_link: http://ww4.sinaimg.cn/mw690/96ea1c33gw1fbevjwe8qgj21kw11ohdt.jpg
    descr: "2016-12-24 平安夜 重庆洪崖洞 8s f18 iso-100"
第一次也是唯一一次用5D3:
    full_link: http://ww2.sinaimg.cn/large/96ea1c33gw1fbevn2iwh7j21kw11x1kx.jpg
    thumb_link: http://ww4.sinaimg.cn/mw690/96ea1c33gw1fbevn2iwh7j21kw11x1kx.jpg
    descr: "2016-2-15 家里县城的咖啡馆（名字忘了） 1/50s f5 iso-320"
死基佬给我拍了一张糊了的帅照:
    full_link: http://ww3.sinaimg.cn/large/96ea1c33gw1fbevr6xyerj21kw11xe81.jpg
    thumb_link: http://ww3.sinaimg.cn/mw690/96ea1c33gw1fbevr6xyerj21kw11xe81.jpg
    descr: "2016-12-2 居然忘了小痰盂不能全开f1.8，好气啊 1/40s f1.8 iso-500"
```
感谢了，我还发现问题，在我更新代码到github上后，我的/gallery和/about页面都是进不去的，这个在我本地的hexo服务中是可以进去的，不知道会不会有联系，麻烦了

**Comment by gaoxianglyx** [comment]
@Halyul 感谢你，我找了这么久哈哈，我开始找下一个问题啦，再次感谢你和 @viosey
