### ISSUE TITLE
右侧增加一个文章目录可好？

### ISSUE THREAD

**Issue by vsxen** [viosey/hexo-theme-material#8]

**Comment by viosey** [comment]
TOC 吗？
会加的

**Comment by vsxen** [comment]
这个目录 只在第一页有，往后翻 就没了，  totop好像也不是很显眼

**Comment by viosey** [comment]
第一页有是什么意思？
toTop 更新为在固定显示在页脚

**Comment by viosey** [comment]
toc 目录需要点击文章页左上的 toc 按钮显示

**Comment by vsxen** [comment]
已经比较完美了

**Comment by viosey** [comment]
Paradox 的 TOC 目录经过较久的斟酌之后才觉得如此设计的，如果放在其他地方担心会显得突兀。
