### ISSUE TITLE
tags menu undefined

### ISSUE THREAD

**Issue by cubesky** [viosey/hexo-theme-material#81]
When you create page using "hexo new page title" and give tags to your artical , tags menu in this page will show "undefined" , and click it you will back to index.

**Comment by neoFelhz** [comment]
Well,we are supposing that people won't set tags on pages.There is indeed the issue here.
Maybe we can stop showing tags on pages to workaround.

**Comment by cubesky** [comment]
Ok, I work on it.

**Comment by viosey** [comment]
@cubesky We discuss this problem, and we decide to use a front matter paramete like `Tags`.
If `Tags: false` the tags button will be hidden, else it will be displayed.

**Comment by cubesky** [comment]
@viosey Oh, I just add a `notag: true` front matter paramete. I'm afraid `Tags` paramete conflict with `tags` using by article tags

**Comment by neoFelhz** [comment]
OK,already merged.
