### ISSUE TITLE
logo 和 icon 无法显示

### ISSUE THREAD

**Issue by james4879** [viosey/hexo-theme-material#82]
在调试的时候无法显示 logo 和 icon, 部署之后界面错位
<img width="721" alt="screenshot 2016-12-30 19 32 16" src="https://cloud.githubusercontent.com/assets/6235586/21564294/c2b3d5d6-cec6-11e6-93ee-a3deb087957e.png">

**Comment by viosey** [comment]
目测 CSS 没有加载完全或没有加载，
使用开发者工具查看一下。

**Comment by james4879** [comment]
https://james4879.github.io/james4879/james4879.github.io.git/css/material.min.cssFailed to load resource: the server responded with a status of 404 (Not Found)
显示没有找到这个css文件

**Comment by viosey** [comment]
你的路径配置错误了在站点配置文件下检查一下。现在使用的是相对路径，应该使用绝对路径`https://james4879.github.io/css/style.min.css`
