### ISSUE TITLE
多行标语问题

### ISSUE THREAD

**Issue by Halyul** [viosey/hexo-theme-material#84]
如图
![qq 20161230222732](https://cloud.githubusercontent.com/assets/6838450/21566587/408ae95a-cedf-11e6-883a-f7c7f172a8b7.png)

**Comment by neoFelhz** [comment]
暂时不允许多行 slogan，原因是 yaml 解析和转义问题。以后可能会有workaround 的方法。目前还在测试。

**Comment by Halyul** [comment]
问题在于现在这段代码是默认启用的，也就是pull了之后就会出现这个问题了

**Comment by viosey** [comment]
@cubesky #80 
It seems caused by this PR, please help to deal with it.

**Comment by cubesky** [comment]
@Halyul 你能提供下你的 _config.yml 中关于 slogan 部分的设置吗？

**Comment by cubesky** [comment]
@viosey I find this error just now , when slogan is null , it will shows this error.

**Comment by cubesky** [comment]
Fixed
