### ISSUE TITLE
sns_share 可以加入 facebook share 嗎

### ISSUE THREAD

**Issue by Mombuyish** [viosey/hexo-theme-material#96]
很喜歡這個主題
但是自己調適了一下發現 sns_share 這邊沒有支持 facebook 分享
希望能夠加入

**Comment by viosey** [comment]
OK

**Comment by cubesky** [comment]
记录下Facebook分享链接： https://www.facebook.com/sharer/sharer.php?u=<URL>
之后的版本中会加入
